// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Chart/setting/nls/strings":{chartTasks:"Kaavioteht\u00e4v\u00e4t",addNew:"Lis\u00e4\u00e4 uusi",addNewTip:"Lis\u00e4\u00e4 uusi kaavioteht\u00e4v\u00e4",name:"Nimi",set:"Aseta",setDataSource:"M\u00e4\u00e4rit\u00e4 aineistol\u00e4hde",generalSettingsTip:"M\u00e4\u00e4rit\u00e4 kaavioiden aineistol\u00e4hde, otsikko ja kuvaus.",chartModeSettingTip:"Valitse tapa, jolla tiedot analysoidaan ja n\u00e4ytet\u00e4\u00e4n kaavioina.",detailsSettingTip:"M\u00e4\u00e4rit\u00e4 kaavion ulkoasu m\u00e4\u00e4ritt\u00e4m\u00e4ll\u00e4 kaavion tyyppi ja v\u00e4ri sek\u00e4 kaavioon sis\u00e4llytett\u00e4v\u00e4t arvot:",
symbolSettingTip:"M\u00e4\u00e4rit\u00e4 kartta kaaviotietojen n\u00e4ytt\u00e4mist\u00e4 varten.",addFilterTip:"Lis\u00e4\u00e4 tietoihin suodatin",dataSource:"Tietol\u00e4hde",noResults:"Kohdetta ei l\u00f6ytynyt.",chartTitle:"Kaavion otsikko",description:"Kuvaus",chartingMode:"Kaavion n\u00e4ytt\u00f6",featureOption:"N\u00e4yt\u00e4 arvot kohteittain",categoryOption:"N\u00e4yt\u00e4 arvot luokittain",countOption:"N\u00e4yt\u00e4 kohdem\u00e4\u00e4r\u00e4t luokittain",fieldOption:"N\u00e4yt\u00e4 ominaisuustietoarvot kaavioina",
category:"Luokka",axisLabel:"Luokan tunnusteksti",categoryField:"Luokkakentt\u00e4",operation:"Toiminto",originalOption:"K\u00e4yt\u00e4 alkuper\u00e4isi\u00e4 arvoja",sumOption:"Summa",averageOption:"Keskiarvo",minOption:"Minimi",maxOption:"Enimm\u00e4isarvo",valueFields:"Luokituskentt\u00e4t",moveUp:"Siirr\u00e4 yl\u00f6s",moveDown:"Siirr\u00e4 alas",sortOrder:"J\u00e4rjest\u00e4 kaaviot luokan tunnustekstin mukaan",ascending:"Nouseva",descending:"Laskeva",chartType:"Kaavion tyyppi",column:"Sarakekaavio",
bar:"Palkkikaavio",line:"Viivakaavio",pie:"Ympyr\u00e4kaavio",chartColor:"Kaavion v\u00e4ri",showDataLabels:"N\u00e4yt\u00e4 tietojen tunnustekstit",setSymbol:"Valintasymboli",setHighLightColor:"Korostusv\u00e4ri",settings:"Asetukset",mapInterationOptions:"Kartan vuorovaikutteisuusasetukset",preview:"Esikatselu",ok:"OK",cancel:"Peruuta",close:"Sulje",setFilterTip:"M\u00e4\u00e4rit\u00e4 suodatin oikein. ",setChartTitleTip:"M\u00e4\u00e4rit\u00e4 kaavion otsikko.",setChartTypeTip:"Valitse v\u00e4hint\u00e4\u00e4n yksi kaaviotyyppi.",
setDataFieldTip:"Valitse v\u00e4hint\u00e4\u00e4n yksi arvokentt\u00e4.",setOutputFieldTip:"M\u00e4\u00e4rit\u00e4 tuloskent\u00e4t",count:"Lukum\u00e4\u00e4r\u00e4",label:"Tunnusteksti",horizontalAxis:"Vaaka-akseli",verticalAxis:"Pystyakseli",dataLabels:"Tietojen tunnustekstit",color:"V\u00e4ri",colorful:"V\u00e4rik\u00e4s",monochromatic:"Yksiv\u00e4rinen",noTaskTip:"Lis\u00e4\u00e4 kaavioteht\u00e4v\u00e4 napsauttamalla Lis\u00e4\u00e4 uusi -vaihtoehtoa",info:"Tiedot",charts:"Kaaviot",options:"Valinnat",
taskName:"Teht\u00e4v\u00e4n nimi",summary:"Yhteenveto",resultDescription:"Tuloksen kuvaus",spatialFilterTip:"Valitse sijaintisuodattimet, joita k\u00e4ytet\u00e4\u00e4n pienoisohjelmassa tulosten rajoittamiseen.",defaultOption:"Oletus",useCurrentExtentTip:"Osittain tai kokonaan nykyisess\u00e4 karttalaajuudessa",useDrawGraphicTip:"Osittain tai kokonaan karttaan piirretyn muodon sis\u00e4ll\u00e4",useFeaturesTip:"Niiden sijaintien perusteella suhteessa toisen karttatason kohteisiin",noSpatialLimitTip:"\u00c4l\u00e4 rajoita tuloksia sijaintitietojen mukaan",
drawingTools:"Piirtoty\u00f6kalut",bufferSettings:"Puskurin asetukset",defaultDistance:"Oletuset\u00e4isyys",bufferDistance:"Puskurin et\u00e4isyys",defaultUnit:"Oletusyksikk\u00f6",miles:"Mailia",kilometers:"Kilometri\u00e4",feet:"Jalka",meters:"Metri\u00e4",yards:"Jaardia",nauticalMiles:"Meripeninkulmaa",availableSpatialRelationships:"K\u00e4ytett\u00e4viss\u00e4 olevat sijaintisuhteet",setSpatialRelationships:"M\u00e4\u00e4rit\u00e4 sijaintisuhteet",availability:"Saatavuus",relationship:"Suhde",
actions:"Toimet",intersect:"leikkaa",contain:"sis\u00e4lt\u00e4\u00e4",areContainedIn:"sis\u00e4ltyv\u00e4t",cross:"risti",envelopeIntersect:"rajojen leikkaus",overlap:"limittyy",areOverlapped:"on p\u00e4\u00e4llekk\u00e4in",touche:"koskettaa",within:"sis\u00e4ss\u00e4",areWithin:"on sis\u00e4ss\u00e4",indexIntersect:"indeksin leikkaus",_localized:{}}});