// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Chart/setting/nls/strings":{chartTasks:"\u00dalohy graf\u016f",addNew:"P\u0159idat nov\u00fd",addNewTip:"P\u0159idat novou \u00falohu grafu",name:"N\u00e1zev",set:"Nastavit",setDataSource:"Nastavit zdroj dat",generalSettingsTip:"Nastavte zdroj dat, n\u00e1zev a popis grafu.",chartModeSettingTip:"Zvolte zp\u016fsob, kter\u00fdm chcete data analyzovat a zobrazovat v grafech.",detailsSettingTip:"Nastavte vzhled grafu zvolen\u00edm typu grafu, barev a hodnot vykreslen\u00fdch v\u00a0grafu:",
symbolSettingTip:"Nastavte zobrazen\u00ed mapy pro data zpracovan\u00e1 v grafu.",addFilterTip:"P\u0159idat filtr k t\u011bmto dat\u016fm",dataSource:"Zdroj dat",noResults:"Nebyl nalezen \u017e\u00e1dn\u00fd prvek",chartTitle:"N\u00e1zev grafu",description:"Popis",chartingMode:"Zobrazen\u00ed grafu",featureOption:"Zobrazit hodnoty prvek po prvku",categoryOption:"Zobrazit hodnoty podle kategorie",countOption:"Zobrazit po\u010dty prvk\u016f podle kategorie",fieldOption:"Zobrazit hodnoty atribut\u016f jako grafy",
category:"Kategorie",axisLabel:"Popisek kategorie",categoryField:"Pole kategorie",operation:"Operace",originalOption:"Pou\u017e\u00edt p\u016fvodn\u00ed hodnoty",sumOption:"Sou\u010det",averageOption:"Pr\u016fm\u011br",minOption:"Minimum",maxOption:"Maximum",valueFields:"Pole hodnot",moveUp:"P\u0159esunout nahoru",moveDown:"P\u0159esunout dol\u016f",sortOrder:"\u0158adit grafy podle popisk\u016f kategori\u00ed",ascending:"Vzestupn\u011b",descending:"Sestupn\u011b",chartType:"Typ grafu",column:"Sloupcov\u00fd graf",
bar:"Pruhov\u00fd graf",line:"Spojnicov\u00fd graf",pie:"Kol\u00e1\u010dov\u00fd graf",chartColor:"Barva grafu",showDataLabels:"Zobrazit popisky dat",setSymbol:"Symbol v\u00fdb\u011bru",setHighLightColor:"Barva zv\u00fdrazn\u011bn\u00ed",settings:"Nastaven\u00ed",mapInterationOptions:"Mo\u017enosti interakce s mapou",preview:"N\u00e1hled",ok:"OK",cancel:"Storno",close:"Zav\u0159\u00edt",setFilterTip:"Nastavte filtr spr\u00e1vn\u011b. ",setChartTitleTip:"Nastavte n\u00e1zev grafu.",setChartTypeTip:"Vyberte alespo\u0148 jeden typ grafu.",
setDataFieldTip:"Vyberte alespo\u0148 jedno pole s  hodnotami.",setOutputFieldTip:"Nastavte v\u00fdstupn\u00ed pole.",count:"Po\u010det",label:"\u0160t\u00edtek",horizontalAxis:"Vodorovn\u00e1 osa",verticalAxis:"Svisl\u00e1 osa",dataLabels:"Popisky dat",color:"Barva",colorful:"Barevn\u00e9",monochromatic:"Monochromatick\u00e9",noTaskTip:"Kliknut\u00edm na P\u0159idat nov\u00fd p\u0159id\u00e1te novou \u00falohu grafu",info:"Informace",charts:"Grafy",options:"Mo\u017enosti",taskName:"N\u00e1zev \u00falohy",
summary:"Souhrn",resultDescription:"Popis v\u00fdsledku",spatialFilterTip:"Zvolte prostorov\u00e9 filtry, kter\u00e9 se ve widgetu pou\u017eij\u00ed k\u00a0omezen\u00ed v\u00fdsledk\u016f.",defaultOption:"V\u00fdchoz\u00ed",useCurrentExtentTip:"Z\u010d\u00e1sti nebo zcela v\u00a0aktu\u00e1ln\u00edm rozsahu mapy",useDrawGraphicTip:"Z\u010d\u00e1sti nebo zcela v\u00a0obrazci nakreslen\u00e9m v\u00a0map\u011b",useFeaturesTip:"Na z\u00e1klad\u011b um\u00edst\u011bn\u00ed prvk\u016f v\u00a0jin\u00e9 vrstv\u011b",
noSpatialLimitTip:"Neomezovat v\u00fdsledky podle polohy",drawingTools:"N\u00e1stroje kreslen\u00ed",bufferSettings:"Nastaven\u00ed obalov\u00e9 z\u00f3ny",defaultDistance:"V\u00fdchoz\u00ed vzd\u00e1lenost",bufferDistance:"\u0160\u00ed\u0159ka obalov\u00e9 z\u00f3ny",defaultUnit:"V\u00fdchoz\u00ed jednotka",miles:"M\u00edle",kilometers:"Kilometry",feet:"Stopy",meters:"Metry",yards:"Yardy",nauticalMiles:"N\u00e1mo\u0159n\u00ed m\u00edle",availableSpatialRelationships:"Dostupn\u00e9 prostorov\u00e9 vztahy",
setSpatialRelationships:"Nastavit prostorov\u00e9 vztahy",availability:"Dostupnost",relationship:"Relace",actions:"Akce",intersect:"prot\u00ednaj\u00ed",contain:"obsahuj\u00ed",areContainedIn:"jsou obsa\u017eeny v",cross:"k\u0159\u00ed\u017eek",envelopeIntersect:"prot\u00ednaj\u00ed ob\u00e1lku",overlap:"p\u0159ekr\u00fdvaj\u00ed",areOverlapped:"jsou p\u0159ekryt\u00e9",touche:"dot\u00fdkaj\u00ed se",within:"v dosahu",areWithin:"jsou v\u00a0dosahu",indexIntersect:"prot\u00ednaj\u00ed index",_localized:{}}});