// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Chart/setting/nls/strings":{chartTasks:"Tareas de gr\u00e1ficos",addNew:"Agregar nueva",addNewTip:"Agregar una nueva tarea de gr\u00e1fico",name:"Nombre",set:"Establecer",setDataSource:"Definir fuente de datos",generalSettingsTip:"Define la fuente de datos, el t\u00edtulo y la descripci\u00f3n de los gr\u00e1ficos.",chartModeSettingTip:"Selecciona una forma de analizar y visualizar los datos como gr\u00e1ficos.",detailsSettingTip:"Define el aspecto del gr\u00e1fico especificando su tipo y su color, as\u00ed como los valores que se deben representar:",
symbolSettingTip:"Define la vista del mapa para los datos representados.",addFilterTip:"Agregar filtro a estos datos",dataSource:"Fuente de datos",noResults:"Ninguna entidad encontrada.",chartTitle:"T\u00edtulo del gr\u00e1fico",description:"Descripci\u00f3n",chartingMode:"Vista del gr\u00e1fico",featureOption:"Mostrar valores entidad por entidad",categoryOption:"Mostrar valores por categor\u00eda",countOption:"Mostrar recuentos de entidades por categor\u00eda",fieldOption:"Mostrar valores de atributos como gr\u00e1ficos",
category:"Categor\u00eda",axisLabel:"Etiqueta de categor\u00eda",categoryField:"Campo de categor\u00eda",operation:"Operaci\u00f3n",originalOption:"Usar valores originales",sumOption:"Suma",averageOption:"Promedio",minOption:"M\u00ednimo",maxOption:"M\u00e1ximo",valueFields:"Campos de valores",moveUp:"Mover hacia arriba",moveDown:"Mover hacia abajo",sortOrder:"Ordenar gr\u00e1ficos por medio de etiquetas de categor\u00edas",ascending:"Ascendente",descending:"Descendente",chartType:"Tipo de gr\u00e1fico",
column:"Gr\u00e1fico de columnas",bar:"Gr\u00e1fico de barras",line:"Gr\u00e1fico de l\u00edneas",pie:"Gr\u00e1fico circular",chartColor:"Color del gr\u00e1fico",showDataLabels:"Mostrar etiquetas de datos",setSymbol:"S\u00edmbolo de selecci\u00f3n",setHighLightColor:"Color de resaltado",settings:"Configuraci\u00f3n",mapInterationOptions:"Opciones de interacci\u00f3n del mapa",preview:"Presentaci\u00f3n preliminar",ok:"Aceptar",cancel:"Cancelar",close:"Cerrar",setFilterTip:"Define correctamente el filtro. ",
setChartTitleTip:"Define el t\u00edtulo del gr\u00e1fico.",setChartTypeTip:"Selecciona al menos un tipo de gr\u00e1fico.",setDataFieldTip:"Selecciona al menos un campo de valor.",setOutputFieldTip:"Define los campos de salida.",count:"Recuento",label:"Etiqueta",horizontalAxis:"Eje horizontal",verticalAxis:"Eje vertical",dataLabels:"Etiquetas de datos",color:"Color",colorful:"Multicolor",monochromatic:"Monocrom\u00e1tico",noTaskTip:"Haz clic en Agregar nuevo para agregar una tarea de gr\u00e1fico",
info:"Informaci\u00f3n",charts:"Cartas",options:"Opciones",taskName:"Nombre de tarea",summary:"Resumen",resultDescription:"Descripci\u00f3n del resultado",spatialFilterTip:"Elige los filtros espaciales utilizados en el widget para limitar los resultados.",defaultOption:"Predeterminado",useCurrentExtentTip:"Parcial o totalmente dentro de la extensi\u00f3n de mapa actual",useDrawGraphicTip:"Parcial o totalmente dentro de la forma dibujada en el mapa",useFeaturesTip:"En funci\u00f3n de sus ubicaciones con respecto a las entidades de otra capa",
noSpatialLimitTip:"No limitar espacialmente los resultados",drawingTools:"Herramientas de dibujo",bufferSettings:"Configuraci\u00f3n de la zona de influencia",defaultDistance:"Distancia predeterminada",bufferDistance:"Distancia de zona de influencia",defaultUnit:"Unidad predeterminada",miles:"Millas",kilometers:"Kil\u00f3metros",feet:"Pies",meters:"Metros",yards:"Yardas",nauticalMiles:"Millas N\u00e1uticas",availableSpatialRelationships:"Relaciones espaciales disponibles",setSpatialRelationships:"Definir relaciones espaciales",
availability:"Disponibilidad",relationship:"Relaci\u00f3n",actions:"Acciones",intersect:"intersecar",contain:"contienen",areContainedIn:"est\u00e1n contenidas en",cross:"cruz",envelopeIntersect:"intersecci\u00f3n con el contorno",overlap:"superponer",areOverlapped:"se superponen",touche:"se tocan",within:"dentro de",areWithin:"est\u00e1n dentro de",indexIntersect:"con intersecci\u00f3n de \u00edndice",_localized:{}}});