// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/setting/nls/strings":{queries:"Consultas",addNew:"Adicionar Nova",queryLayer:"Camada de Consulta",setSource:"Definir",setDataSource:"Definir Fonte dos Dados",name:"Nome",querySource:"Fonte da Dados",queryName:"Nome da Tarefa",queryDefinition:"Defini\u00e7\u00e3o do Filtro",resultsSetting:"Defini\u00e7\u00e3o de Resultados",symbolSetting:"Defini\u00e7\u00f5es de s\u00edmbolos",resultSettingTip:"Defina o qu\u00ea e como exibir os resultados de sa\u00edda.",resultItemTitle:"T\u00edtulo do Item Resultante",
resultItemContent:"Conte\u00fado do Item Resultante",fieldsSetTip:"Marque os campos que pretende exibir. Selecione um campo para atualizar o seu nome alternativo, orden\u00e1-lo e format\u00e1-lo.",addField:"Adicionar Campo",visibility:"Visibilidade",alias:"Nome Alternativo",specialType:"Tipo Especial",actions:"A\u00e7\u00f5es",none:"Nenhum",link:"Liga\u00e7\u00e3o",image:"Imagem",noField:"Sem Campo",operationalLayerTip:"Adicionar resultado como camada operacional",setLayerSymbolTip:"Definir o s\u00edmbolo para os resultados da consulta. ",
setSelectedSymbolTip:"Definir o s\u00edmbolo do elemento selecionado.",notUseFilter:"N\u00e3o utilizar filtro",setSourceTip:"Por favor, defina a fonte da consulta.",setFilterTip:"Por favor, defina o filtro corretamente.",ok:"Ok",cancel:"Cancelar",noFilterTip:"Sem uma express\u00e3o de filtro definida, esta tarefa de consulta ir\u00e1 listar todos os elementos na fonte de dados especificada.",relationships:"Rela\u00e7\u00f5es",addRelationshipLayer:"Adicionar Nova Rela\u00e7\u00e3o",relatedTo:"Relacionado com",
selectOption:"Por favor, selecione..",resultItemSorting:"Classificando Resultado de Item",field:"Campo",sortingOrder:"Ordem",configureFieldsTip:"Por favor configure os campos nos quais o resultado da consulta ser\u00e1 ordenada por.",setSortingFields:"Definir Sele\u00e7\u00e3o Campos",ascending:"Ascendente",descending:"Decrescente",sortBy:"Ordenar por",thenBy:"De seguida por",addTask:"Adicionar Tarefa",noTasksTip:'Sem tarefas, por favor clique em "${addTask}" para come\u00e7ar!',infoText:"Informa\u00e7\u00e3o",
filters:"Filtros",results:"Resultados",optionsText:"Op\u00e7\u00f5es",summaryText:"Resumo",attributeFilter:"Filtro de Atributos",attributeFilterTip:"Defina express\u00f5es de atributos para utilizar no widget para filtrar a camada da consulta.",noExpressionDefinedTip:"N\u00e3o foi definida qualquer express\u00e3o.",needInputValuesTip:"\u00c9 necess\u00e1rio introduzir valores no runtime",setExpressions:"Definir Express\u00f5es",spatialFilter:"Filtro Espacial",spatialFilterTip:"Escolha o(s) filtro(s) espacial(ais) utilizados no widget para limitar os resultados.",
defaultOption:"Padr\u00e3o",useCurrentExtentTip:"Parcialmente ou totalmente no contido na atual extens\u00e3o de mapa",useDrawGraphicTip:"Parcialmente ou totalmente no contido na forma desenhada no mapa",useFeaturesTip:"Baseado nas respetivas localiza\u00e7\u00f5es em rela\u00e7\u00e3o a elementos noutra camada",noSpatialLimitTip:"N\u00e3o limita resultados espacialmente",drawingTools:"Ferramentas de desenho",bufferSettings:"Defini\u00e7\u00f5es de Buffer",defaultDistance:"Dist\u00e2ncia Padr\u00e3o",
bufferDistance:"Dist\u00e2ncia do Buffer",defaultUnit:"Unidade Padr\u00e3o",miles:"Milhas",kilometers:"Quil\u00f4metros",feet:"P\u00e9s",meters:"Metros",yards:"Jardas",nauticalMiles:"Milhas N\u00e1uticas",availableSpatialRelationships:"Rela\u00e7\u00f5es Espaciais Dispon\u00edveis",setSpatialRelationships:"Definir Rela\u00e7\u00f5es Espaciais",availability:"Disponibilidade",relationship:"Relacionamento",label:"R\u00f3tulo",intersect:"intersetar",contain:"conter",areContainedIn:"est\u00e3o contidos em",
cross:"cruz",envelopeIntersect:"interse\u00e7\u00e3o envelope",overlap:"sobrepor",areOverlapped:"est\u00e3o sobrepostos",touche:"touche",within:"contidos",areWithin:"est\u00e3o contidos",indexIntersect:"interse\u00e7\u00e3o \u00edndice",itemTitle:"T\u00edtulo do Item",displayFields:"Campos de Visualiza\u00e7\u00e3o",sortingFields:"A Ordenar Campos",setDisplayFields:"Definir Exibir Campos",symbol:"S\u00edmbolo",setSymbol:"Definir s\u00edmbolo",serviceSymbolTip:"Utilizar s\u00edmbolos definidos pela camada",
exportTip:"Exibir bot\u00e3o Exportar",keepResultsTip:"Manter resultados no mapa ap\u00f3s fechar o widget",queryRelatedRecords:"Registos relacionados com a consulta",createLayerForTaskTip:"Especificar como a tarefa cria as camadas",oneLayerForTaskTip:"Apenas criar uma camada para esta tarefa",multipleLayerForTaskTip:"Criar uma nova camada de cada vez que esta tarefa for executada",_localized:{}}});