// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/nls/strings":{_widgetLabel:"P\u00e4ring",executeQueryTip:"P\u00e4ringu k\u00e4ivitamiseks kl\u00f5psake \u00fchte j\u00e4rgmistest sisuobjekti toimingutest.",invalidConfig:"Vigane seadistus. \u00d5ige seadistuse hankimiseks kasutage p\u00e4ringu seadete lehte.",queryParams:"Valikud",parameters:"VALIKUD",queries:"P\u00c4RINGUD",apply:"RAKENDA",queryResults:"Tulemused",clear:"Puhasta",noResults:"Objekte ei leitud.",queryError:"P\u00e4ring eba\u00f5nnestus!",numberFound:"Leitud objektide arv",
mapExtentTip:"Piira tulemusi kaardi praeguse kuvaulatusega.",noValue:"V\u00e4\u00e4rtus puudub",and:"ja",stringOperatorIs:"on",stringOperatorIsNot:"ei ole",stringOperatorStartsWith:"algab",stringOperatorEndsWith:"l\u00f5peb",stringOperatorContains:"sisaldab",stringOperatorDoesNotContain:"ei sisalda",stringOperatorIsBlank:"on t\u00fchi",stringOperatorIsNotBlank:"ei ole t\u00fchi",dateOperatorIsOn:"on",dateOperatorIsNotOn:"ei ole",dateOperatorIsBefore:"on enne",dateOperatorIsAfter:"on p\u00e4rast",
dateOperatorDays:"p\u00e4eva",dateOperatorWeeks:"n\u00e4dalat",dateOperatorMonths:"kuud",dateOperatorInTheLast:"viimases",dateOperatorNotInTheLast:"mitte viimases",dateOperatorIsBetween:"on vahemikus",dateOperatorIsNotBetween:"ei ole vahemikus",dateOperatorIsBlank:"on t\u00fchi",dateOperatorIsNotBlank:"ei ole t\u00fchi",numberOperatorIs:"on",numberOperatorIsNot:"ei ole",numberOperatorIsAtLeast:"on v\u00e4hemalt",numberOperatorIsLessThan:"on v\u00e4iksem kui",numberOperatorIsAtMost:"on k\u00f5ige",
numberOperatorIsGreaterThan:"on suurem kui",numberOperatorIsBetween:"on vahemikus",numberOperatorIsNotBetween:"ei ole vahemikus",numberOperatorIsBlank:"on t\u00fchi",numberOperatorIsNotBlank:"ei ole t\u00fchi",operationalLayerTip:"Lisa tulemus t\u00f6\u00f6kihina",queryResult:"P\u00e4ringu tulemus",specifyParamsTip:"M\u00e4\u00e4ra selle \u00fclesande jaoks parameetrid",useSpatialFilter:"Kasuta objektide piiramiseks ruumifiltrit",useCurrentMapExtent:"Vaid praeguse kaardiulatusega l\u00f5ikuvad objektid",
drawGraphicOnMap:"Vaid kasutaja poolt m\u00e4\u00e4ratletud alaga l\u00f5ikuvad objektid",specifySpatialFilterMsg:"M\u00e4\u00e4rake selle \u00fclesande jaoks ruumifilter.",clearResults:"Kustuta tulemused",operationalTip:'Kui see valik on m\u00e4rgitud, kuvatakse tulemused kaardil seni, kuni klikite nuppu "${clearResults}".',noneQueryTip:"Selle vidina jaoks pole konfigureeritud p\u00e4ringu toimingut.",noPermissionsMsg:"Teil puudub juurdep\u00e4\u00e4s sellele teenusele.",attributesFromRelationship:"Atribuudid seotud tabelist",
tasks:"Toimingud",applySpatialFilterToLimitResults:"Rakenda tulemuste piiramiseks ruumifilter",useCurrentExtentTip:"Osaliselt v\u00f5i t\u00e4ielikult praeguses kaardi kuvaulatuses",useDrawGraphicTip:"Osaliselt v\u00f5i t\u00e4ielikult kaardile joonistatud kujundis",useFeaturesTip:"Vastavalt nende asukohale teise kihi objektide suhtes",noSpatialLimitTip:"\u00c4ra piira tulemusi ruumiliselt",applySearchDistance:"Rakenda otsingu vahemaad",spatialRelationship:"Ruumiline seos",relatedLayer:"Seotud kiht",
bufferDistance:"Puhvri ulatus",miles:"Miilid",kilometers:"Kilomeetrid",feet:"Jalad",meters:"Meetrid",yards:"Jardid",nauticalMiles:"Meremiilid",back:"Tagasi",execute:"K\u00e4ivita",_localized:{}}});