// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"widgets/AttributeTable/utils":function(){define("dojo/_base/lang dojo/_base/array jimu/LayerInfos/LayerInfos dojo/Deferred dojo/promise/all exports dojo/store/Observable dojo/store/Cache dojo/store/Memory esri/lang ./FeatureLayerQueryStore jimu/utils".split(" "),function(g,p,r,q,d,b,k,t,h,l,s,n){function v(a){var e=[],c=[];p.forEach(a,function(f){var u=e.indexOf(f.name);0>u?e.push(f.name):(c.push(a[u]),c.push(f))});p.forEach(c,function(a){a.name=a.name+"-"+a.id})}function m(a,e){if(!a||
!a.length)return e||[];if(!e||!e.length)return a;for(var c=[],f=0,u=a.length;f<u;f++)for(var d=a[f],b=0,k=e.length;b<k;b++)if(e[b].name===d.name){c.push(d);break}return c}b.readLayerInfosObj=function(a){return r.getInstance(a,a.itemInfo)};b.readLayerInfosFromMap=function(a,e,c){var f=new q;r.getInstance(a,a.itemInfo).then(g.hitch(this,function(a){var d=[];e?a.traversalLayerInfosOfWebmap(function(a){d.push(a)}):a.traversal(function(a){d.push(a)});if(c){var b=[],k=a.getMapNotesLayerInfoArray();p.forEach(k,
function(a){b.push(a.id);a.traversal(function(a){b.push(a.id)})});d=p.filter(d,function(a){return-1===b.indexOf(a.id)})}a=a.getTableInfoArray();d=d.concat(a);f.resolve(d)}),g.hitch(this,function(a){console.error(a);f.reject(a)}));return f.promise};b.generateColumnsFromFields=function(a,e,c,f,d){function k(e){if(a&&l.isDefined(a.fieldInfos))for(var c=0,f=a.fieldInfos.length;c<f;c++){var d=a.fieldInfos[c];if(d.fieldName===e)return d.format}return null}var m={};p.forEach(e,g.hitch(b,function(a,e,h){var n=
"field"+e,t=!!a.domain,q="esriFieldTypeDate"===a.type,s=c&&a.name===c;m[n]={label:a.alias||a.name,className:n,hidden:1===h.length?!1:!a.show&&l.isDefined(a.show),unhidable:1===h.length?!1:!a.show&&l.isDefined(a.show)&&a._pk,field:a.name};m[n].sortable=!!d;if("esriFieldTypeString"===h[e].type)m[n].formatter=g.hitch(b,b.urlFormatter);else if("esriFieldTypeDate"===h[e].type)m[n].formatter=g.hitch(b,b.dateFormatter,k(a.name));else if("esriFieldTypeDouble"===h[e].type||"esriFieldTypeSingle"===h[e].type||
"esriFieldTypeInteger"===h[e].type||"esriFieldTypeSmallInteger"===h[e].type)m[n].formatter=g.hitch(b,b.numberFormatter,k(a.name));t?m[n].get=g.hitch(b,function(a,e){return this.getCodeValue(a.domain,e[a.name])},a):s?m[n].get=g.hitch(b,function(a,e,c){return this.getTypeName(c[a.name],e)},a,f):!t&&(!q&&!s)&&(m[n].get=g.hitch(b,function(a,e,c,f){var d=null;e&&c&&0<c.length&&(c=(c=p.filter(c,g.hitch(b,function(a){return a.name===f[e]})))&&c[0]||null)&&(c.domains&&c.domains[a.name]&&c.domains[a.name].codedValues)&&
(d=this.getCodeValue(c.domains[a.name],f[a.name]));return(a=null!==d?d:f[a.name])||isFinite(a)?a:""},a,c,f))}));return m};b.getTypeName=function(a,e){return n.fieldFormatter.getTypeName(a,e)};b.getCodeValue=function(a,e){return n.fieldFormatter.getCodedValue(a,e)};b.urlFormatter=function(a){return n.fieldFormatter.getFormattedUrl(a)};b.dateFormatter=function(a,e){return n.fieldFormatter.getFormattedDate(e,a)};b.numberFormatter=function(a,e){return n.fieldFormatter.getFormattedNumber(e,a)};b.readLayerObjectsFromMap=
function(a,e,c){var f=new q,b=[];this.readLayerInfosFromMap(a,e,c).then(g.hitch(this,function(a){p.forEach(a,g.hitch(this,function(a){b.push(a.getLayerObject())}));d(b).then(g.hitch(this,function(a){f.resolve(a)}),g.hitch(this,function(a){f.reject(a);console.error(a)}))}),g.hitch(this,function(a){f.reject(a)}));return f.promise};b.readSupportTableInfoFromLayerInfos=function(a){var e=new q,c=[];p.forEach(a,g.hitch(this,function(a){c.push(a.getSupportTableInfo())}));d(c).then(g.hitch(this,function(c){c=
g.clone(c);p.forEach(c,function(e,c){e.id=a[c].id});e.resolve(c)}),function(a){e.reject(a)});return e.promise};b.readConfigLayerInfosFromMap=function(a,e,c){var f=new q,b=[];this.readLayerInfosFromMap(a,e,c).then(g.hitch(this,function(a){var e=[];p.forEach(a,function(a){b.push(a.getSupportTableInfo())});d(b).then(g.hitch(this,function(c){p.forEach(c,g.hitch(this,function(c,f){c.isSupportedLayer&&(a[f].name=a[f].title,e.push(a[f]))}));v(e);f.resolve(e)}),g.hitch(this,function(a){f.reject(a)}))}),g.hitch(this,
function(a){f.reject(a)}));return f.promise};b.getConfigInfosFromLayerInfos=function(a){return p.map(a,function(a){return b.getConfigInfoFromLayerInfo(a)})};b.getConfigInfoFromLayerInfo=function(a){var e={};e.name=a.name||a.title;e.id=a.id;e.show=a.isShowInMap();e.layer={url:a.getUrl()};var c=a.getPopupInfo();c&&!c.description&&(e.layer.fields=p.map(c.fieldInfos,function(a){return{name:a.fieldName,alias:a.label,show:a.visible,format:a.format}}),a=g.getObject("layerObject.fields",!1,a),e.layer.fields=
m(e.layer.fields,a),p.some(e.layer.fields,function(a){return a.show})||(e.layer.fields[0].show=!0));return e};b.generateCacheStore=function(a,e,c,f,d){a=new s({layer:a,objectIds:a._objectIds||null,totalCount:e,batchCount:c,where:f||"1\x3d1",spatialFilter:d});e=new h;return new t(a,e,{})};b.generateMemoryStore=function(a,e){return new k(new h({data:a||[],idProperty:e}))};b.merge=function(a,e,c,f){for(var d=p.map(e,function(a){return a[c]}),b=0,k=a.length;b<k;b++){var m=d.indexOf(a[b][c]);-1<m&&f(a[b],
e[m])}};b.syncOrderWith=function(a,e,c){function f(a,e){return p.map(a,function(a){return a[e]})}if(!g.isArray(e)||!c)return a;for(var d=f(a,c),b=[],k=0,m=e.length;k<m;k++){var h=d.indexOf(e[k][c]);-1<h&&(b=b.concat(a.splice(h,1)),d=f(a,c))}return b.concat(a)}})},"dojo/store/Observable":function(){define(["../_base/kernel","../_base/lang","../when","../_base/array"],function(g,p,r,q){g=function(d){function b(b,k){var h=d[b];h&&(d[b]=function(m){var a;"put"===b&&(a=d.getIdentity(m));if(l)return h.apply(this,
arguments);l=!0;try{var e=h.apply(this,arguments);r(e,function(e){k("object"==typeof e&&e||m,a)});return e}finally{l=!1}})}var k=[],g=0;d=p.delegate(d);d.notify=function(d,b){g++;for(var h=k.slice(),m=0,a=h.length;m<a;m++)h[m](d,b)};var h=d.query;d.query=function(b,n){n=n||{};var l=h.apply(this,arguments);if(l&&l.forEach){var m=p.mixin({},n);delete m.start;delete m.count;var a=d.queryEngine&&d.queryEngine(b,m),e=g,c=[],f;l.observe=function(b,h){1==c.push(b)&&k.push(f=function(f,b){r(l,function(k){var m=
k.length!=n.count,l,u;if(++e!=g)throw Error("Query is out of date, you must observe() the query prior to any data modifications");var p,r=-1,s=-1;if(void 0!==b){l=0;for(u=k.length;l<u;l++){var w=k[l];if(d.getIdentity(w)==b){p=w;r=l;(a||!f)&&k.splice(l,1);break}}}if(a){if(f&&(a.matches?a.matches(f):a([f]).length))l=-1<r?r:k.length,k.splice(l,0,f),s=q.indexOf(a(k),f),k.splice(l,1),n.start&&0==s||!m&&s==k.length?s=-1:k.splice(s,0,f)}else f&&(void 0!==b?s=r:n.start||(s=d.defaultIndex||0,k.splice(s,0,
f)));if((-1<r||-1<s)&&(h||!a||r!=s)){m=c.slice();for(l=0;k=m[l];l++)k(f||p,r,s)}})});var m={};m.remove=m.cancel=function(){var a=q.indexOf(c,b);-1<a&&(c.splice(a,1),c.length||k.splice(q.indexOf(k,f),1))};return m}}return l};var l;b("put",function(b,k){d.notify(b,k)});b("add",function(b){d.notify(b)});b("remove",function(b){d.notify(void 0,b)});return d};p.setObject("dojo.store.Observable",g);return g})},"dojo/store/Cache":function(){define(["../_base/lang","../when"],function(g,p){var r=function(q,
d,b){b=b||{};return g.delegate(q,{query:function(k,g){var h=q.query(k,g);h.forEach(function(k){(!b.isLoaded||b.isLoaded(k))&&d.put(k)});return h},queryEngine:q.queryEngine||d.queryEngine,get:function(b,g){return p(d.get(b),function(h){return h||p(q.get(b,g),function(h){h&&d.put(h,{id:b});return h})})},add:function(b,g){return p(q.add(b,g),function(h){d.add(h&&"object"==typeof h?h:b,g);return h})},put:function(b,g){d.remove(g&&g.id||this.getIdentity(b));return p(q.put(b,g),function(h){d.put(h&&"object"==
typeof h?h:b,g);return h})},remove:function(b,g){return p(q.remove(b,g),function(h){return d.remove(b,g)})},evict:function(b){return d.remove(b)}})};g.setObject("dojo.store.Cache",r);return r})},"widgets/AttributeTable/FeatureLayerQueryStore":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array esri/tasks/query esri/tasks/QueryTask ./FeatureLayerQueryResult".split(" "),function(g,p,r,q,d,b){return g(null,{queryUrl:"",idProperty:"id",data:null,_entityData:null,constructor:function(b){g.safeMixin(this,
b);this.data=[];this._entityData=[];this.layer=b.layer;this.objectIds=b.objectIds;this.where=b.where;this.orderByFields=b.orderByFields;this.totalCount=b.totalCount;this.batchCount=b.batchCount||25;this.idProperty=this.layer.objectIdField;this.spatialFilter=b.spatialFilter;this.layer&&this.layer.url&&(this.queryTask=new d(this.layer.url))},get:function(b){return this.data[b]},getIdentity:function(b){return b[this.idProperty]},query:function(d,g){var h=new q,l=g&&g.start||0,s=this.batchCount,n=null;
"function"===typeof d?n=d(this._entityData):"[object Array]"===Object.prototype.toString.call(d)&&(n=d);if(this.objectIds)n=n?n:this.objectIds,h.objectIds=n.length>=l+this.batchCount?n.slice(l,l+s):n.slice(l);else if(n&&0<n.length?h.objectIds=n.length>=l+this.batchCount?n.slice(l,l+s):n.slice(l):(h.start=l,h.num=s,h.where=this.where,h.geometry=this.spatialFilter,h.spatialRelationship=q.SPATIAL_REL_INTERSECTS),(l=g.sort)&&0<l.length)l=r.map(l,function(b){return b.attribute+" "+(b.descending?"DESC":
"ASC")}),h.orderByFields=l;h.returnGeometry=!1;h.outFields=["*"];var v=this.totalCount,l=null,l=!h.where;if(!(h.objectIds&&0<h.objectIds.length)&&l)return new b([]);l=this.queryTask?this.queryTask.execute(h):this.layer.queryFeatures(h);l.total=l.then(p.hitch(this,function(b){var a=0,e=this.layer.objectIdField;if(this.objectIds){if(!e)for(a=0;a<b.fields.length;a++)if("esriFieldTypeOID"===b.fields[a].type){e=b.fields[a].name;break}for(var c={},a=0;a<b.features.length;a++)c[b.features[a].attributes[e]]=
b.features[a];b.features=r.map(h.objectIds,function(a){return c[a]})}for(a=0;a<b.features.length;a++)b.features[a]&&(b.features[a]=b.features[a].attributes,this.data[b.features[a][e]]=b.features[a],this._entityData.push(b.features[a]));b=b.features;return v}),function(){console.log("FeatureLayerQueryStore queryFeatures failed.");return 0});return new b(l)}})})},"widgets/AttributeTable/FeatureLayerQueryResult":function(){define("esri/main dojo/_base/lang dojo/_base/kernel dojo/_base/Deferred dojo/DeferredList dojo/_base/array".split(" "),
function(g,p,r,q){var d=function(b){function k(g){b[g]||(b[g]=function(){var h=arguments;return q.when(b,function(b){Array.prototype.unshift.call(h,b.features||b);return d(r[g].apply(r,h))})})}if(!b)return b;b.then&&(b=p.delegate(b));b.total||(b.total=q.when(b,function(b){return g._isDefined(b.total)?b.total:b.length||0}));k("forEach");k("filter");k("map");k("some");k("every");return b};return d})},"widgets/AttributeTable/setting/_build-generate_module":function(){define(["dojo/text!./Setting.html",
"dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/AttributeTable/setting/Setting.html":'\x3cdiv style\x3d"width:100%;"\x3e\r\n  \x3cdiv class\x3d"instruction"\x3e\r\n    \x3cp\x3e${nls.instruction}\x3c/p\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"tableLayerInfos" class\x3d"table-layer-infos"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"table-options jimu-ellipsis"\x3e\r\n    \x3cul\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"exportcsv" checked\r\n        data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.exportCSV}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"expand" data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.expand}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"filterByMapExtent" data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.filterByExtent}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n    \x3c/ul\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
"url:widgets/AttributeTable/setting/css/style.css":".jimu-widget-attributetable-setting{margin:0; padding:0; font-size:14px; width: 100%; height: 100%; position: relative; color: #596679;}.jimu-widget-attributetable-setting .instruction{font-size: 12px; margin-bottom: 10px;}.jimu-widget-attributetable-setting .show{width: 120px;}.jimu-widget-attributetable-setting .symbol{width: 200px;}.jimu-widget-attributetable-setting .table-layer-infos{width: 100%; height: 396px;}.jimu-widget-attributetable-setting .table-options ul{list-style-type: none; padding: 0;}.jimu-widget-attributetable-setting .jimu-checkbox{margin-right: 20px;}.jimu-widget-attributetable-setting .disable-checkbox{color: #e5e5e5;}",
"*now":function(g){g(['dojo/i18n!*preload*widgets/AttributeTable/setting/nls/Setting*["ar","cs","da","de","en","el","es","et","fi","fr","he","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])}}});
define("dojo/_base/declare dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/Deferred dojo/query jimu/dijit/Popup jimu/dijit/Message jimu/dijit/LoadingShelter ../utils".split(" "),function(g,p,r,q,d,b,k,t,h,l,s,n,v,m){return g([r,p],{baseClass:"jimu-widget-attributetable-setting",currentFieldTable:null,_allLayerFields:null,_layerInfos:null,_tableInfos:null,_delayedLayerInfos:null,_delayedLayerInfosAfterInit:null,
_unSpportQueryCampsite:null,startup:function(){this.inherited(arguments);this.config.layerInfos||(this.config.layerInfos=[]);this._allLayerFields=[];this._layerInfos=[];this._tableInfos=[];this._delayedLayerInfos=[];this._delayedLayerInfosAfterInit=[];this._unSpportQueryCampsite={};this.displayFieldsTable=new q({fields:[{name:"show",title:this.nls.show,width:"auto",type:"checkbox","class":"show"},{name:"label",title:this.nls.label,width:"60%",type:"text"},{name:"url",title:"url",type:"text",hidden:!0},
{name:"index",title:"index",type:"text",hidden:!0},{name:"actions",title:this.nls.actions,type:"actions",width:"20%",actions:["edit"],"class":"symbol"}],selectable:!0,autoHeight:!1});this.displayFieldsTable.placeAt(this.tableLayerInfos);b.setStyle(this.displayFieldsTable.domNode,{height:"100%"});this.shelter=new v({hidden:!0});this.shelter.placeAt(this.domNode.parentNode.parentNode||this.domNode);this.shelter.startup();this.shelter.show();m.readLayerInfosObj(this.map).then(d.hitch(this,function(a){this.own(a.on("layerInfosChanged",
d.hitch(this,this.onLayerInfosChanged)));this.own(t(this.displayFieldsTable,"actions-edit",d.hitch(this,this.editFieldsClick)));this.own(t(this.displayFieldsTable,"row-click",d.hitch(this,this._verifiedOnShowClick)));this.setConfig(this.config)}))},editFieldsClick:function(a){var b=l(".action-item-parent",a);if(b&&b.length)if(b=this.displayFieldsTable.getRowData(a),b.show){var c=parseInt(b.index,10);this.shelter.show();this._getLayerFields(c).then(d.hitch(this,function(b){this.openFieldsDialog(a,
b,c)}),d.hitch(this,function(a){console.error(a)})).always(d.hitch(this,function(){this.shelter.hide()}))}else var f=new n({message:this.nls.warning,buttons:[{label:this.nls.ok,onClick:d.hitch(this,function(){f.close()})}]})},_verifiedOnShowClick:function(a){var b=this.displayFieldsTable.getRowData(a),c=parseInt(b.index,10),f=null,f=this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?this.config.layerInfos[c]:this._layerInfos[c],c=-1<this._unSpportQueryCampsite.layerNames.indexOf(f.name||
f.title);b.show&&c&&(new n({message:this.nls.unsupportQueryWarning}),b.show=!1,this.displayFieldsTable.editRow(a,b))},_getLayerFields:function(a){return this._layerInfos[a].getLayerObject().then(d.hitch(this,function(b){var c=this._allLayerFields[a];b=k.map(b.fields,function(a){return{name:a.name,alias:a.alias,show:!0}});m.merge(b,c,"name",function(a,b){d.mixin(a,b)});return b=m.syncOrderWith(b,c,"name")}))},openFieldsDialog:function(a,b,c){var f=this._createFieldsTable(b,c);this.currentFieldTable=
f;var g=new s({titleLabel:this.nls.configureLayerFields,width:640,maxHeight:600,autoHeight:!0,content:f,buttons:[{label:this.nls.ok,onClick:d.hitch(this,function(){this._allLayerFields[c]=f.getData();g.close();g=null})},{label:this.nls.cancel,classNames:["jimu-btn-vacation"],onClick:d.hitch(this,function(){g.close();g=null})}],onClose:function(){g=null}});f.startup()},_createFieldsTable:function(a){for(var b=null,c={fields:[{name:"show",title:this.nls.fieldVisibility,type:"checkbox","class":"show",
onChange:d.hitch(this,function(a){var c=b.getData();if(!k.some(c,d.hitch(this,function(a){return a.show}))&&(new n({message:this.nls.fieldCheckWarning}),c=b.getRowData(a)))c.show=!0,b.editRow(a,c)})},{name:"name",title:this.nls.fieldName,type:"text"},{name:"alias",title:this.nls.fieldAlias,editable:!0,type:"text"},{name:"actions",title:this.nls.fieldActions,type:"actions",actions:["up","down"],"class":"symbol"}],selectable:!0,autoHeight:!1,style:{height:"300px",maxHeight:"300px"}},b=new q(c),c=0;c<
a.length;c++)a[c].show=void 0===a[c].show?!0:!!a[c].show,b.addRow(a[c]);return b},setConfig:function(a){this.config=a;this.displayFieldsTable.clear();this._allLayerFields=[];this._processTableData().then(d.hitch(this,function(a){this._init(a);this.shelter.hide()}),d.hitch(this,function(a){new n({message:a.message||a})}))},onLayerInfosChanged:function(a,b,c){"added"!==b||(!c||!a)||c.getSupportTableInfo().then(d.hitch(this,function(a){a.isSupportedLayer&&(this._layerInfos&&0===this._layerInfos.length?
this._delayedLayerInfos.push(c):this._layerInfos&&(0<this._layerInfos.length&&!this._getLayerInfoById(c.id))&&(this._delayedLayerInfosAfterInit.push(c),this._processDelayedLayerInfosAfterInit(this._delayedLayerInfosAfterInit)))}))},_processDelayedLayerInfosAfterInit:function(a){for(var b=this._layerInfos.length,c=0;c<a.length;c++){var f=m.getConfigInfoFromLayerInfo(a[c]);this.displayFieldsTable.addRow({label:f.name||f.title,url:f.layer.url,index:""+(b+c),show:f.show});this._allLayerFields.push(f.layer.fields);
this._layerInfos.push(a[c])}},_processDelayedLayerInfos:function(){0<this._delayedLayerInfos.length&&(k.forEach(this._delayedLayerInfos,d.hitch(this,function(a){this._getLayerInfoById(a.id)||this._layerInfos.push(a)})),this._delayedLayerInfos=[])},_processTableData:function(){var a=new h;m.readConfigLayerInfosFromMap(this.map,!0,!0).then(d.hitch(this,function(b){this._layerInfos=b;this._processDelayedLayerInfos();m.readSupportTableInfoFromLayerInfos(this._layerInfos).then(d.hitch(this,function(c){this._tableInfos=
c;this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?(c=m.getConfigInfosFromLayerInfos(this._layerInfos),m.merge(c,this.config.layerInfos,"id",d.hitch(this,function(a,b){a.show=b.show;a.layer.url=b.layer.url;d.getObject("layer.fields.length",!1,a)&&d.getObject("layer.fields.length",!1,b)?(m.merge(a.layer.fields,b.layer.fields,"name",function(a,b){d.mixin(a,b)}),a.layer.fields=m.syncOrderWith(a.layer.fields,b.layer.fields,"name")):a.layer.fields=b.layer.fields})),this.config.layerInfos=
c,this._unSpportQueryCampsite.fromConfig=!0,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this.config.layerInfos),a.resolve(c)):(this._unSpportQueryCampsite.fromConfig=!1,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this._layerInfos),a.resolve(m.getConfigInfosFromLayerInfos(b)))}),function(b){console.error(b);a.reject(b)})}),d.hitch(this,function(b){console.error(b);a.reject(b)}));return a},_getUnsupportQueryLayerNames:function(a){var b=[];k.forEach(a,
d.hitch(this,function(a){var d=this._getSupportTableInfoById(a.id);d&&!d.isSupportQuery&&b.push(a.name||a.title)}));return b},_init:function(a){for(var e=[],c=0;c<a.length;c++){var d=a[c].show&&this._getSupportTableInfoById(a[c].id).isSupportQuery;this.displayFieldsTable.addRow({label:a[c].name||a[c].title,url:a[c].layer.url,index:""+c,show:d});this._allLayerFields.push(a[c].layer.fields);this._unSpportQueryCampsite.fromConfig&&(d=(d=this._unSpportQueryCampsite.layerNames)&&-1<d.indexOf(a[c].name||
a[c].title),a[c].show&&d&&e.push(a[c].name||a[c].title))}this._unSpportQueryCampsite.fromConfig&&0<e.length&&new n({message:this.nls.unsupportQueryLayers+"\x3cbr\x3e\x3cbr\x3e"+e.toString()});this.config.hideExportButton?this.exportcsv.uncheck():this.exportcsv.check();this.config.initiallyExpand?this.expand.check():this.expand.uncheck();this._canUseOpenAtStart()&&(this.openAtStart?this.expand.check():this.expand.uncheck(),this.expand.status=!1,b.addClass(this.expand.domNode,"disable-checkbox"));this.config.filterByMapExtent?
this.filterByMapExtent.check():this.filterByMapExtent.uncheck()},_canUseOpenAtStart:function(){return this.closeable||!this.isOnScreen},_getLayerInfoById:function(a){for(var b=0,c=this._layerInfos.length;b<c;b++)if(this._layerInfos[b].id===a)return this._layerInfos[b]},_getSupportTableInfoById:function(a){for(var b=0,c=this._tableInfos.length;b<c;b++)if(this._tableInfos[b].id===a)return this._tableInfos[b]},getConfig:function(){var a=this.displayFieldsTable.getData(),b=[],c=a.length;if(this.config&&
this.config.layerInfos&&0<this.config.layerInfos.length)k.forEach(a,d.hitch(this,function(c,d){var g=this.config.layerInfos[d],f={};f.name=g.name||g.title;f.id=g.id;f.layer={};f.layer.url=a[d].url;f.layer.fields=this._allLayerFields[d];f.show=a[d].show;b.push(f)}));else for(var f=0;f<c;f++){var g={};g.name=this._layerInfos[f].name||this._layerInfos[f].title;g.id=this._layerInfos[f].id;g.layer={};g.layer.url=a[f].url;g.layer.fields=this._allLayerFields[f];g.show=a[f].show;b.push(g)}this.config.layerInfos=
b;this.config.hideExportButton=!this.exportcsv.getValue();this.config.filterByMapExtent=this.filterByMapExtent.getValue();this._canUseOpenAtStart()||(this.config.initiallyExpand=this.expand.getValue());return this.config}})});