// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Lihavointi",copy:"Kopioi",cut:"Leikkaa","delete":"Poista",indent:"Sisenn\u00e4",insertHorizontalRule:"Vaakasuuntainen viiva",insertOrderedList:"Numeroitu luettelo",insertUnorderedList:"Numeroimaton luettelo",italic:"Kursivointi",justifyCenter:"Tasaus keskelle",justifyFull:"Tasaus",justifyLeft:"Tasaus vasemmalle",justifyRight:"Tasaus oikealle",outdent:"Ulonna",paste:"Liit\u00e4",redo:"Tee uudelleen",removeFormat:"Poista muotoilu",selectAll:"Valitse kaikki",
strikethrough:"Yliviivaus",subscript:"Alennettu",superscript:"Korotettu",underline:"Alleviivaus",undo:"Kumoa",unlink:"Poista linkki",createLink:"Luo linkki",toggleDir:"Vaihda suuntaa",insertImage:"Lis\u00e4\u00e4 kuva",insertTable:"Lis\u00e4\u00e4 taulukko/muokkaa taulukkoa",toggleTableBorder:"Ota taulukon kehys k\u00e4ytt\u00f6\u00f6n/poista kehys k\u00e4yt\u00f6st\u00e4",deleteTable:"Poista taulukko",tableProp:"Taulukon ominaisuudet",htmlToggle:"HTML-l\u00e4hde",foreColor:"Edustav\u00e4ri",hiliteColor:"Taustav\u00e4ri",
plainFormatBlock:"Kappaletyyli",formatBlock:"Kappaletyyli",fontSize:"Fonttikoko",fontName:"Fontin nimi",tabIndent:"Sarkainsisennys",fullScreen:"Vaihda koko n\u00e4ytt\u00f6",viewSource:"N\u00e4yt\u00e4 HTML-l\u00e4hde",print:"Tulosta",newPage:"Uusi sivu",systemShortcut:'Toiminto "${0}" on k\u00e4ytett\u00e4viss\u00e4 selaimessa vain n\u00e4pp\u00e4imist\u00f6n pikatoiminnolla. K\u00e4yt\u00e4 seuraavaa: ${1}.',ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a",
"days-standAlone-short":"su ma ti ke to pe la".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"nyt","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"viikonp\u00e4iv\u00e4","field-wed-relative+0":"t\u00e4n\u00e4 keskiviikkona","field-wed-relative+1":"ensi keskiviikkona","dateFormatItem-GyMMMEd":"E d. MMM y G","dateFormatItem-MMMEd":"ccc d. MMM",eraNarrow:["AH"],"field-tue-relative+-1":"viime tiistaina","days-format-short":"su ma ti ke to pe la".split(" "),
"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d. MMMM y G","field-fri-relative+-1":"viime perjantaina","field-wed-relative+-1":"viime keskiviikkona","months-format-wide":"muharram;safar;rabi\u2019 al-awwal;rabi\u2019 al-akhir;d\u017eumada-l-ula;d\u017eumada-l-akhira;rad\u017eab;\u0161a\u2019ban;ramadan;\u0161awwal;dhu-l-qa\u2019da;dhu-l-hidd\u017ea".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"ip.","dateFormat-full":"cccc d. MMMM y G",
"dateFormatItem-yyyyMEd":"E d.M.y G","field-thu-relative+-1":"viime torstaina","dateFormatItem-Md":"d.M.","dayPeriods-format-abbr-am":"ap.","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"aikakausi","months-standAlone-wide":"muharram;safar;rabi\u2019 al-awwal;rabi\u2019 al-akhir;d\u017eumada-l-ula;d\u017eumada-l-akhira;rad\u017eab;\u0161a\u2019ban;ramadan;\u0161awwal;dhu-l-qa\u2019da;dhu-l-hidd\u017ea".split(";"),"timeFormat-short":"H.mm","quarters-format-wide":["1. nelj\u00e4nnes",
"2. nelj\u00e4nnes","3. nelj\u00e4nnes","4. nelj\u00e4nnes"],"timeFormat-long":"H.mm.ss z","field-year":"vuosi","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"tunti","months-format-abbr":"muharram;safar;rabi\u2019 al-awwal;rabi\u2019 al-akhir;d\u017eumada-l-ula;d\u017eumada-l-akhira;rad\u017eab;\u0161a\u2019ban;ramadan;\u0161awwal;dhu-l-qa\u2019da;dhu-l-hidd\u017ea".split(";"),"field-sat-relative+0":"t\u00e4n\u00e4 lauantaina","field-sat-relative+1":"ensi lauantaina","timeFormat-full":"H.mm.ss zzzz",
"dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"t\u00e4n\u00e4\u00e4n","field-thu-relative+0":"t\u00e4n\u00e4 torstaina","field-day-relative+1":"huomenna","field-thu-relative+1":"ensi torstaina","dateFormatItem-GyMMMd":"d. MMM y G","dateFormatItem-H":"H","months-standAlone-abbr":"muharram;safar;rabi\u2019 al-awwal;rabi\u2019 al-akhir;d\u017eumada-l-ula;d\u017eumada-l-akhira;rad\u017eab;\u0161a\u2019ban;ramadan;\u0161awwal;dhu-l-qa\u2019da;dhu-l-hidd\u017ea".split(";"),"quarters-format-abbr":["1. nelj.",
"2. nelj.","3. nelj.","4. nelj."],"quarters-standAlone-wide":["1. nelj\u00e4nnes","2. nelj\u00e4nnes","3. nelj\u00e4nnes","4. nelj\u00e4nnes"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E d. MMM y G","dateFormatItem-M":"L","days-standAlone-wide":"sunnuntai maanantai tiistai keskiviikko torstai perjantai lauantai".split(" "),"dateFormatItem-yyyyMMM":"LLL y G","dateFormatItem-yyyyMMMd":"d. MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"H.mm.ss","field-sun-relative+0":"t\u00e4n\u00e4 sunnuntaina",
"dateFormatItem-Hm":"H.mm","field-sun-relative+1":"ensi sunnuntaina","quarters-standAlone-abbr":["1. nelj.","2. nelj.","3. nelj.","4. nelj."],eraAbbr:["AH"],"field-minute":"minuutti","field-dayperiod":"vuorokaudenaika","days-standAlone-abbr":"su ma ti ke to pe la".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm.ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"eilen","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"ap.","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d. MMM",
"dateFormatItem-MEd":"E d.M.","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"t\u00e4n\u00e4 perjantaina","field-fri-relative+1":"ensi perjantaina","field-day":"p\u00e4iv\u00e4","days-format-wide":"sunnuntaina maanantaina tiistaina keskiviikkona torstaina perjantaina lauantaina".split(" "),"field-zone":"aikavy\u00f6hyke","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"viime vuonna",
"field-month-relative+-1":"viime kuussa","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h.mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"ip.","days-format-abbr":"su ma ti ke to pe la".split(" "),eraNames:["AH"],"days-format-narrow":"SMTKTPL".split(""),"dateFormatItem-yyyyMd":"d.M.y G","field-month":"kuukausi","days-standAlone-narrow":"SMTKTPL".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"t\u00e4n\u00e4 tiistaina","field-tue-relative+1":"ensi tiistaina",
"dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"ap.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"t\u00e4n\u00e4 maanantaina","field-mon-relative+1":"ensi maanantaina","dateFormat-short":"d.M.y GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"sekunti","field-sat-relative+-1":"viime lauantaina",
"field-sun-relative+-1":"viime sunnuntaina","field-month-relative+0":"t\u00e4ss\u00e4 kuussa","field-month-relative+1":"ensi kuussa","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E d.","field-week":"viikko","dateFormat-medium":"d.M.y G","field-week-relative+-1":"viime viikolla","field-year-relative+0":"t\u00e4n\u00e4 vuonna","dateFormatItem-yyyyM":"L.y G","field-year-relative+1":"ensi vuonna","dayPeriods-format-narrow-pm":"ip.","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1} {0}",
"dateFormatItem-Hms":"H.mm.ss","dateFormatItem-hms":"h.mm.ss a","dateFormatItem-GyMMM":"LLL y G","field-mon-relative+-1":"viime maanantaina","dateFormatItem-yyyy":"y G","field-week-relative+0":"t\u00e4ll\u00e4 viikolla","field-week-relative+1":"ensi viikolla","field-day-relative+2":"ylihuomenna","field-day-relative+-2":"toissap\u00e4iv\u00e4n\u00e4",_localized:{}},"widgets/SituationAwareness/nls/strings":{_widgetLabel:"Tilannekuva",locate_incident:"Paikanna tapahtuma",clear_incidents:"Tyhjenn\u00e4 tapahtumat",
reverse_geocoded_address:"L\u00e4hin osoite",reverse_geocoded_error:"Ei k\u00e4ytett\u00e4viss\u00e4",miles:"Mailia",kilometers:"Kilometri\u00e4",feet:"Jalkaa",meters:"Metri\u00e4",yards:"Jaardia",nauticalMiles:"Meripeninkulmaa",now:"NYT",wind:"TUULI",SUN:"SU",MON:"MA",TUE:"TI",WED:"KE",THU:"TO",FRI:"PE",SAT:"LA",defaultTabMsg:"M\u00e4\u00e4rit\u00e4 tapausalue.",actionLabel:"M\u00e4\u00e4rit\u00e4 tapahtumaksi",drawPoint:"Piirr\u00e4 piste",drawLine:"Piirr\u00e4 viiva",drawPolygon:"Piirr\u00e4 polygoni",
saveIncident:"Tallenna tapaus",clearIncident:"Tyhjenn\u00e4 tapaus",useMapExtent:"K\u00e4yt\u00e4 nykyist\u00e4 kartan laajuutta",noFeaturesFound:"Kohteita ei l\u00f6ytynyt.",downloadCSV:"LATAA CSV-TIEDOSTO",editComplete:"Kohteen tallennus onnistui.",updateComplete:"Kohteen p\u00e4ivitys onnistui.",deleteComplete:"Kohteen poisto onnistui.",sum:"SUMMA",min:"V\u00c4HINT.",max:"ENINT.",avg:"KESKIARVO",count:"M\u00c4\u00c4R\u00c4",area:"ALUE",length:"PITUUS",notPolySave:"M\u00e4\u00e4rit\u00e4 puskurin et\u00e4isyys ennen tallennusta.",
update_btn:"Valmis",delete_btn:"Poista",get_directions:"Hae reittiohjeet",incident:"Tapahtuma",weather:"S\u00e4\u00e4",_localized:{}}});