// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/nls/strings":{_widgetLabel:"Kysely",executeQueryTip:"Suorita kysely napsauttamalla jotakin seuraavista teht\u00e4v\u00e4kohteista.",invalidConfig:"Virheellinen konfigurointi. Korjaa konfigurointi kyselyn asetussivulla.",queryParams:"Valinnat",parameters:"VALINNAT",queries:"KYSELYT",apply:"K\u00c4YT\u00c4",queryResults:"Tulokset",clear:"Tyhjenn\u00e4",noResults:"Kohdetta ei l\u00f6ytynyt.",queryError:"Kysely ep\u00e4onnistui !",numberFound:"L\u00f6ydettyjen kohteiden lukum\u00e4\u00e4r\u00e4",
mapExtentTip:"Rajoita tulokset nykyiselle kartta-alueelle.",noValue:"Ei arvoa",and:"ja",stringOperatorIs:"on",stringOperatorIsNot:"ei ole",stringOperatorStartsWith:"alkaa merkill\u00e4",stringOperatorEndsWith:"p\u00e4\u00e4ttyy merkkiin",stringOperatorContains:"sis\u00e4lt\u00e4\u00e4",stringOperatorDoesNotContain:"ei sis\u00e4ll\u00e4",stringOperatorIsBlank:"on tyhj\u00e4",stringOperatorIsNotBlank:"ei ole tyhj\u00e4",dateOperatorIsOn:"on p\u00e4\u00e4ll\u00e4",dateOperatorIsNotOn:"ei ole p\u00e4\u00e4ll\u00e4",
dateOperatorIsBefore:"on ennen",dateOperatorIsAfter:"on j\u00e4lkeen",dateOperatorDays:"p\u00e4iv\u00e4\u00e4",dateOperatorWeeks:"viikkoa",dateOperatorMonths:"kuukautta",dateOperatorInTheLast:"viimeisess\u00e4",dateOperatorNotInTheLast:"ei viimeisess\u00e4",dateOperatorIsBetween:"on v\u00e4lill\u00e4",dateOperatorIsNotBetween:"ei ole v\u00e4lill\u00e4",dateOperatorIsBlank:"on tyhj\u00e4",dateOperatorIsNotBlank:"ei ole tyhj\u00e4",numberOperatorIs:"on",numberOperatorIsNot:"ei ole",numberOperatorIsAtLeast:"on v\u00e4hint\u00e4\u00e4n",
numberOperatorIsLessThan:"on v\u00e4hemm\u00e4n kuin",numberOperatorIsAtMost:"on enint\u00e4\u00e4n",numberOperatorIsGreaterThan:"on suurempi kuin",numberOperatorIsBetween:"on v\u00e4lill\u00e4",numberOperatorIsNotBetween:"ei ole v\u00e4lill\u00e4",numberOperatorIsBlank:"on tyhj\u00e4",numberOperatorIsNotBlank:"ei ole tyhj\u00e4",operationalLayerTip:"Lis\u00e4\u00e4 tulos toiminnalliseksi karttatasoksi",queryResult:"Kyselytulos",specifyParamsTip:"M\u00e4\u00e4rit\u00e4 teht\u00e4v\u00e4n parametrit",
useSpatialFilter:"Rajoita kohteita k\u00e4ytt\u00e4m\u00e4ll\u00e4 sijaintisuodatinta",useCurrentMapExtent:"Vain nykyisen kartta-alueen kanssa leikkaavat kohteet",drawGraphicOnMap:"Vain k\u00e4ytt\u00e4j\u00e4n m\u00e4\u00e4ritt\u00e4m\u00e4n alueeseen kanssa leikkaavat kohteet",specifySpatialFilterMsg:"M\u00e4\u00e4rit\u00e4 teht\u00e4v\u00e4n sijaintisuodatin.",clearResults:"Tyhjenn\u00e4 tulokset",operationalTip:"Kun t\u00e4m\u00e4 vaihtoehto on valittuna, tulokset n\u00e4kyv\u00e4t kartassa, kunnes painiketta ${clearResults} napsautetaan.",
noneQueryTip:"T\u00e4lle pienoisohjelmalle ei ole m\u00e4\u00e4ritetty kyselyteht\u00e4v\u00e4\u00e4.",noPermissionsMsg:"Sinulla ei ole palvelun k\u00e4ytt\u00f6oikeutta.",attributesFromRelationship:"Liittyv\u00e4n taulun ominaisuustiedot",tasks:"Teht\u00e4v\u00e4t",applySpatialFilterToLimitResults:"Rajoita tuloksia k\u00e4ytt\u00e4m\u00e4ll\u00e4 sijaintisuodatinta",useCurrentExtentTip:"Osittain tai kokonaan nykyisess\u00e4 karttalaajuudessa",useDrawGraphicTip:"Osittain tai kokonaan karttaan piirretyn muodon sis\u00e4ll\u00e4",
useFeaturesTip:"Niiden sijaintien perusteella suhteessa toisen karttatason kohteisiin",noSpatialLimitTip:"\u00c4l\u00e4 rajoita tuloksia sijaintitietojen mukaan",applySearchDistance:"K\u00e4yt\u00e4 hakuet\u00e4isyytt\u00e4",spatialRelationship:"Sijaintisuhde",relatedLayer:"Liittyv\u00e4 karttataso",bufferDistance:"Puskurin et\u00e4isyys",miles:"Mailia",kilometers:"Kilometri\u00e4",feet:"Jalkaa",meters:"Metri\u00e4",yards:"Jaardia",nauticalMiles:"Meripeninkulmaa",back:"Takaisin",execute:"Suorita",
_localized:{}}});