// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Mylios",acronym:"myl."},kilometers:{displayText:"Kilometrai",acronym:"km"},feet:{displayText:"P\u0117dos",acronym:"p\u0117dos"},meters:{displayText:"Metrai",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Paie\u0161kos nuostatos",defaultBufferDistanceLabel:"Nustatyti numatyt\u0105j\u0105 buferio atstumo reik\u0161m\u0119",maxBufferDistanceLabel:"Nustatyti maksimali\u0105 element\u0173 paie\u0161kos buferio atstumo reik\u0161m\u0119",
bufferDistanceUnitLabel:"Buferio atstumo vienetai",defaultBufferHintLabel:"Patarimas: naudokite numatyt\u0105jai buferio reik\u0161mei nustatyti",maxBufferHintLabel:"Patarimas: naudokite maksimaliai buferio reik\u0161mei nustatyti",bufferUnitLabel:"Patarimas: nustatykite buferio k\u016brimo vienet\u0105",selectGraphicLocationSymbol:"Adreso arba vietos simbolis",graphicLocationSymbolHintText:"Patarimas: ie\u0161koto adreso arba spustel\u0117tos vietos simbolis",fontColorLabel:"Pasirinkti paie\u0161kos rezultat\u0173 \u0161rifto spalv\u0105",
fontColorHintText:"Patarimas: paie\u0161kos rezultat\u0173 \u0161rifto spalva"},layerSelector:{selectLayerLabel:"Pasirinkti paie\u0161kos sluoksn\u012f (-ius)",layerSelectionHint:"Patarimas: sluoksniui (-iams) pasirinkti naudokite nustatymo mygtuk\u0105",addLayerButton:"Grup\u0117",okButton:"Gerai",cancelButton:"At\u0161aukti"},routeSetting:{routeSettingTabTitle:"Krypties nustatymai",routeServiceUrl:"Mar\u0161ruto paslauga",travelModeServiceUrl:"Kelion\u0117s re\u017eimo paslauga",buttonSet:"Grup\u0117",
routeServiceUrlHintText:"Patarimas: spustel\u0117kite \u201eNustatyti\u201c, jei norite nar\u0161yti ir pasirinkti mar\u0161ruto paslaug\u0105",directionLengthUnit:"Krypties ilgio vienetai",unitsForRouteHintText:"Patarimas: naudojama mar\u0161ruto vienetams rodyti",selectRouteSymbol:"Pasirinkti mar\u0161ruto rodymo simbol\u012f",routeSymbolHintText:"Patarimas: naudojamas mar\u0161ruto linijos simboliui rodyti",travelModeServiceUrlHintText:"Patarimas: spustel\u0117kite \u201eNustatyti\u201c, jei norite nar\u0161yti ir pasirinkti kelion\u0117s re\u017eimo paslaug\u0105",
invalidTravelmodeServiceUrl:"Nurodykite galiojan\u010di\u0105 kelion\u0117s re\u017eimo paslaug\u0105 ",routingDisabledMsg:"Jei norite \u012fjungti nuorodas, \u012fsitikinkite, kad mar\u0161rutas \u012fjungtas ArcGIS Online elemente."},networkServiceChooser:{arcgislabel:"Prid\u0117ti i\u0161 ArcGIS Online",serviceURLabel:"Prid\u0117ti paslaugos URL",routeURL:"Mar\u0161ruto URL",validateRouteURL:"Tikrinti",exampleText:"Pavyzdys",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",
hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",okButton:"Gerai",cancelButton:"At\u0161aukti",nextButton:"Kitas",backButton:"Atgal",invalidRouteServiceURL:"Nurodykite galiojan\u010di\u0105 mar\u0161ruto paslaug\u0105."},errorStrings:{bufferErrorString:"\u012eveskite leistin\u0105 skaitin\u0119 reik\u0161m\u0119.",selectLayerErrorString:"Pasirinkite ie\u0161kos sluoksn\u012f (-ius)",invalidDefaultValue:"Numatytasis buferio atstumas negali b\u016bti tu\u0161\u010dias. Nurodykite buferio atstum\u0105",
invalidMaximumValue:"Maksimalus buferio atstumas negali b\u016bti tu\u0161\u010dias. Nurodykite buferio atstum\u0105",defaultValueLessThanMax:"Nurodykite numatyt\u0105j\u012f buferio atstum\u0105 maksimaliose ribose",defaultBufferValueGreaterThanZero:"Nurodykite numatyt\u0105j\u012f buferio atstum\u0105 didesn\u012f u\u017e 0",maximumBufferValueGreaterThanZero:"Nurodykite maksimal\u0173 buferio atstum\u0105 didesn\u012f u\u017e 0"},symbolPickerPreviewText:"Per\u017ei\u016bra:",_localized:{}}});