// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/setting/nls/strings":{queries:"P\u00e4ringu\u00fclesanded",addNew:"Lisa uus",queryLayer:"P\u00e4ringukiht",setSource:"M\u00e4\u00e4ra",setDataSource:"M\u00e4\u00e4ra andmeallikas",name:"Nimi",querySource:"Andmeallikas",queryName:"\u00dclesande nimi",queryDefinition:"Filtri m\u00e4\u00e4ratlus",resultsSetting:"Tulemuste seade",symbolSetting:"S\u00fcmboli seade",resultSettingTip:"Saate m\u00e4\u00e4rata, kuidas tulemused kuvatakse ja mida need h\u00f5lmavad.",resultItemTitle:"Tulemuse pealkiri",
resultItemContent:"Tulemuse sisu",fieldsSetTip:"Kontrollige kuvatavaid v\u00e4lju. V\u00e4ljade j\u00e4rjestuse muutmiseks, v\u00e4lja vormindamiseks v\u00f5i aliase v\u00e4rskendamiseks valige v\u00e4li.",addField:"Lisa v\u00e4li",visibility:"N\u00e4htavus",alias:"Alias",specialType:"Erit\u00fc\u00fcp",actions:"Tegevused",none:"Pole",link:"Link",image:"Pilt",noField:"V\u00e4li puudub",operationalLayerTip:"Lisa tulemus t\u00f6\u00f6kihina",setLayerSymbolTip:"M\u00e4\u00e4rake p\u00e4ringu tulemuste s\u00fcmbol: ",
setSelectedSymbolTip:"M\u00e4\u00e4rake valitud objekti s\u00fcmbol.",notUseFilter:"\u00c4ra kasuta filtrit",setSourceTip:"M\u00e4\u00e4rake p\u00e4ringu allikas.",setFilterTip:"M\u00e4\u00e4rake filter \u00f5igesti.",ok:"OK",cancel:"T\u00fchista",noFilterTip:"M\u00e4\u00e4ratlemata filtriavaldiseta loendab see p\u00e4ringu\u00fclesanne k\u00f5ik m\u00e4\u00e4ratud andmeallika funktsioonid.",relationships:"Seosed",addRelationshipLayer:"Lisa uus seos",relatedTo:"Seotud",selectOption:"Valige...",resultItemSorting:"Tulemuse \u00fcksuste sortimine",
field:"V\u00e4li",sortingOrder:"J\u00e4rjekord",configureFieldsTip:"Palun konfigureerige v\u00e4ljad, mille j\u00e4rgi p\u00e4ringutulemusi sorditakse.",setSortingFields:"M\u00e4\u00e4ra sortimisv\u00e4ljad",ascending:"Kahanev",descending:"Kahanev",sortBy:"Sorteeri:",thenBy:"Seej\u00e4rel",addTask:"Lisa toiming",noTasksTip:"Toiminguid pole, alustamiseks kl\u00f5psake k\u00e4sku ${addTask}!",infoText:"Teave",filters:"Filtrid",results:"Tulemused",optionsText:"Seaded",summaryText:"Kokkuv\u00f5te",attributeFilter:"Atribuudifilter",
attributeFilterTip:"M\u00e4\u00e4ratlege atribuudiavaldised, mida kasutatakse vidinas p\u00e4ringukihi filtreerimiseks.",noExpressionDefinedTip:"\u00dchtki avaldist pole m\u00e4\u00e4ratletud.",needInputValuesTip:"K\u00e4itusaja k\u00e4igus tuleb sisestada v\u00e4\u00e4rtused",setExpressions:"M\u00e4\u00e4ra avaldised",spatialFilter:"Ruumifilter",spatialFilterTip:"Valige vidinas tulemuste piiramiseks ruumiline filter (filtrid).",defaultOption:"Vaikimisi",useCurrentExtentTip:"Osaliselt v\u00f5i t\u00e4ielikult praeguses kaardi kuvaulatuses",
useDrawGraphicTip:"Osaliselt v\u00f5i t\u00e4ielikult kaardile joonistatud kujundis",useFeaturesTip:"Vastavalt nende asukohale teise kihi objektide suhtes",noSpatialLimitTip:"\u00c4ra piira tulemusi ruumiliselt",drawingTools:"Joonistamise t\u00f6\u00f6vahendid",bufferSettings:"Puhvri seaded",defaultDistance:"Vaike-vahemaa",bufferDistance:"Puhvri ulatus",defaultUnit:"Vaike\u00fchik",miles:"Miilid",kilometers:"Kilomeetrid",feet:"Jalad",meters:"Meetrid",yards:"Jardid",nauticalMiles:"Meremiilid",availableSpatialRelationships:"Saadaolevad ruumilised seosed",
setSpatialRelationships:"M\u00e4\u00e4ra ruumilised seosed",availability:"Saadavus",relationship:"Seos",label:"M\u00e4rgis",intersect:"l\u00f5ikuvad",contain:"sisaldavad",areContainedIn:"sisalduvad",cross:"rist",envelopeIntersect:"l\u00f5ikuvad \u00fcmbrisega",overlap:"\u00fclekattes",areOverlapped:"kaetakse",touche:"puutuvad kokku",within:"vahemikus",areWithin:"on vahemikus",indexIntersect:"l\u00f5ikuvad indeksiga",itemTitle:"\u00dcksuse pealkiri",displayFields:"Kuvamise v\u00e4ljad",sortingFields:"Sortimise v\u00e4ljad",
setDisplayFields:"M\u00e4\u00e4ra kuvamise v\u00e4ljad",symbol:"S\u00fcmbol",setSymbol:"M\u00e4\u00e4ra s\u00fcmbol",serviceSymbolTip:"Kasuta kihi kaudu m\u00e4\u00e4ratud s\u00fcmboleid",exportTip:"Kuva eksportimise nuppu",keepResultsTip:"S\u00e4ilita tulemused kaardil p\u00e4rast vidina sulgemist",queryRelatedRecords:"Seotud kirjete p\u00e4ring",createLayerForTaskTip:"M\u00e4\u00e4rake, kuidas toiming loob kihte",oneLayerForTaskTip:"Loo selle toimingu jaoks ainult \u00fcks kiht",multipleLayerForTaskTip:"Loo uus kiht iga kord, kui see toiming k\u00e4ivitub",
_localized:{}}});