// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/setting/nls/strings":{queries:"Abfrage-Tasks",addNew:"Neu hinzuf\u00fcgen",queryLayer:"Abfrage-Layer",setSource:"Festlegen",setDataSource:"Datenquelle festlegen",name:"Name",querySource:"Datenquelle",queryName:"Task-Name",queryDefinition:"Filterdefinition",resultsSetting:"Ergebniseinstellung",symbolSetting:"Symboleinstellung",resultSettingTip:"Definieren Sie, welche Ausgabeergebnisse und wie sie angezeigt werden sollen.",resultItemTitle:"Titel des Ergebniselements",resultItemContent:"Inhalt des Ergebniselements",
fieldsSetTip:"Aktivieren Sie die Felder, die angezeigt werden sollen. W\u00e4hlen Sie ein Feld aus, um dessen Alias zu aktualisieren, es zu sortieren und zu formatieren.",addField:"Feld hinzuf\u00fcgen",visibility:"Sichtbarkeit",alias:"Alias",specialType:"Besonderer Typ",actions:"Aktionen",none:"Keine",link:"Link",image:"Bild",noField:"Kein Feld",operationalLayerTip:"Ergebnis als operationalen Layer hinzuf\u00fcgen",setLayerSymbolTip:"Legen Sie das Symbol f\u00fcr die Abfrageergebnisse fest: ",setSelectedSymbolTip:"Legen Sie das Symbol des ausgew\u00e4hlten Features fest.",
notUseFilter:"Keinen Filter verwenden",setSourceTip:"Legen Sie die Abfragequelle fest.",setFilterTip:"Legen Sie den Filter ordnungsgem\u00e4\u00df fest.",ok:"OK",cancel:"Abbrechen",noFilterTip:"Dieser Abfrage-Task listet alle Features in der angegebenen Datenquelle ohne definierten Filterausdruck auf.",relationships:"Beziehungen",addRelationshipLayer:"Neue Beziehung hinzuf\u00fcgen",relatedTo:"In Beziehung mit",selectOption:"W\u00e4hlen Sie..",resultItemSorting:"Sortierung von Ergebniselementen",
field:"Feld",sortingOrder:"Reihenfolge",configureFieldsTip:"Konfigurieren Sie die Felder, nach denen das Abfrageergebnis sortiert wird.",setSortingFields:"Sortierfelder festlegen",ascending:"Aufsteigend",descending:"Absteigend",sortBy:"Sortieren nach",thenBy:"Dann nach",addTask:"Task hinzuf\u00fcgen",noTasksTip:'Keine Tasks; klicken Sie auf "${addTask}", um zu starten!',infoText:"Info",filters:"Filter",results:"Ergebnisse",optionsText:"Optionen",summaryText:"Zusammenfassung",attributeFilter:"Attributfilter",
attributeFilterTip:"Definieren Sie Attributausdr\u00fccke f\u00fcr die Verwendung in Widgets, um den Abfrage-Layer zu filtern.",noExpressionDefinedTip:"Es wurde kein Ausdruck definiert.",needInputValuesTip:"W\u00e4hrend der Laufzeit m\u00fcssen Werte eingegeben werden",setExpressions:"Ausdr\u00fccke festlegen",spatialFilter:"R\u00e4umlicher Filter",spatialFilterTip:"W\u00e4hlen Sie den/die r\u00e4umlichen Filter zum Begrenzen der Ergebnisse in Widgets aus.",defaultOption:"Standard",useCurrentExtentTip:"Teilweise oder vollst\u00e4ndig innerhalb der aktuellen Kartenausdehnung",
useDrawGraphicTip:"Teilweise oder vollst\u00e4ndig innerhalb des auf der Karte dargestellten Shapes",useFeaturesTip:"Basierend auf deren Positionen relativ zu Features in einem anderen Layer",noSpatialLimitTip:"Ergebnisse nicht r\u00e4umlich beschr\u00e4nken",drawingTools:"Zeichenwerkzeuge",bufferSettings:"Puffer-Einstellungen",defaultDistance:"Standardentfernung",bufferDistance:"Pufferabstand",defaultUnit:"Standardeinheit",miles:"Meilen",kilometers:"Kilometer",feet:"Fu\u00df",meters:"Meter",yards:"Yard",
nauticalMiles:"Seemeilen",availableSpatialRelationships:"Verf\u00fcgbare r\u00e4umliche Beziehungen",setSpatialRelationships:"R\u00e4umliche Beziehungen festlegen",availability:"Verf\u00fcgbarkeit",relationship:"Beziehung",label:"Beschriftung",intersect:"\u00fcberschneiden",contain:"contain",areContainedIn:"sind enthalten in",cross:"Kreuz",envelopeIntersect:"Envelope-\u00dcberschneidung",overlap:"\u00dcberlappung",areOverlapped:"werden \u00fcberlappt",touche:"ber\u00fchren",within:"Innerhalb",areWithin:"enthalten sind in",
indexIntersect:"Index-\u00dcberschneidung",itemTitle:"Elementtitel",displayFields:"Anzeigefelder",sortingFields:"Sortierfelder",setDisplayFields:"Anzeigefelder festlegen",symbol:"Symbol",setSymbol:"Symbol festlegen",serviceSymbolTip:"Vom Layer definierte Symbole verwenden",exportTip:'Die Schaltfl\u00e4che "Exportieren" anzeigen',keepResultsTip:"Ergebnisse auf der Karte beibehalten, nachdem das Widget geschlossen wurde",queryRelatedRecords:"Zugeh\u00f6rige Datens\u00e4tze abfragen",createLayerForTaskTip:"Festlegen, wie der Task Layer erstellt",
oneLayerForTaskTip:"Nur einen Layer f\u00fcr diesen Task erstellen",multipleLayerForTaskTip:"Bei jeder Ausf\u00fchrung dieses Tasks einen neuen Layer erstellen",_localized:{}}});