// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Chart/setting/nls/strings":{chartTasks:"Tarefas de Gr\u00e1ficos",addNew:"Adicionar Nova",addNewTip:"Adicionar uma Nova Tarefa de Gr\u00e1fico",name:"Nome",set:"Definir",setDataSource:"Definir Fonte dos Dados",generalSettingsTip:"Definir a fonte dos dados, t\u00edtulo e descri\u00e7\u00e3o para os gr\u00e1ficos.",chartModeSettingTip:"Selecione uma forma de analisar e exibir dados como gr\u00e1ficos.",detailsSettingTip:"Definir a apar\u00eancia do gr\u00e1fico especificando tipo e cor, e os valores a incluir no gr\u00e1fico.",
symbolSettingTip:"Definir a exibi\u00e7\u00e3o do mapa para dados em gr\u00e1fico.",addFilterTip:"Adicionar Filtro a estes dados",dataSource:"Fonte da Dados",noResults:"Nenhum resultado",chartTitle:"T\u00edtulo do Gr\u00e1fico",description:"Descri\u00e7\u00e3o",chartingMode:"Exibi\u00e7\u00e3o do Gr\u00e1fico",featureOption:"Exibir elemento a elemento",categoryOption:"Exibir valores por categoria",countOption:"Exibir contagens de elementos por categoria",fieldOption:"Exibir valores de atributos como gr\u00e1ficos",
category:"Categoria",axisLabel:"R\u00f3tulo de Categoria",categoryField:"Campo de Categoria",operation:"Opera\u00e7\u00e3o",originalOption:"Utilizar valores originais",sumOption:"Soma",averageOption:"M\u00e9dia",minOption:"M\u00ednimo",maxOption:"M\u00e1ximo",valueFields:"Campos de Valores",moveUp:"Mover para cima",moveDown:"Mover para baixo",sortOrder:"Ordenar Gr\u00e1ficos atrav\u00e9s de R\u00f3tulos de Categorias",ascending:"Ascendente",descending:"Descendente",chartType:"Tipo de Gr\u00e1fico",
column:"Gr\u00e1fico de Colunas",bar:"Gr\u00e1fico de Barras",line:"Gr\u00e1fico de Linhas",pie:"Gr\u00e1fico Circular",chartColor:"Cor do Gr\u00e1fico",showDataLabels:"Exibir R\u00f3tulos de Dados",setSymbol:"S\u00edmbolo de Sele\u00e7\u00e3o",setHighLightColor:"Real\u00e7ar Cor",settings:"Defini\u00e7\u00f5es",mapInterationOptions:"Op\u00e7\u00f5es de Intera\u00e7\u00e3o do Mapa",preview:"Pr\u00e9-Visualizar",ok:"OK",cancel:"Cancelar",close:"Fechar",setFilterTip:"Por favor, defina o filtro corretamente. ",
setChartTitleTip:"Por favor, defina o t\u00edtulo do gr\u00e1fico.",setChartTypeTip:"Por favor, selecione pelo menos um tipo de gr\u00e1fico.",setDataFieldTip:"por favor, selecione pelo menos um campo de valor.",setOutputFieldTip:"por favor, defina campos de sa\u00edda.",count:"Contagem",label:"R\u00f3tulo",horizontalAxis:"Eixo Horizontal",verticalAxis:"Eixo Vertical",dataLabels:"R\u00f3tulos de Dados",color:"Cor",colorful:"Colorido",monochromatic:"Monocrom\u00e1tico",noTaskTip:"Clique em Adicionar Novo para adicionar uma tarefa de gr\u00e1fico",
info:"Informa\u00e7\u00e3o",charts:"Gr\u00e1ficos",options:"Op\u00e7\u00f5es",taskName:"Nome da Tarefa",summary:"Resumo",resultDescription:"Descri\u00e7\u00e3o de Resultado",spatialFilterTip:"Escolha o(s) filtro(s) espacial(ais) utilizados no widget para limitar os resultados.",defaultOption:"Padr\u00e3o",useCurrentExtentTip:"Parcialmente ou totalmente no contido na atual extens\u00e3o de mapa",useDrawGraphicTip:"Parcialmente ou totalmente no contido na forma desenhada no mapa",useFeaturesTip:"Baseado nas respetivas localiza\u00e7\u00f5es em rela\u00e7\u00e3o a elementos noutra camada",
noSpatialLimitTip:"N\u00e3o limita resultados espacialmente",drawingTools:"Ferramentas de desenho",bufferSettings:"Defini\u00e7\u00f5es de Buffer",defaultDistance:"Dist\u00e2ncia Padr\u00e3o",bufferDistance:"Dist\u00e2ncia do Buffer",defaultUnit:"Unidade Padr\u00e3o",miles:"Milhas",kilometers:"Quil\u00f4metros",feet:"P\u00e9s",meters:"Metros",yards:"Jardas",nauticalMiles:"Milhas N\u00e1uticas",availableSpatialRelationships:"Rela\u00e7\u00f5es Espaciais Dispon\u00edveis",setSpatialRelationships:"Definir Rela\u00e7\u00f5es Espaciais",
availability:"Disponibilidade",relationship:"Relacionamento",actions:"Ac\u00e7\u00f5es",intersect:"intersetar",contain:"conter",areContainedIn:"est\u00e3o contidos em",cross:"cruz",envelopeIntersect:"interse\u00e7\u00e3o envelope",overlap:"sobrepor",areOverlapped:"est\u00e3o sobrepostos",touche:"touche",within:"contidos",areWithin:"est\u00e3o contidos",indexIntersect:"interse\u00e7\u00e3o \u00edndice",_localized:{}}});