// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Chart/setting/nls/strings":{chartTasks:"Sarcini pentru diagrame",addNew:"Ad\u0103ugare nou",addNewTip:"Ad\u0103ugare sarcin\u0103 nou\u0103 pentru diagrame",name:"Nume",set:"Setare",setDataSource:"Setare surs\u0103 de date",generalSettingsTip:"Seta\u0163i sursa de date, titlul \u015fi descrierea pentru diagrame.",chartModeSettingTip:"Selecta\u0163i un mod de analiza \u015fi afi\u015fa date drept diagrame.",detailsSettingTip:"Seta\u0163i aspectul diagramelor specific\u00e2nd tipurile \u015fi culorile \u015fi ce valori s\u0103 fie incluse \u00een ele:",
symbolSettingTip:"Seta\u0163i afi\u015farea pe hart\u0103 a datelor din diagram\u0103.",addFilterTip:"Ad\u0103ugare filtru la aceste date",dataSource:"Surs\u0103 date",noResults:"Nu a fost g\u0103sit niciun obiect spa\u0163ial.",chartTitle:"Titlu diagram\u0103",description:"Descriere",chartingMode:"Afi\u015fare diagram\u0103",featureOption:"Afi\u015fare valori pentru fiecare obiecte spa\u0163ial",categoryOption:"Afi\u015fare valori pe categorii",countOption:"Afi\u015fare num\u0103r de obiecte spa\u0163iale pe categorii",
fieldOption:"Afi\u015fare valori de atribute sub form\u0103 de diagram\u0103",category:"Categorie",axisLabel:"Etichet\u0103 categorie",categoryField:"C\u00e2mp categorie",operation:"Opera\u0163ie",originalOption:"Utilizare valori originale",sumOption:"Sum\u0103",averageOption:"Medie",minOption:"Minim",maxOption:"Maxim",valueFields:"C\u00e2mpuri pentru valori",moveUp:"Deplasare \u00een sus",moveDown:"Deplasare \u00een jos",sortOrder:"Sortare ordine diagrame pe baza etichetelor de categorii",ascending:"Ascendent",
descending:"Descendent",chartType:"Tip diagram\u0103",column:"Diagram\u0103 cu coloane",bar:"Diagram\u0103 cu bare",line:"Diagram\u0103 liniar\u0103",pie:"Diagram\u0103 circular\u0103",chartColor:"Culoare diagram\u0103",showDataLabels:"Afi\u015fare etichete pentru date",setSymbol:"Simbol pentru selectare",setHighLightColor:"Culoare de eviden\u0163iere",settings:"Set\u0103ri",mapInterationOptions:"Op\u0163iuni pentru interac\u0163iunea cu harta",preview:"Previzualizare",ok:"OK",cancel:"Anulare",close:"\u00cenchidere",
setFilterTip:"Seta\u0163i filtrul corect. ",setChartTitleTip:"Seta\u0163i titlul diagramei.",setChartTypeTip:"Selecta\u0163i cel pu\u0163in un tip de diagram\u0103.",setDataFieldTip:"Selecta\u0163i cel pu\u0163in un c\u00e2mp de valori.",setOutputFieldTip:"Seta\u0163i c\u00e2mpuri de ie\u015fire.",count:"Num\u0103r",label:"Etichet\u0103",horizontalAxis:"Ax\u0103 orizontal\u0103",verticalAxis:"Ax\u0103 vertical\u0103",dataLabels:"Etichete date",color:"Culoare",colorful:"Color",monochromatic:"Monocrom",
noTaskTip:"Face\u0163i clic pe Ad\u0103ugare nou pentru a ad\u0103uga o activitate pentru diagrame",info:"Informa\u0163ii",charts:"Diagrame",options:"Op\u0163iuni",taskName:"Nume opera\u0163ie",summary:"Rezumat",resultDescription:"Descriere rezultat",spatialFilterTip:"Alege\u0163i filtrele spa\u0163iale utilizate \u00een widget pentru limitarea rezultatelor.",defaultOption:"Implicit",useCurrentExtentTip:"Par\u0163ial sau complet \u00een cadrul extinderii curente de hart\u0103",useDrawGraphicTip:"Par\u0163ial sau complet \u00een cadrul formei trasate pe hart\u0103",
useFeaturesTip:"\u00cen baza loca\u0163iilor, \u00een raport cu obiectele spa\u0163iale din alt strat tematic",noSpatialLimitTip:"Nu limita\u0163i spa\u0163ial rezultatele",drawingTools:"Instrumente de trasare",bufferSettings:"Set\u0103ri buffer",defaultDistance:"Distan\u0163\u0103 implicit\u0103",bufferDistance:"Distan\u0163\u0103 buffer",defaultUnit:"Unitate implicit\u0103",miles:"Mile",kilometers:"Kilometri",feet:"Ft",meters:"Metri",yards:"Iarzi",nauticalMiles:"Mile marine",availableSpatialRelationships:"Rela\u0163ie spa\u0163ial\u0103 disponibil\u0103",
setSpatialRelationships:"Setare rela\u0163ie spa\u0163ial\u0103",availability:"Disponibilitate",relationship:"Rela\u0163ie",actions:"Ac\u0163iuni",intersect:"intersectare",contain:"con\u0163ine",areContainedIn:"sunt con\u0163inute de",cross:"cruce",envelopeIntersect:"intersectare plic",overlap:"suprapunere",areOverlapped:"sunt suprapuse",touche:"atins",within:"\u00een",areWithin:"sunt la",indexIntersect:"intersectare index",_localized:{}}});