// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Chart/setting/nls/strings":{chartTasks:"Diagramopgaver",addNew:"Tilf\u00f8j ny",addNewTip:"Tilf\u00f8j en ny diagramopgave",name:"Navn",set:"Indstil",setDataSource:"Angiv datakilde",generalSettingsTip:"Angiv datakilde, titel og beskrivelse til diagrammet.",chartModeSettingTip:"V\u00e6lg en m\u00e5de at analysere og vise data p\u00e5 som diagrammer.",detailsSettingTip:"Indstil diagrammets udseende ved at angive dets typer og farve, samt hvilke v\u00e6rdier der skal afbildes:",symbolSettingTip:"Angiv kortvisningen for afbildede data.",
addFilterTip:"F\u00f8j et filter til disse data",dataSource:"Datakilde",noResults:"Ingen resultater fundet.",chartTitle:"Diagramtitel",description:"Beskrivelse",chartingMode:"Diagramvisning",featureOption:"Vis v\u00e6rdier objekt for objekt",categoryOption:"Vis v\u00e6rdier efter kategori",countOption:"Vis objektantal efter kategori",fieldOption:"Vis attributv\u00e6rdier som diagrammer",category:"Kategori",axisLabel:"Kategorietiket",categoryField:"Kategorifelt",operation:"Handling",originalOption:"Brug originalv\u00e6rdier",
sumOption:"Sum",averageOption:"Gennemsnitlig",minOption:"Minimum",maxOption:"Maksimum",valueFields:"V\u00e6rdifelter",moveUp:"Flyt op",moveDown:"Flyt ned",sortOrder:"Sort\u00e9r diagrambestilling via kategorietiketter",ascending:"Stigende",descending:"Faldende",chartType:"Diagramtype",column:"Kolonnediagram",bar:"S\u00f8jlediagram",line:"Linjediagram",pie:"Cirkeldiagram",chartColor:"Diagramfarve",showDataLabels:"Vis dataetiketter",setSymbol:"Markeringssymbol",setHighLightColor:"Fremh\u00e6v farve",
settings:"Indstillinger",mapInterationOptions:"Indstillinger for interaktion med kortet",preview:"Forh\u00e5ndsvisning",ok:"OK",cancel:"Annuller",close:"Luk",setFilterTip:"Angiv filteret korrekt. ",setChartTitleTip:"Angiv diagrammets titel.",setChartTypeTip:"V\u00e6lg mindst \u00e9n diagramtype.",setDataFieldTip:"V\u00e6lg mindst \u00e9t v\u00e6rdifelt.",setOutputFieldTip:"Angiv outputfelter.",count:"T\u00e6lling",label:"M\u00e6rke",horizontalAxis:"Horisontal akse",verticalAxis:"Vertikal akse",dataLabels:"Dataetiketter",
color:"Farve",colorful:"Farverig",monochromatic:"Monokrom",noTaskTip:"Klik p\u00e5 Tilf\u00f8j ny for at tilf\u00f8je en diagramopgave",info:"Info",charts:"Diagrammer",options:"Indstillinger",taskName:"Navn p\u00e5 opgave",summary:"Summary",resultDescription:"Resultatbeskrivelse",spatialFilterTip:"V\u00e6lg det/de spatiale filtre, der anvendes i widget'en til at begr\u00e6nse resultater.",defaultOption:"Standard",useCurrentExtentTip:"Delvist eller helt inden for den aktuelle kortudstr\u00e6kning",
useDrawGraphicTip:"Delvist eller helt inden for den form, der et tegnet p\u00e5 kortet",useFeaturesTip:"Baseret p\u00e5 deres positioner i forhold til objekterne i et andet lag",noSpatialLimitTip:"Begr\u00e6ns ikke resultaterne spatialt",drawingTools:"Tegnev\u00e6rkt\u00f8jer",bufferSettings:"Bufferindstillinger",defaultDistance:"Standardafstand",bufferDistance:"Bufferafstand",defaultUnit:"Standardenhed",miles:"Miles",kilometers:"Kilometer",feet:"Fod",meters:"Meter",yards:"Yards",nauticalMiles:"S\u00f8mil",
availableSpatialRelationships:"Tilg\u00e6ngelige spatiale relationer",setSpatialRelationships:"Angiv spatiale relationer",availability:"Tilg\u00e6ngelighed",relationship:"Relation",actions:"Handlinger",intersect:"gennemsk\u00e6rer",contain:"indeholder",areContainedIn:"er indeholdt i",cross:"kors",envelopeIntersect:"indkredset gennemsk\u00e6ring",overlap:"overlapper",areOverlapped:"er overlappet",touche:"ber\u00f8rer",within:"inden for",areWithin:"er inden for",indexIntersect:"indeksgennemsk\u00e6ring",
_localized:{}}});