// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Miili",acronym:"mi"},kilometers:{displayText:"Kilomeetrit",acronym:"m"},feet:{displayText:"Jalga",acronym:"jl"},meters:{displayText:"Meetrit",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Otsingu seaded",defaultBufferDistanceLabel:"M\u00e4\u00e4ra puhvri\u00a0ulatuse vaikev\u00e4\u00e4rtus",maxBufferDistanceLabel:"M\u00e4\u00e4ra puhvri ulatuse maksimumv\u00e4\u00e4rtus\u00a0objektide otsimiseks",bufferDistanceUnitLabel:"Puhvri ulatuse \u00fchikud",
defaultBufferHintLabel:"Vihje: kasutage puhvri vaikev\u00e4\u00e4rtuse m\u00e4\u00e4ramiseks",maxBufferHintLabel:"Vihje: kasutage puhvri maksimumv\u00e4\u00e4rtuse m\u00e4\u00e4ramiseks",bufferUnitLabel:"Vihje: m\u00e4\u00e4ratlege puhvri loomise \u00fchik",selectGraphicLocationSymbol:"Aadressi v\u00f5i asukoha s\u00fcmbol",graphicLocationSymbolHintText:"Vihje: otsitud aadressi v\u00f5i kl\u00f5psatud asukoha s\u00fcmbol",fontColorLabel:"Vali otsingutulemuste fondi v\u00e4rv",fontColorHintText:"Vihje: otsingutulemuste fondi v\u00e4rv"},
layerSelector:{selectLayerLabel:"Vali otsingukiht (-kihid)",layerSelectionHint:"Vihje: kasutage kihi (kihtide) valimiseks nuppu M\u00e4\u00e4ra",addLayerButton:"M\u00e4\u00e4ra",okButton:"OK",cancelButton:"T\u00fchista"},routeSetting:{routeSettingTabTitle:"Teejuhiste seaded",routeServiceUrl:"Marsruutimisteenus",travelModeServiceUrl:"S\u00f5idure\u017eiimi teenus",buttonSet:"M\u00e4\u00e4ra",routeServiceUrlHintText:"Vihje:\u00a0marsruutimisteenuse sirvimiseks ja valimiseks kl\u00f5psake nuppu\u00a0\u2018M\u00e4\u00e4ra\u2019",
directionLengthUnit:"Teejuhise pikkus\u00fchikud",unitsForRouteHintText:"Vihje: kasutatakse marsruudi \u00fchikute kuvamiseks",selectRouteSymbol:"Vali marsruudi kuvamiseks s\u00fcmbol",routeSymbolHintText:"Vihje: kasutatakse marsruudi joons\u00fcmboli kuvamiseks",travelModeServiceUrlHintText:"Vihje:\u00a0s\u00f5idure\u017eiimi teenuse sirvimiseks ja valimiseks kl\u00f5psake nuppu \u2018M\u00e4\u00e4ra\u2019",invalidTravelmodeServiceUrl:"M\u00e4\u00e4rake sobiv s\u00f5idure\u017eiimi teenus ",routingDisabledMsg:"Enne teejuhiste lubamist\u00a0veenduge, et marsruutimine on\u00a0ArcGIS Online'i \u00fcksuses lubatud."},
networkServiceChooser:{arcgislabel:"Lisa ArcGIS Online\u2019ist",serviceURLabel:"Lisa teenuse URL",routeURL:"Marsruudi URL",validateRouteURL:"Valideeri",exampleText:"N\u00e4ide",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",okButton:"OK",cancelButton:"T\u00fchista",nextButton:"Edasi",backButton:"Tagasi",invalidRouteServiceURL:"M\u00e4\u00e4rake sobiv marsruuditeenus."},
errorStrings:{bufferErrorString:"Sisestage sobiv numbriline v\u00e4\u00e4rtus.",selectLayerErrorString:"Valige otsingukiht (-kihid).",invalidDefaultValue:"Puhvri vaikeulatuse v\u00e4li ei tohi olla t\u00fchi. M\u00e4\u00e4rake puhvri ulatus",invalidMaximumValue:"Puhvri maksimumulatuse v\u00e4li ei tohi olla t\u00fchi. M\u00e4\u00e4rake puhvri ulatus",defaultValueLessThanMax:"M\u00e4\u00e4rake puhvri vaikeulatus limiidi piires",defaultBufferValueGreaterThanZero:"M\u00e4\u00e4rake puhvri vaikeulatus, mis on suurem kui 0",
maximumBufferValueGreaterThanZero:"M\u00e4\u00e4rake puhvri maksimumulatus, mis on suurem kui 0"},symbolPickerPreviewText:"Eelvaade:",_localized:{}}});