// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Miles",acronym:"mi"},kilometers:{displayText:"Kilometer",acronym:"km"},feet:{displayText:"Fod",acronym:"fod"},meters:{displayText:"Meter",acronym:"m"}},searchSetting:{searchSettingTabTitle:"S\u00f8geindstillinger",defaultBufferDistanceLabel:"Angiv v\u00e6rdi for standardbufferafstand",maxBufferDistanceLabel:"Angiv v\u00e6rdi for maksimal bufferafstand for s\u00f8gning efter objekter",bufferDistanceUnitLabel:"Bufferafstandsenheder",
defaultBufferHintLabel:"Tip: Bruges til at angive standardv\u00e6rdi for en buffer",maxBufferHintLabel:"Tip: Bruges til at angive maksimumv\u00e6rdi for en buffer",bufferUnitLabel:"Tip: Defin\u00e9r enhed for oprettelse af en buffer",selectGraphicLocationSymbol:"Adresse- eller positionssymbol",graphicLocationSymbolHintText:"Tip: Symbol for s\u00f8gt adresse eller klikket position",fontColorLabel:"V\u00e6lg skrifttypefarve for s\u00f8geresultater",fontColorHintText:"Tip: Skrifttypefarve for s\u00f8geresultater"},
layerSelector:{selectLayerLabel:"V\u00e6lg s\u00f8gelag",layerSelectionHint:"Tip: Brug indstillingsknappen til at v\u00e6lge lag(ene)",addLayerButton:"Indstil",okButton:"\x26quot;.prvs\x26quot; er en ugyldig fil til en enkeltbrugerautorisation.",cancelButton:"Annuller"},routeSetting:{routeSettingTabTitle:"Indstillinger for k\u00f8rselsvejledning",routeServiceUrl:"Rutetjeneste",travelModeServiceUrl:"Rejsetjeneste",buttonSet:"Indstil",routeServiceUrlHintText:"Tip: Klik p\u00e5 \u2018Indstil\u2019 for at g\u00e5 til og v\u00e6lge en rutetjeneste",
directionLengthUnit:"L\u00e6ngdeenheder for k\u00f8rselsvejledning",unitsForRouteHintText:"Tip: Bruges til at vise enheder for ruten",selectRouteSymbol:"V\u00e6lg symbol for visning af rute",routeSymbolHintText:"Tip: Brug visningslinjesymbolet for ruten",travelModeServiceUrlHintText:"Tip: Klik p\u00e5 \u2018Indstil\u2019 for at g\u00e5 til og v\u00e6lge en rejsetjeneste",invalidTravelmodeServiceUrl:"Angiv en gyldig rejsetjeneste. ",routingDisabledMsg:"For at aktivere k\u00f8rselsvejledninger skal du s\u00f8rge for, at ruteplanl\u00e6gning er aktiveret i ArcGIS Online-elementet."},
networkServiceChooser:{arcgislabel:"Tilf\u00f8j fra ArcGIS Online",serviceURLabel:"Tilf\u00f8j tjeneste-URL",routeURL:"Rute-URL",validateRouteURL:"Bekr\u00e6ft",exampleText:"Eksempel",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",okButton:"\x26quot;.prvs\x26quot; er en ugyldig fil til en enkeltbrugerautorisation.",cancelButton:"Annuller",nextButton:"N\u00e6ste",backButton:"Tilbage",
invalidRouteServiceURL:"Angiv en gyldig rutetjeneste."},errorStrings:{bufferErrorString:"Angiv en gyldig numerisk v\u00e6rdi.",selectLayerErrorString:"V\u00e6lg de lag, der skal s\u00f8ges i.",invalidDefaultValue:"Standardbufferafstand kan ikke v\u00e6re tom. Angiv bufferafstanden",invalidMaximumValue:"Maksimumbufferafstand kan ikke v\u00e6re tom. Angiv bufferafstanden",defaultValueLessThanMax:"Angiv standardbufferafstand inden for maksimumgr\u00e6nsen",defaultBufferValueGreaterThanZero:"Angiv en standardbufferafstand, der er st\u00f8rre end 0",
maximumBufferValueGreaterThanZero:"Angiv en maksimumbufferafstand, der er st\u00f8rre end 0"},symbolPickerPreviewText:"Forh\u00e5ndsvisning:",_localized:{}}});