// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Pary\u0161kintasis",copy:"Kopijuoti",cut:"Kirpti","delete":"Pa\u0161alinti",indent:"\u012etrauka",insertHorizontalRule:"Horizontali linija",insertOrderedList:"Sunumeruotas s\u0105ra\u0161as",insertUnorderedList:"S\u0105ra\u0161as su \u017eenkleliais",italic:"Pasvirasis",justifyCenter:"Lygiuoti centre",justifyFull:"Abipus\u0117 lygiuot\u0117",justifyLeft:"Lygiuoti kair\u0117je",justifyRight:"Lygiuoti de\u0161in\u0117je",outdent:"Atvirk\u0161tin\u0117 \u012ftrauka",
paste:"\u012eklijuoti",redo:"Gr\u0105\u017einti",removeFormat:"Pa\u0161alinti formatavim\u0105",selectAll:"\u017dym\u0117ti visk\u0105",strikethrough:"Perbrauktasis",subscript:"Apatinis indeksas",superscript:"Vir\u0161utinis indeksas",underline:"Pabrauktasis",undo:"At\u0161aukti",unlink:"Pa\u0161alinti nuorod\u0105",createLink:"Kurti nuorod\u0105",toggleDir:"Perjungti krypt\u012f",insertImage:"\u012eterpti vaizd\u0105",insertTable:"\u012eterpti / redaguoti vaizd\u0105",toggleTableBorder:"Perjungti lentel\u0117s kra\u0161tin\u0119",
deleteTable:"Pa\u0161alinti lentel\u0119",tableProp:"Lentel\u0117s savyb\u0117",htmlToggle:"HTML \u0161altinis",foreColor:"Priekinio plano spalva",hiliteColor:"Fono spalva",plainFormatBlock:"Pastraipos stilius",formatBlock:"Pastraipos stilius",fontSize:"\u0160rifto dydis",fontName:"\u0160rifto pavadinimas",tabIndent:"Tabuliacijos \u012ftrauka",fullScreen:"Perjungti vis\u0105 ekran\u0105",viewSource:"Per\u017ei\u016br\u0117ti HTML \u0161altin\u012f",print:"Spausdinti",newPage:"Naujas puslapis",systemShortcut:'"${0}" veiksm\u0105 galima atlikti nar\u0161ykl\u0117je tik naudojant spart\u0173j\u012f klavi\u0161\u0105. Naudokite ${1}.',
ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"dabar","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Savait\u0117s diena","field-wed-relative+0":"\u0161is tre\u010diadienis","field-wed-relative+1":"kitas tre\u010diadienis","dateFormatItem-GyMMMEd":"G y MMM d, E",
"dateFormatItem-MMMEd":"MMM d, E",eraNarrow:["AH"],"field-tue-relative+-1":"paskutinis antradienis","days-format-short":"Sk Pr An Tr Kt Pn \u0160t".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"G y 'm'. MMMM d 'd'.","field-fri-relative+-1":"paskutinis penktadienis","field-wed-relative+-1":"paskutinis tre\u010diadienis","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"dateFormatItem-yyyyQQQ":"G y QQQ","dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"G y 'm'. MMMM d 'd'., EEEE","dateFormatItem-yyyyMEd":"y-MM-dd G, E","field-thu-relative+-1":"paskutinis ketvirtadienis","dateFormatItem-Md":"MM-d","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"timeFormat-short":"hh:mm a","quarters-format-wide":["1-as ketvirtis","2-as ketvirtis","3-ias ketvirtis","4-as ketvirtis"],"timeFormat-long":"HH:mm:ss z","field-year":"Metai","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Valanda","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"\u0161is \u0161e\u0161tadienis","field-sat-relative+1":"kitas \u0161e\u0161tadienis","timeFormat-full":"HH:mm:ss zzzz",
"dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"\u0161iandien","field-thu-relative+0":"\u0161is ketvirtadienis","field-day-relative+1":"rytoj","field-thu-relative+1":"kitas ketvirtadienis","dateFormatItem-GyMMMd":"G y MMM d","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["Q1","Q2","Q3","Q4"],"dateFormatItem-Gy":"G y",
"dateFormatItem-yyyyMMMEd":"G y MMM d, E","dateFormatItem-M":"L","days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"y MMM d G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"hh:mm:ss a","field-sun-relative+0":"\u0161is sekmadienis","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"kitas sekmadienis","quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],eraAbbr:["AH"],"field-minute":"Minut\u0117","field-dayperiod":"iki piet\u0173 / po piet\u0173",
"days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"vakar","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"MM-dd, E","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"\u0161is penktadienis","field-fri-relative+1":"kitas penktadienis","field-day":"Diena","days-format-wide":"Sekmadienis Pirmadienis Antradienis Tre\u010diadienis Ketvirtadienis Penktadienis \u0160e\u0161tadienis".split(" "),
"field-zone":"Laiko juosta","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"G y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"pra\u0117j\u0119 metai","field-month-relative+-1":"pra\u0117j\u0119s m\u0117nuo","dateTimeFormats-appendItem-Year":"{0} {1}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),eraNames:["AH"],
"days-format-narrow":"SMTWTFS".split(""),"dateFormatItem-yyyyMd":"GGGGG y-MM-dd","field-month":"M\u0117nuo","days-standAlone-narrow":"SMTWTFS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"\u0161is antradienis","field-tue-relative+1":"kitas antradienis","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"\u0161is pirmadienis",
"field-mon-relative+1":"kitas pirmadienis","dateFormat-short":"GGGGG y-MM-dd","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Sekund\u0117","field-sat-relative+-1":"paskutinis \u0161e\u0161tadienis","field-sun-relative+-1":"paskutinis sekmadienis","field-month-relative+0":"\u0161is m\u0117nuo","field-month-relative+1":"kitas m\u0117nuo","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E, d","field-week":"Savait\u0117",
"dateFormat-medium":"G y MMM d","field-week-relative+-1":"pra\u0117jusi savait\u0117","field-year-relative+0":"\u0161ie metai","dateFormatItem-yyyyM":"GGGGG y-MM","field-year-relative+1":"kiti metai","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"G y MMM","field-mon-relative+-1":"paskutinis pirmadienis","dateFormatItem-yyyy":"G y","field-week-relative+0":"\u0161i savait\u0117",
"field-week-relative+1":"kita savait\u0117",_localized:{}},"widgets/BatchAttributeEditor/nls/strings":{_widgetLabel:"Atribut\u0173 paketo rengykl\u0117",widgetIntroSelectByArea:"Naudodami toliau pateikiamus \u012frankius kurkite pasirinktus element\u0173 rinkinius, kad atnaujintum\u0117te.  Jeigu eilut\u0117 \x3cfont class\x3d'maxRecordInIntro'\x3ei\u0161ry\u0161kinama\x3c/font\x3e, vir\u0161yta maksimali \u012fra\u0161\u0173 riba.",widgetIntroSelectByFeature:"Naudokite toliau pateikiam\u0105 \u012frank\u012f, kad pasirinktum\u0117te element\u0105 i\u0161 \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e sluoksnio.  \u0160i funkcija bus naudojama pasirinkti ir atnaujinti visus susikertan\u010dius elementus.  Jeigu eilut\u0117 \x3cfont class\x3d'maxRecordInIntro'\x3ei\u0161ry\u0161kinama\x3c/font\x3e, vir\u0161yta maksimali \u012fra\u0161\u0173 riba.",
widgetIntroSelectByFeatureQuery:"Naudokite toliau pateikiam\u0105 \u012frank\u012f i\u0161 \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e .  \u0160io elemento \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e atributas bus naudojamas vykdyti toliau pateikiam\u0173 sluoksni\u0173 u\u017eklausas ir atnaujinti gautus elementus.  Jeigu eilut\u0117 \x3cfont class\x3d'maxRecordInIntro'\x3ei\u0161ry\u0161kinama\x3c/font\x3e, vir\u0161yta maksimali \u012fra\u0161\u0173 riba.",widgetIntroSelectByQuery:"\u012eveskite reik\u0161m\u0119, kad sukurtum\u0117te pasirinkim\u0173 rinkin\u012f.  Jeigu eilut\u0117 \x3cfont class\x3d'maxRecordInIntro'\x3ei\u0161ry\u0161kinama\x3c/font\x3e, vir\u0161yta maksimali \u012fra\u0161\u0173 riba.",
layerTable:{colLabel:"Sluoksnio pavadinimas",numSelected:"#",colSyncStatus:""},noConfiguredLayers:"Sukonfig\u016bruot\u0173 redaguojam\u0173 sluoksni\u0173 n\u0117ra",editorPopupTitle:"Atribut\u0173 paketo rengykl\u0117",editorPopupSaveBtn:"\u012era\u0161yti",editorPopupMultipleValues:"",clear:"Valyti",featuresUpdated:"${0} / ${1} elementas (-\u0173) atnaujintas",featuresSelected:"${0} elementas (-\u0173) pasirinktas",featuresSkipped:"Apeita",search:"Ie\u0161koti",queryInput:"\u012eveskite reik\u0161m\u0119 \u012f u\u017eklaus\u0105",
noFilterTip:"Nenusta\u010dius filtro s\u0105lygos, \u0161i u\u017eklausos u\u017eduotis nurodys visus nurodyto duomen\u0173 \u0161altinio elementus.",setFilterTip:"Nustatykite filtr\u0105 tinkamai.",filterPopup:"Filtruoti sluoksn\u012f",cancel:"At\u0161aukti",ok:"Gerai",drawBox:{point:"Ky\u0161ulys",line:"Linija",polyline:"Linija",freehandPolyline:"Laisvai pie\u0161iama linija",extent:"Apr\u0117ptis",polygon:"Plotas",freehandPolygon:"Laisvai pie\u0161iamas poligonas",clear:"Valyti",addPointToolTip:"Spustel\u0117kite, kad pasirinktum\u0117te \u0161ioje vietov\u0117je",
addShapeToolTip:"Nubr\u0117\u017ekite fig\u016br\u0105, kad pasirinktum\u0117te elementus",freehandToolTip:"Paspauskite ir laikykite, kad nubr\u0117\u017etum\u0117te fig\u016br\u0105 ir pasirinktum\u0117te elementus",startToolTip:"Nubr\u0117\u017ekite fig\u016br\u0105, kad pasirinktum\u0117te elementus"},errors:{layerNotFound:"Sluoksnis ${0} su ID ${1} \u017eem\u0117lapyje nerastas, gali b\u016bti, kad po valdikli\u0173 konfig\u016bracijos \u017eem\u0117lapis pasikeit\u0117",queryNullID:"Elementas i\u0161 ${0} pateik\u0117 netinkam\u0105 ID",
noSelectedLayers:"N\u0117ra naujinam\u0173 sluoksni\u0173 su \u012fra\u0161ais",inputValueError:"Netinkama reik\u0161m\u0117 formoje"},_localized:{}}});