// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/setting/nls/strings":{queries:"Foresp\u00f8rgselsopgaver",addNew:"Tilf\u00f8j ny",queryLayer:"Foresp\u00f8rgselslag",setSource:"Indstil",setDataSource:"Angiv datakilde",name:"Navn",querySource:"Datakilde",queryName:"Navn p\u00e5 opgave",queryDefinition:"Filterdefinition",resultsSetting:"Indstilling for resultat",symbolSetting:"Indstilling for symbol",resultSettingTip:"Angiv, hvad og hvordan output-resultaterne skal vise.",resultItemTitle:"Resultatobjektets titel",resultItemContent:"Resultatobjektets indhold",
fieldsSetTip:"Mark\u00e9r de felter, der skal vises. Mark\u00e9r et felt for at opdatere dets alias, sortere og formatere.",addField:"Tilf\u00f8j felt",visibility:"Synlighed",alias:"Alias",specialType:"Speciel type",actions:"Handlinger",none:"Ingen",link:"Link",image:"Billede",noField:"Intet felt",operationalLayerTip:"Tilf\u00f8j resultat som operationelt lag",setLayerSymbolTip:"Angiv symbolet for foresp\u00f8rgselsresultater: ",setSelectedSymbolTip:"Angiv symbolet for markeret objekt.",notUseFilter:"Brug ikke filter",
setSourceTip:"Angiv foresp\u00f8rgselskilde.",setFilterTip:"Angiv filteret korrekt.",ok:"OK",cancel:"Annuller",noFilterTip:"Defineres der ikke et filterudtryk, viser denne foresp\u00f8rgsel alle objekter i den angivne datakilde.",relationships:"Relationer",addRelationshipLayer:"Tilf\u00f8j ny relation",relatedTo:"Relateret til",selectOption:"V\u00e6lg venligst...",resultItemSorting:"Sortering af resultatelement",field:"Mark",sortingOrder:"R\u00e6kkef\u00f8lge",configureFieldsTip:"Konfigur\u00e9r de felter, som foresp\u00f8rgselsresultatet skal sorteres efter.",
setSortingFields:"Indstil sorteringsfelter",ascending:"Stigende",descending:"Faldende",sortBy:"Sort\u00e9r efter",thenBy:"Dern\u00e6st efter",addTask:"Tilf\u00f8j opgave",noTasksTip:'Ingen opgaver, klik p\u00e5 "${addTask}" for at starte!',infoText:"Info",filters:"Filtre",results:"Resultater",optionsText:"Indstillinger",summaryText:"Oversigt",attributeFilter:"Attributfilter",attributeFilterTip:"Defin\u00e9r attributudtryk til brug i widget'en for at filtrere foresp\u00f8rgselslaget.",noExpressionDefinedTip:"Der blev ikke defineret noget udtryk.",
needInputValuesTip:"Der skal inds\u00e6ttes v\u00e6rdier ved runtime",setExpressions:"Angiv udtryk",spatialFilter:"Spatialt filter",spatialFilterTip:"V\u00e6lg det/de spatiale filtre, der anvendes i widget'en til at begr\u00e6nse resultater.",defaultOption:"Standard",useCurrentExtentTip:"Delvist eller helt inden for den aktuelle kortudstr\u00e6kning",useDrawGraphicTip:"Delvist eller helt inden for den form, der et tegnet p\u00e5 kortet",useFeaturesTip:"Baseret p\u00e5 deres positioner i forhold til objekterne i et andet lag",
noSpatialLimitTip:"Begr\u00e6ns ikke resultaterne spatialt",drawingTools:"Tegnev\u00e6rkt\u00f8jer",bufferSettings:"Bufferindstillinger",defaultDistance:"Standardafstand",bufferDistance:"Bufferafstand",defaultUnit:"Standardenhed",miles:"Miles",kilometers:"Kilometer",feet:"Fod",meters:"Meter",yards:"Yards",nauticalMiles:"S\u00f8mil",availableSpatialRelationships:"Tilg\u00e6ngelige spatiale relationer",setSpatialRelationships:"Angiv spatiale relationer",availability:"Tilg\u00e6ngelighed",relationship:"Relation",
label:"M\u00e6rke",intersect:"gennemsk\u00e6rer",contain:"indeholder",areContainedIn:"er indeholdt i",cross:"kors",envelopeIntersect:"indkredset gennemsk\u00e6ring",overlap:"overlapper",areOverlapped:"er overlappet",touche:"ber\u00f8rer",within:"inden for",areWithin:"er inden for",indexIntersect:"indeksgennemsk\u00e6ring",itemTitle:"Elementtitel",displayFields:"Visningsfelter",sortingFields:"Sorterer felter",setDisplayFields:"Angiv visningsfelter",symbol:"Symbol",setSymbol:"Angiv symbol",serviceSymbolTip:"Brug de symboler, der er defineret af laget",
exportTip:"Vis eksport-knap",keepResultsTip:"Behold resultater p\u00e5 kortet, n\u00e5r widget'en lukkes",queryRelatedRecords:"Foresp\u00f8rg p\u00e5 relaterede poster",createLayerForTaskTip:"Angiv, hvordan opgaven skal oprette lag",oneLayerForTaskTip:"Opret kun \u00e9t lag for denne opgave",multipleLayerForTaskTip:"Opret et nyt lag, hver gang denne opgave udf\u00f8res",_localized:{}}});