// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/setting/nls/strings":{queries:"Tarefas de Consulta",addNew:"Adicionar Novo",queryLayer:"Camada de Consulta",setSource:"Configurar",setDataSource:"Configurar Fonte de Dados",name:"Nome",querySource:"Fonte de Dados",queryName:"Nome da Tarefa",queryDefinition:"Defini\u00e7\u00e3o de Filtro",resultsSetting:"Configura\u00e7\u00e3o dos Resultados",symbolSetting:"Configura\u00e7\u00e3o do S\u00edmbolo",resultSettingTip:"Define quais e como exibir os resultados de sa\u00edda.",resultItemTitle:"T\u00edtulo do Item Resultante",
resultItemContent:"Conte\u00fados do Item Resultante",fieldsSetTip:"Verifique os campos que voc\u00ea deseja exibir. Selecione um campo para atualizar seu nome alternativo, ordem e formato.",addField:"Adicionar Campo",visibility:"Visibilidade",alias:"Nome Alternativo",specialType:"Tipo Especial",actions:"A\u00e7\u00f5es",none:"Nenhum",link:"Link",image:"Imagem",noField:"Nenhum campo",operationalLayerTip:"Adicionar resultado como camada operacional",setLayerSymbolTip:"Configure o s\u00edmbolo para resultados da consulta: ",
setSelectedSymbolTip:"Configurar s\u00edmbolo da fei\u00e7\u00e3o selecionada.",notUseFilter:"N\u00e3o utilizar filtro",setSourceTip:"Configure a origem da consulta.",setFilterTip:"Configure o filtro corretamente.",ok:"Ok",cancel:"Cancelar",noFilterTip:"Sem express\u00e3o de filtro definida, esta tarefa de consulta listar\u00e1 todas as fei\u00e7\u00f5es na fonte de dados especificada.",relationships:"Relacionamentos",addRelationshipLayer:"Adicionar Novo Relacionamento",relatedTo:"Relacionado Para",
selectOption:"Selecione..",resultItemSorting:"Classifica\u00e7\u00e3o de Item do Resultado",field:"Campo",sortingOrder:"Ordenar",configureFieldsTip:"Configure os campos que o resultado da consulta ser\u00e1 classificado.",setSortingFields:"Configurar Campos de Classifica\u00e7\u00e3o",ascending:"Crescente",descending:"Descendente",sortBy:"Classificar por",thenBy:"Ent\u00e3o por",addTask:"Adicionar tarefa",noTasksTip:'Nenhuma tarefa, clique em "${addTask}" para iniciar!',infoText:"Info",filters:"Filtros",
results:"Resultados",optionsText:"Op\u00e7\u00f5es",summaryText:"Resumo",attributeFilter:"Filtro de Atributo",attributeFilterTip:"Defina express\u00f5es de atributo para utilizar no widget para filtrar a camada de consulta.",noExpressionDefinedTip:"Nenhuma express\u00e3o foi definida.",needInputValuesTip:"Necess\u00e1rio valores de entrada no tempo de execu\u00e7\u00e3o",setExpressions:"Configurar Express\u00f5es",spatialFilter:"Filtro Espacial",spatialFilterTip:"Escolha o filtro espacial utilizado no widget para limitar resultados.",
defaultOption:"Padr\u00e3o",useCurrentExtentTip:"Parcialmente ou completamente dentro da extens\u00e3o de mapa atual",useDrawGraphicTip:"Parcialmente ou completamente dentro da forma desenhada no mapa",useFeaturesTip:"Baseado em suas localiza\u00e7\u00f5es em rela\u00e7\u00e3o \u00e0s fei\u00e7\u00f5es em outra camada",noSpatialLimitTip:"N\u00e3o limitar espacialmente os resultados",drawingTools:"Ferramentas de desenho",bufferSettings:"Configura\u00e7\u00f5es do Buffer",defaultDistance:"Dist\u00e2ncia Padr\u00e3o",
bufferDistance:"Dist\u00e2ncia do Buffer",defaultUnit:"Unidade Padr\u00e3o",miles:"Milhas",kilometers:"Quil\u00f4metros",feet:"P\u00e9s",meters:"Metros",yards:"Jardas",nauticalMiles:"Milhas N\u00e1uticas",availableSpatialRelationships:"Relacionamentos Espaciais Dispon\u00edveis",setSpatialRelationships:"Configurar Relacionamentos Espaciais",availability:"Disponibilidade",relationship:"Relacionamento",label:"R\u00f3tulo",intersect:"interseccionar",contain:"cont\u00e9m",areContainedIn:"est\u00e3o contidos em",
cross:"cruz",envelopeIntersect:"intersec\u00e7\u00e3o de envelope",overlap:"sobreposi\u00e7\u00e3o",areOverlapped:"est\u00e3o sobrepostos",touche:"toca",within:"dentro",areWithin:"est\u00e3o dentro",indexIntersect:"intersec\u00e7\u00e3o de \u00edndice",itemTitle:"T\u00edtulo do Item",displayFields:"Campos de Visualiza\u00e7\u00e3o",sortingFields:"Campos de Classifica\u00e7\u00e3o",setDisplayFields:"Configurar Campos de Visualiza\u00e7\u00e3o",symbol:"S\u00edmbolo",setSymbol:"Configurar s\u00edmbolo",
serviceSymbolTip:"Utilizar s\u00edmbolos definidos pela camada",exportTip:"Mostrar bot\u00e3o Exportar",keepResultsTip:"Manter resultados no mapa ap\u00f3s o widget ser fechado",queryRelatedRecords:"Consultar registros relacionados",createLayerForTaskTip:"Especificar como a tarefa cria camadas",oneLayerForTaskTip:"Somente criar uma camada desta tarefa",multipleLayerForTaskTip:"Criar uma nova camada toda vez que esta tarefa executar",_localized:{}}});