// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/dom-class dojo/dom-construct dojo/dom-style dojo/on esri/geometry/geometryEngine esri/graphic esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query jimu/CSVUtils jimu/utils".split(" "),function(B,l,x,q,C,g,m,D,u,E,y,F,z,A,G,H,I,J,K){return B("ProximityInfo",null,{constructor:function(c,b,a){this.tab=c;this.container=
b;this.parent=a;this.graphicsLayer=this.incident=null;this.specialFields={};this.dateFields={};this.config=a.config},updateForIncident:function(c,b,a){q.forEach(this.tab.tabLayers,l.hitch(this,function(d){if("undefined"!==typeof d.empty){var f=new F(d.url);u(f,"load",l.hitch(this,function(){this.tab.tabLayers=[f];this.processIncident(c,b,a)}))}else this.processIncident(c,b,a)}))},processIncident:function(c,b,a){this.container.innerHTML="";this.buffer=b;g.add(this.container,"loading");var d=[];this.incident=
c;this.graphicsLayer=a;var f=this.tab.tabLayers;a=[];for(var k=0;k<f.length;k++){var h=f[k],e=new I;e.returnGeometry=!0;e.geometry=b.geometry;e.outFields="true"===this.parent.config.csvAllFields||!0===this.parent.config.csvAllFields?["*"]:this._getFields(h);"undefined"!==typeof h.queryFeatures&&a.push(h.queryFeatures(e))}(new C(a)).then(l.hitch(this,function(a){for(var b=0;b<a.length;b++){var e=a[b][1],k=this._getFields(f[b]);if(e)for(var e=e.features,h=0;h<e.length;h++){for(var g=e[h],l=this._getDistance(c.geometry,
g.geometry),m={DISTANCE:l},v=0;v<k.length;v++)m[k[v]]=g.attributes[k[v]];!0===this.config.csvAllFields||"true"===this.config.csvAllFields?g.attributes.DISTANCE=l:g.attributes=m;d.push(g)}}this._processResults(d)}))},_processResults:function(c){this.container.innerHTML="";g.remove(this.container,"loading");this.graphicsLayer.clear();0===c.length&&this.buffer?this.container.innerHTML=this.parent.nls.noFeaturesFound:0===c.length&&!this.buffer&&(this.container.innerHTML=this.parent.nls.defaultTabMsg);
c.sort(this._compareDistance);var b=m.create("div",{id:"SA_tpc",style:"width:"+220*(c.length+1)+"px;"},this.container);g.add(b,"SAT_tabPanelContent");var a=m.create("div",{},b);g.add(a,"SATcol");a=m.create("div",{innerHTML:this.parent.nls.downloadCSV},a);g.add(a,"btnExport");u(a,"click",l.hitch(this,this._exportToCSV,c));var a=this.parent.nls[this.parent.config.distanceUnits],d;"undefined"!==typeof this.tab.advStat?d=this.tab.advStat.stats.outFields:(d=[],0<this.parent.map.itemInfo.itemData.operationalLayers.length&&
q.forEach(this.parent.map.itemInfo.itemData.operationalLayers,l.hitch(this,function(a){a.title===this.tab.layers&&("undefined"!==typeof a.popupInfo?q.forEach(a.popupInfo.fieldInfos,l.hitch(this,function(a){if(a.visible){var b={value:0};b.expression=a.fieldName;b.label=a.label;d.push(b)}})):q.forEach(a.layerObject.fields,l.hitch(this,function(a){var b={value:0};b.expression=a.name;b.label=a.alias;d.push(b)})))})));for(var f=0;f<c.length;f++){var k=f+1,h=c[f],e=h.geometry,r=e;"point"!==e.type&&(r=e.getExtent().getCenter());
var h=h.attributes,w;"point"===this.incident.geometry.type&&(w=a+": "+Math.round(100*h.DISTANCE)/100);var e="",n=0,s;for(s in h)if("DISTANCE"!==s&&3>n&&"undefined"!==typeof d)for(var p=0;p<d.length;p++)d[p].expression===s&&(e+=K.sanitizeHTML(this._getFieldValue(s,h[s])+"\x3cbr/\x3e"),n+=1);n=m.create("div",{id:"SA_Feature_"+k},b);g.add(n,"SATcolRec");p=m.create("div",{},n);g.add(p,"SATcolRecBar");var t=m.create("div",{innerHTML:k},p);g.add(t,"SATcolRecNum");D.set(t,"backgroundColor",this.parent.config.color);
u(t,"click",l.hitch(this,this._zoomToLocation,r));w&&(t=m.create("div",{innerHTML:w},p),g.add(t,"SATcolDistance"));this.parent.config.enableRouting&&(p=m.create("div",{title:this.parent.nls.get_directions},p),g.add(p,"SATcolDir"),u(p,"click",l.hitch(this,this._routeToIncident,r)));e=m.create("div",{innerHTML:e},n);g.add(e,"SATcolInfo");e=new A(A.STYLE_SOLID,new x.fromString(this.parent.config.color),1);e=new z(z.STYLE_CIRCLE,24,e,new x.fromString(this.parent.config.color));n=new G;n.family="Arial";
n.size="12px";k=new H(k,n,"#ffffff");k.setOffset(0,-4);this.graphicsLayer.add(new y(r,e,h));this.graphicsLayer.add(new y(r,k,h))}},_exportToCSV:function(c){if(0===c.length)return!1;var b=this.tab.tabLayers[0].id,a=[],d=[];q.forEach(c,function(b){a.push(b.attributes)});for(var f in a[0])d.push(f);J.exportCSV(b,a,d)},_getFields:function(c){var b=[];if(this.tab.advStat&&this.tab.advStat.stats&&0<this.tab.advStat.stats.outFields.length)q.forEach(this.tab.advStat.stats.outFields,function(a){b.push(a.expression)});
else{var a;if(c.infoTemplate)a=c.infoTemplate.info.fieldInfos;else if(0<this.parent.map.itemInfo.itemData.operationalLayers.length){var d=this.parent.map.itemInfo.itemData.operationalLayers;a=null;var f=0;a:for(;f<d.length;f++){var k=d[f];if("ArcGISMapServiceLayer"===k.layerType&&"undefined"!==typeof k.layers)for(var h=0;h<k.layers.length;h++){var e=k.layers[h];if(e.popupInfo&&e.id===c.layerId){a=e.popupInfo.fieldInfos;break a}}}a||(a=c.fields)}else a=c.fields;for(d=0;d<a.length;d++)f=a[d],"undefined"!==
typeof f.visible?f.visible&&b.push(f.fieldName):b.push(f.name)}var g={};q.forEach(c.fields,l.hitch(this,function(a){if("esriFieldTypeDate"===a.type||a.domain){if("esriFieldTypeDate"===a.type&&c.infoTemplate)for(var b in c.infoTemplate._fieldsMap)"undefined"!==typeof c.infoTemplate._fieldsMap[b].fieldName&&(c.infoTemplate._fieldsMap[b].fieldName===a.name&&"undefined"!==typeof c.infoTemplate._fieldsMap[b].format.dateFormat)&&(this.dateFields[a.name]=c.infoTemplate._fieldsMap[b].format.dateFormat);g[a.name]=
a}}));this.specialFields=g;return b},_getFieldValue:function(c,b){var a=b;if(this.specialFields[c]){var d=this.specialFields[c];"esriFieldTypeDate"===d.type?"undefined"!==this.dateFields[c]?(d=this._getDateFormat(this.dateFields[c]),a=void 0!==typeof d?(new Date(b)).toLocaleDateString(navigator.language,d):(new Date(b)).toLocaleString()):a=(new Date(b)).toLocaleString():q.some(d.domain.codedValues,function(c){if(c.code===b)return a=c.name,!0})}return a},_getDateFormat:function(c){var b;switch(c){case "shortDate":b=
{month:"2-digit",day:"2-digit",year:"numeric"};break;case "shortDateLE":b={day:"2-digit",month:"2-digit",year:"numeric"};break;case "longMonthDayYear":b={month:"long",day:"2-digit",year:"numeric"};break;case "dayShortMonthYear":b={day:"2-digit",month:"short",year:"numeric"};break;case "longDate":b={weekday:"long",month:"long",day:"2-digit",year:"numeric"};break;case "shortDateLongTime":b={month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",second:"2-digit",hour12:!0};break;
case "shortDateLELongTime":b={day:"2-digit",month:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",second:"2-digit",hour12:!0};break;case "shortDateShortTime":b={month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!0};break;case "shortDateLEShortTime":b={day:"2-digit",month:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!0};break;case "shortDateShortTime24":b={month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!1};
break;case "shortDateLEShortTime24":b={day:"2-digit",month:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!1};break;case "longMonthYear":b={month:"long",year:"numeric"};break;case "shortMonthYear":b={month:"short",year:"numeric"};break;case "year":b={year:"numeric"}}return b},_getDistance:function(c,b){var a=0,d=this.parent.config.distanceUnits,a=E.distance(c,b,9001);switch(d){case "miles":a*=6.21371E-4;break;case "kilometers":a*=0.0010;break;case "feet":a*=3.28084;break;case "yards":a*=
1.09361;break;case "nauticalMiles":a*=5.39957E-4}return a},_compareDistance:function(c,b){return c.attributes.DISTANCE<b.attributes.DISTANCE?-1:c.attributes.DISTANCE>b.attributes.DISTANCE?1:0},_zoomToLocation:function(c){this.parent.zoomToLocation(c)},_routeToIncident:function(c){this.parent.routeToIncident(c)}})});