// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Chart/setting/nls/strings":{chartTasks:"Zadania diagramu",addNew:"Dodaj nowe",addNewTip:"Dodaj nowe zadanie diagramu",name:"Nazwa",set:"Ustaw",setDataSource:"Skonfiguruj \u017ar\u00f3d\u0142o danych",generalSettingsTip:"Skonfiguruj \u017ar\u00f3d\u0142a danych, tytu\u0142y i opisy diagram\u00f3w.",chartModeSettingTip:"Wybierz metod\u0119 analizy i spos\u00f3b wy\u015bwietlania danych w postaci diagram\u00f3w.",detailsSettingTip:"Skonfiguruj wygl\u0105d diagramu, okre\u015blaj\u0105c jego typ i kolor oraz warto\u015bci, kt\u00f3re zostan\u0105 na nim przedstawione:",
symbolSettingTip:"Skonfiguruj wy\u015bwietlanie mapy dla danych przedstawionych na diagramie.",addFilterTip:"Dodaj filtr do danych",dataSource:"\u0179r\u00f3d\u0142o danych",noResults:"Nie odnaleziono \u017cadnego obiektu.",chartTitle:"Tytu\u0142 diagramu",description:"Opis",chartingMode:"Wy\u015bwietlanie diagramu",featureOption:"Wy\u015bwietlaj warto\u015bci dla ka\u017cdego kolejnego obiektu",categoryOption:"Wy\u015bwietlaj warto\u015bci wg kategorii",countOption:"Wy\u015bwietlaj liczb\u0119 obiekt\u00f3w wg kategorii",
fieldOption:"Wy\u015bwietlaj warto\u015bci atrybut\u00f3w w postaci diagram\u00f3w",category:"Kategoria",axisLabel:"Etykieta kategorii",categoryField:"Pole kategorii",operation:"Operacja",originalOption:"U\u017cyj oryginalnych warto\u015bci",sumOption:"Suma",averageOption:"\u015arednia",minOption:"Minimum",maxOption:"Warto\u015b\u0107 maks.",valueFields:"Pola warto\u015bci",moveUp:"Przesu\u0144 w g\u00f3r\u0119",moveDown:"Przesu\u0144 w d\u00f3\u0142",sortOrder:"Sortuj diagramy wg etykiet kategorii",
ascending:"Rosn\u0105co",descending:"Malej\u0105co",chartType:"Typ diagramu",column:"Diagram kolumnowy",bar:"Diagram s\u0142upkowy grupowy",line:"Diagram liniowy",pie:"Diagram ko\u0142owy",chartColor:"Kolor diagramu",showDataLabels:"Poka\u017c etykiety danych",setSymbol:"Symbol selekcji",setHighLightColor:"Kolor wyr\u00f3\u017cnienia",settings:"Ustawienia",mapInterationOptions:"Opcje interakcji z map\u0105",preview:"Podgl\u0105d",ok:"OK",cancel:"Anuluj",close:"Zamknij",setFilterTip:"Skonfiguruj poprawnie filtr. ",
setChartTitleTip:"Skonfiguruj tytu\u0142 diagramu.",setChartTypeTip:"Wybierz przynajmniej jeden typ diagramu.",setDataFieldTip:"Wybierz przynajmniej jedno pole warto\u015bci.",setOutputFieldTip:"Skonfiguruj pola wyj\u015bciowe.",count:"Liczba",label:"Etykieta",horizontalAxis:"O\u015b pozioma",verticalAxis:"O\u015b pionowa",dataLabels:"Etykiety danych",color:"Kolor",colorful:"Kolorowe",monochromatic:"Monochromatyczne",noTaskTip:"Kliknij opcj\u0119 Dodaj nowe, aby doda\u0107 zadanie diagramu",info:"Informacje",
charts:"Diagramy",options:"Opcje",taskName:"Nazwa zadania",summary:"Podsumowanie",resultDescription:"Opis wynik\u00f3w",spatialFilterTip:"Wybierz filtry przestrzenne u\u017cywane w wid\u017cecie, aby ograniczy\u0107 liczb\u0119 wynik\u00f3w.",defaultOption:"Domy\u015blne",useCurrentExtentTip:"Cz\u0119\u015bciowo lub ca\u0142kowicie w bie\u017c\u0105cym zasi\u0119gu mapy",useDrawGraphicTip:"Cz\u0119\u015bciowo lub ca\u0142kowicie w zasi\u0119gu narysowanego na mapie obszaru",useFeaturesTip:"Na podstawie ich lokalizacji wzgl\u0119dem obiekt\u00f3w na innej warstwie",
noSpatialLimitTip:"Nie ograniczaj przestrzennie wynik\u00f3w wyszukiwania",drawingTools:"Narz\u0119dzia rysowania",bufferSettings:"Ustawienia bufora",defaultDistance:"Domy\u015blna odleg\u0142o\u015b\u0107",bufferDistance:"Odleg\u0142o\u015b\u0107 buforowania",defaultUnit:"Jednostka domy\u015blna",miles:"Mile",kilometers:"Kilometry",feet:"Stopy",meters:"Metry",yards:"Jardy",nauticalMiles:"Mile morskie",availableSpatialRelationships:"Dost\u0119pne zale\u017cno\u015bci przestrzenne",setSpatialRelationships:"Skonfiguruj zale\u017cno\u015bci przestrzenne",
availability:"Dost\u0119pno\u015b\u0107",relationship:"Zale\u017cno\u015b\u0107",actions:"Dzia\u0142ania",intersect:"przecinaj\u0105",contain:"zawieraj\u0105",areContainedIn:"s\u0105 zawarte w",cross:"krzy\u017cuj\u0105 si\u0119",envelopeIntersect:"przecinaj\u0105 obwiedni\u0119",overlap:"nachodz\u0105",areOverlapped:"s\u0105 zakryte",touche:"dotykaj\u0105",within:"w zasi\u0119gu",areWithin:"s\u0105 w zasi\u0119gu",indexIntersect:"przecinaj\u0105 indeks",_localized:{}}});