// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Miglia",acronym:"mi"},kilometers:{displayText:"Chilometri",acronym:"km"},feet:{displayText:"Piedi",acronym:"piedi"},meters:{displayText:"Metri",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Impostazione di ricerca",defaultBufferDistanceLabel:"Imposta valore distanza di buffer predefinita",maxBufferDistanceLabel:"Imposta valore distanza di buffer massima per la ricerca di feature",bufferDistanceUnitLabel:"Unit\u00e0 distanza di buffer",
defaultBufferHintLabel:"Suggerimento: utilizzare per impostare il valore predefinito per un buffer",maxBufferHintLabel:"Suggerimento: utilizzare per impostare il valore massimo per un buffer",bufferUnitLabel:"Suggerimento: definire unit\u00e0 di creazione buffer",selectGraphicLocationSymbol:"Simbolo indirizzo o posizione",graphicLocationSymbolHintText:"Suggerimento: simbolo per l'indirizzo ricercato o la posizione selezionata",fontColorLabel:"Seleziona colore font per risultati della ricerca",fontColorHintText:"Suggerimento: colore font dei risultati della ricerca"},
layerSelector:{selectLayerLabel:"Seleziona layer di ricerca",layerSelectionHint:"Suggerimento: utilizzare il pulsante di impostazione per selezionare layer",addLayerButton:"Imposta",okButton:"OK",cancelButton:"Annulla"},routeSetting:{routeSettingTabTitle:"Impostazioni direzione",routeServiceUrl:"Servizio itinerario",travelModeServiceUrl:"Servizio Modalit\u00e0 di viaggio",buttonSet:"Imposta",routeServiceUrlHintText:"Suggerimento: fare clic su \u2018Imposta\u2019 per individuare e selezionare un servizio itinerario",
directionLengthUnit:"Unit\u00e0 di lunghezza direzione",unitsForRouteHintText:"Suggerimento: utilizzato per visualizzare unit\u00e0 per percorso",selectRouteSymbol:"Seleziona simbolo per visualizzare percorso",routeSymbolHintText:"Suggerimento: utilizzato per visualizzare simbolo linea del percorso",travelModeServiceUrlHintText:"Suggerimento: fare clic su \u2018Imposta\u2019 per individuare e selezionare un servizio Modalit\u00e0 di viaggio",invalidTravelmodeServiceUrl:"Specificare un servizio Modalit\u00e0 di viaggio valido ",
routingDisabledMsg:"Per abilitare le direzioni accertarsi che gli itinerari siano abilitati nell'elemento di ArcGIS Online."},networkServiceChooser:{arcgislabel:"Aggiungi da ArcGIS Online",serviceURLabel:"Aggiungi URL del servizio",routeURL:"URL itinerario",validateRouteURL:"Convalida",exampleText:"Esempio",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",okButton:"OK",
cancelButton:"Annulla",nextButton:"Avanti",backButton:"Indietro",invalidRouteServiceURL:"Specificare un servizio Itinerari valido."},errorStrings:{bufferErrorString:"Immettere valore numerico valido.",selectLayerErrorString:"Selezionare i layer da cercare.",invalidDefaultValue:"La distanza di buffer predefinita non pu\u00f2 essere vuota. Specificare la distanza di buffer",invalidMaximumValue:"La distanza di buffer massima non pu\u00f2 essere vuota. Specificare la distanza di buffer",defaultValueLessThanMax:"Specificare la distanza di buffer predefinita all'interno del limite massimo",
defaultBufferValueGreaterThanZero:"Specificare la distanza di buffer predefinita maggiore di 0",maximumBufferValueGreaterThanZero:"Specificare la distanza di buffer massima maggiore di 0"},symbolPickerPreviewText:"Anteprima:",_localized:{}}});