// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Mile",acronym:"mi"},kilometers:{displayText:"Kilometer",acronym:"km"},feet:{displayText:"Fot",acronym:"fot"},meters:{displayText:"Meter",acronym:"m"}},searchSetting:{searchSettingTabTitle:"S\u00f6kinst\u00e4llningar",defaultBufferDistanceLabel:"Ange ett standardv\u00e4rde f\u00f6r buffertavst\u00e5nd",maxBufferDistanceLabel:"Ange ett maxv\u00e4rde f\u00f6r buffertavst\u00e5nd vid s\u00f6kning efter geoobjekt",bufferDistanceUnitLabel:"Enheter f\u00f6r buffertavst\u00e5nd",
defaultBufferHintLabel:"Tips: Anv\u00e4nds f\u00f6r att ange ett standardv\u00e4rde f\u00f6r en buffert",maxBufferHintLabel:"Tips: Anv\u00e4nds f\u00f6r att ange ett maxv\u00e4rde f\u00f6r en buffert",bufferUnitLabel:"Tips: Ange vilken enhet som ska anv\u00e4ndas n\u00e4r man skapar buffertar",selectGraphicLocationSymbol:"Adress- eller platssymbol",graphicLocationSymbolHintText:"Tips: Symbol f\u00f6r adresser som anv\u00e4ndarna s\u00f6kt efter eller platser som de klickat p\u00e5",fontColorLabel:"V\u00e4lj teckensnittsf\u00e4rg i s\u00f6kresultaten",
fontColorHintText:"Tips: Teckensnittsf\u00e4rg i s\u00f6kresultaten"},layerSelector:{selectLayerLabel:"V\u00e4lj s\u00f6klager",layerSelectionHint:"Tips: Ange knappen Ange f\u00f6r att v\u00e4lja lager",addLayerButton:"Ange",okButton:"OK",cancelButton:"Appar"},routeSetting:{routeSettingTabTitle:"Riktningsinst\u00e4llningar",routeServiceUrl:"Ruttj\u00e4nst",travelModeServiceUrl:"F\u00e4rdl\u00e4gestj\u00e4nst",buttonSet:"Ange",routeServiceUrlHintText:"Tips: Klicka p\u00e5 Ange f\u00f6r att leta efter och v\u00e4lja en ruttj\u00e4nst",
directionLengthUnit:"L\u00e4ngdenheter f\u00f6r riktning",unitsForRouteHintText:"Tips: Anv\u00e4nds f\u00f6r att visa enheter f\u00f6r rutter",selectRouteSymbol:"V\u00e4lj symbol f\u00f6r visning av rutten",routeSymbolHintText:"Tips: Visade tidigare en linjesymbol f\u00f6r rutten",travelModeServiceUrlHintText:"Tips: Klicka p\u00e5 Ange f\u00f6r att leta efter och markera en f\u00e4rdl\u00e4gestj\u00e4nst",invalidTravelmodeServiceUrl:"Ange en giltig f\u00e4rdl\u00e4gestj\u00e4nst ",routingDisabledMsg:"Om du vill anv\u00e4nda rutter och v\u00e4gbeskrivningar m\u00e5ste du kontrollera att det har aktiverats i objektet ArcGIS Online."},
networkServiceChooser:{arcgislabel:"L\u00e4gg till fr\u00e5n ArcGIS Online",serviceURLabel:"L\u00e4gg till tj\u00e4nst-URL",routeURL:"Rutt-URL",validateRouteURL:"Validera",exampleText:"Exempel",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",okButton:"OK",cancelButton:"Appar",nextButton:"N\u00e4sta",backButton:"Bakom",invalidRouteServiceURL:"Ange en giltig ruttj\u00e4nst."},
errorStrings:{bufferErrorString:"Ange ett giltigt numeriskt v\u00e4rde.",selectLayerErrorString:"V\u00e4lj vilka lager du vill s\u00f6ka i.",invalidDefaultValue:"Standardv\u00e4rdet f\u00f6r buffertavst\u00e5nd m\u00e5ste vara ifyllt. Ange buffertavst\u00e5ndet",invalidMaximumValue:"Maxv\u00e4rdet f\u00f6r buffertavst\u00e5nd m\u00e5ste vara ifyllt. Ange buffertavst\u00e5ndet",defaultValueLessThanMax:"Ange standardv\u00e4rdet f\u00f6r buffertavst\u00e5nd, och t\u00e4nk p\u00e5 att det inte f\u00e5r \u00f6verskrida maxgr\u00e4nsen",
defaultBufferValueGreaterThanZero:"Ange ett standardv\u00e4rde f\u00f6r buffertavst\u00e5ndet som \u00e4r st\u00f6rre \u00e4n noll",maximumBufferValueGreaterThanZero:"Ange ett maxv\u00e4rde f\u00f6r buffertavst\u00e5ndet som \u00e4r st\u00f6rre \u00e4n noll"},symbolPickerPreviewText:"F\u00f6rhandsgranska:",_localized:{}}});