// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Milhas",acronym:"mi"},kilometers:{displayText:"Quil\u00f3metros",acronym:"km"},feet:{displayText:"P\u00e9s",acronym:"ft"},meters:{displayText:"Metros",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Configura\u00e7\u00f5es da Pesquisa",defaultBufferDistanceLabel:"Definir valor distancia de buffer por omiss\u00e3o",maxBufferDistanceLabel:"Definir valor m\u00e1ximo de buffer para descobrir elementos",bufferDistanceUnitLabel:"Unidades de distancia buffer",
defaultBufferHintLabel:"Sugest\u00e3o: Usado para definir o valor por omiss\u00e3o para buffer",maxBufferHintLabel:"Sugest\u00e3o: Usado para definir o valor m\u00e1ximo para buffer",bufferUnitLabel:"Sugest\u00e3o: Definir unidade para cria\u00e7\u00e3o de buffer",selectGraphicLocationSymbol:"S\u00edmbolo de endere\u00e7o ou localiza\u00e7\u00e3o",graphicLocationSymbolHintText:"Sugest\u00e3o: S\u00edmbolo para endere\u00e7o pesquisado ou localiza\u00e7\u00e3o clicada",fontColorLabel:"Seleccionar cor de fonte para resultados de pesquisa",
fontColorHintText:"Sugest\u00e3o: Cor de fonte para resultados de pesquisa"},layerSelector:{selectLayerLabel:"Camada(s) de pesquisa seleccionada",layerSelectionHint:"Sugest\u00e3o: Ise o bot\u00e3o de defini\u00e7\u00e3o para camada(s) seleccionadas",addLayerButton:"Definir",okButton:"OK",cancelButton:"Cancelar"},routeSetting:{routeSettingTabTitle:"Defini\u00e7\u00f5es de direc\u00e7\u00e3o",routeServiceUrl:"Servi\u00e7o de Roteamento",travelModeServiceUrl:"Servi\u00e7o de Modo de Viagem",buttonSet:"Definir",
routeServiceUrlHintText:"Sugest\u00e3o: Clique 'Definir' para navegar e seleccionar um servi\u00e7o de roteamento",directionLengthUnit:"Unidades de comprimento de direc\u00e7\u00e3o",unitsForRouteHintText:"Sugest\u00e3o: Usado para exibir unidade para roteamento",selectRouteSymbol:"Seleccionar s\u00edmbolo para exibir rota",routeSymbolHintText:"Sugest\u00e3o: Usado para exibir s\u00edmbolo linha da rota",travelModeServiceUrlHintText:"Sugest\u00e3o: Clique 'Definir' para navegar e seleccionar um Servi\u00e7o de Modo de Viagem",
invalidTravelmodeServiceUrl:"Por favor especifique um servi\u00e7o de Modo de Viagem v\u00e1lido ",routingDisabledMsg:"Para permitir direc\u00e7\u00f5es certifique-se que o roteamento est\u00e1 activo no item ArcGIS Online."},networkServiceChooser:{arcgislabel:"Adicionar de ArcGIS Online",serviceURLabel:"Adicionar URL de Servi\u00e7o",routeURL:"URL de rota",validateRouteURL:"Validar",exampleText:"Exemplo",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",
okButton:"OK",cancelButton:"Cancelar",nextButton:"Seguinte",backButton:"Retroceder",invalidRouteServiceURL:"Por favor especifique o servi\u00e7o de Roteamento v\u00e1lido."},errorStrings:{bufferErrorString:"Por favor especifique um valor num\u00e9rico v\u00e1lido.",selectLayerErrorString:"Por favor seleccione camada(s) para pesquisar.",invalidDefaultValue:"A distancia buffer por omiss\u00e3o n\u00e3o pode estar em branco. Por favor especifique a distancia buffer",invalidMaximumValue:"Distancia m\u00e1xima buffer n\u00e3o pode estar em branco. Por favor especifique a distancia buffer",
defaultValueLessThanMax:"Por favor especifique a distancia buffer por omiss\u00e3o dentro do limite m\u00e1ximo",defaultBufferValueGreaterThanZero:"Por favor especifique a distancia buffer por omiss\u00e3o maior do que 0",maximumBufferValueGreaterThanZero:"Por favor especifique a distancia buffer m\u00e1xima maior do que 0"},symbolPickerPreviewText:"Visualizar:",_localized:{}}});