// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Mil",acronym:"mi"},kilometers:{displayText:"Kilometre",acronym:"km"},feet:{displayText:"Fit",acronym:"ft"},meters:{displayText:"Metre",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Arama Ayarlar\u0131",defaultBufferDistanceLabel:"Varsay\u0131lan tampon mesafesi de\u011ferini ayarla",maxBufferDistanceLabel:"Detay bulmak i\u00e7in maksimum tampon mesafesi de\u011ferini ayarla",bufferDistanceUnitLabel:"Tampon mesafesi birimleri",
defaultBufferHintLabel:"\u0130pucu: Tamponun varsay\u0131lan de\u011ferini ayarlamak i\u00e7in kullan\u0131n",maxBufferHintLabel:"\u0130pucu: Tamponun maksimum de\u011ferini ayarlamak i\u00e7in kullan\u0131n",bufferUnitLabel:"\u0130pucu: Tampon olu\u015fturma birimi tan\u0131mlay\u0131n",selectGraphicLocationSymbol:"Adres veya konum simgesi",graphicLocationSymbolHintText:"\u0130pucu: Aranan adres veya t\u0131klanan konum simgesi",fontColorLabel:"Arama sonu\u00e7lar\u0131 i\u00e7in yaz\u0131 tipi rengini belirle",
fontColorHintText:"\u0130pucu: Arama sonu\u00e7lar\u0131n\u0131n yaz\u0131 tipi rengi"},layerSelector:{selectLayerLabel:"Arama katmanlar\u0131n\u0131 se\u00e7",layerSelectionHint:"\u0130pucu: Katman se\u00e7mek i\u00e7in ayarla d\u00fc\u011fmesini kullan\u0131n",addLayerButton:"Ayarla",okButton:"Tamam",cancelButton:"\u0130ptal"},routeSetting:{routeSettingTabTitle:"Yol Tarifi Ayarlar\u0131",routeServiceUrl:"Rota Olu\u015fturma Servisi",travelModeServiceUrl:"Seyahat Modu Servisi",buttonSet:"Ayarla",
routeServiceUrlHintText:"\u0130pucu: Bir rota olu\u015fturma servisini inceleyerek se\u00e7mek i\u00e7in \u2018Ayarla\u2019 d\u00fc\u011fmesine t\u0131klay\u0131n",directionLengthUnit:"Yol tarifi uzunluk birimi",unitsForRouteHintText:"\u0130pucu: Rota birimini g\u00f6r\u00fcnt\u00fclemek i\u00e7in kullan\u0131l\u0131r",selectRouteSymbol:"Rotay\u0131 g\u00f6r\u00fcnt\u00fclemek i\u00e7in simge se\u00e7",routeSymbolHintText:"\u0130pucu: Rotan\u0131n \u00e7izgi simgesini g\u00f6r\u00fcnt\u00fclemek i\u00e7in kullan\u0131l\u0131r",
travelModeServiceUrlHintText:"\u0130pucu: Bir Seyahat Modu Servisini inceleyerek se\u00e7mek i\u00e7in \u2018Ayarla\u2019 d\u00fc\u011fmesine t\u0131klay\u0131n",invalidTravelmodeServiceUrl:"Ge\u00e7erli bir Seyahat Modu servisi belirtin. ",routingDisabledMsg:"Yol tarifi \u00f6zelli\u011fini etkinle\u015ftirmek i\u00e7in ArcGIS Online \u00f6\u011fesinde rota olu\u015fturman\u0131n etkinle\u015ftirildi\u011finden emin olun."},networkServiceChooser:{arcgislabel:"ArcGIS Online'dan Ekle",serviceURLabel:"Servis URL'si ekle",
routeURL:"Rotalama URL'si",validateRouteURL:"Do\u011frula",exampleText:"\u00d6rnek",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",okButton:"Tamam",cancelButton:"\u0130ptal",nextButton:"Sonraki",backButton:"Geri",invalidRouteServiceURL:"Ge\u00e7erli bir Rota servisi belirtin."},errorStrings:{bufferErrorString:"Ge\u00e7erli say\u0131sal de\u011fer girin.",selectLayerErrorString:"Aranacak katmanlar\u0131 se\u00e7in.",
invalidDefaultValue:"Varsay\u0131lan tampon mesafesi bo\u015f olamaz. Tampon mesafesini belirtin",invalidMaximumValue:"Maksimum tampon mesafesi bo\u015f olamaz. Tampon mesafesini belirtin",defaultValueLessThanMax:"Varsay\u0131lan tampon mesafesini maksimum s\u0131n\u0131r dahilinde belirtin",defaultBufferValueGreaterThanZero:"0'dan b\u00fcy\u00fck varsay\u0131lan tampon mesafesi belirtin",maximumBufferValueGreaterThanZero:"0'dan b\u00fcy\u00fck maksimum tampon mesafesi belirtin"},symbolPickerPreviewText:"\u00d6nizleme:",
_localized:{}}});