// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/nls/strings":{_widgetLabel:"Abfrage",executeQueryTip:"Klicken Sie auf einen der folgenden Tasks, um die Abfrage auszuf\u00fchren.",invalidConfig:"Ung\u00fcltige Konfiguration. Verwenden Sie die Seite f\u00fcr Abfrageeinstellungen, um die richtige Konfiguration abzurufen.",queryParams:"Optionen",parameters:"OPTIONEN",queries:"ABFRAGEN",apply:"\u00dcBERNEHMEN",queryResults:"Ergebnisse",clear:"L\u00f6schen",noResults:"Kein Feature gefunden.",queryError:"Abfrage fehlgeschlagen!",
numberFound:"Anzahl der gefundenen Features",mapExtentTip:"Beschr\u00e4nken Sie die Ergebnisse auf den aktuellen Kartenbereich.",noValue:"Kein Wert",and:"und",stringOperatorIs:"ist",stringOperatorIsNot:"ist nicht",stringOperatorStartsWith:"beginnt mit",stringOperatorEndsWith:"endet mit",stringOperatorContains:"enth\u00e4lt",stringOperatorDoesNotContain:"enth\u00e4lt nicht",stringOperatorIsBlank:"ist leer",stringOperatorIsNotBlank:"ist nicht leer",dateOperatorIsOn:"ist am",dateOperatorIsNotOn:"ist nicht am",
dateOperatorIsBefore:"ist vor",dateOperatorIsAfter:"ist nach",dateOperatorDays:"Tagen",dateOperatorWeeks:"Wochen",dateOperatorMonths:"Monate",dateOperatorInTheLast:"in den letzten",dateOperatorNotInTheLast:"nicht in den letzten",dateOperatorIsBetween:"liegt zwischen",dateOperatorIsNotBetween:"liegt nicht zwischen",dateOperatorIsBlank:"ist leer",dateOperatorIsNotBlank:"ist nicht leer",numberOperatorIs:"ist",numberOperatorIsNot:"ist nicht",numberOperatorIsAtLeast:"ist mindestens",numberOperatorIsLessThan:"ist kleiner als",
numberOperatorIsAtMost:"ist h\u00f6chstens",numberOperatorIsGreaterThan:"ist gr\u00f6\u00dfer als",numberOperatorIsBetween:"liegt zwischen",numberOperatorIsNotBetween:"liegt nicht zwischen",numberOperatorIsBlank:"ist leer",numberOperatorIsNotBlank:"ist nicht leer",operationalLayerTip:"Ergebnis als operationalen Layer hinzuf\u00fcgen",queryResult:"Abfrageergebnis",specifyParamsTip:"Parameter f\u00fcr diesen Task festlegen",useSpatialFilter:"R\u00e4umlichen Filter zum Begrenzen von Features verwenden",
useCurrentMapExtent:"Nur Features, die den aktuellen Kartenbereich schneiden",drawGraphicOnMap:"Nur Features, die den benutzerdefinierten Bereich schneiden",specifySpatialFilterMsg:"Geben Sie einen r\u00e4umlichen Filter f\u00fcr diesen Task an.",clearResults:"Ergebnisse l\u00f6schen",operationalTip:'Wenn diese Option aktiviert ist, werden die Ergebnisse auf der Karte beibehalten, bis auf die Schaltfl\u00e4che "${clearResults}" geklickt wird.',noneQueryTip:"F\u00fcr dieses Widget wurde kein Abfrage-Task konfiguriert.",
noPermissionsMsg:"Sie verf\u00fcgen nicht \u00fcber die entsprechenden Berechtigungen f\u00fcr den Zugriff auf diesen Service.",attributesFromRelationship:"Attribute aus zugeh\u00f6riger Tabelle",tasks:"Tasks",applySpatialFilterToLimitResults:"Zum Eingrenzen der Ergebnisse einen r\u00e4umlichen Filter anwenden",useCurrentExtentTip:"Teilweise oder vollst\u00e4ndig innerhalb der aktuellen Kartenausdehnung",useDrawGraphicTip:"Teilweise oder vollst\u00e4ndig innerhalb des auf der Karte dargestellten Shapes",
useFeaturesTip:"Basierend auf deren Positionen relativ zu Features in einem anderen Layer",noSpatialLimitTip:"Ergebnisse nicht r\u00e4umlich beschr\u00e4nken",applySearchDistance:"Eine Suchentfernung anwenden",spatialRelationship:"R\u00e4umliche Beziehung",relatedLayer:"Zugeh\u00f6riger Layer",bufferDistance:"Pufferabstand",miles:"Meilen",kilometers:"Kilometer",feet:"Fu\u00df",meters:"Meter",yards:"Yard",nauticalMiles:"Seemeilen",back:"Zur\u00fcck",execute:"Ausf\u00fchren",_localized:{}}});