// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/dom-class dojo/dom-construct dojo/dom-style dojo/on jimu/utils esri/geometry/geometryEngine esri/geometry/Polyline esri/graphic esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query".split(" "),function(A,m,u,r,B,k,n,C,v,D,y,E,w,F,z,s,G,H,I){return A("ClosestInfo",null,{constructor:function(c,b,a){this.tab=c;
this.container=b;this.parent=a;this.graphicsLayer=this.incident=null;this.map=a.map;this.specialFields={};this.dateFields={}},updateForIncident:function(c,b,a){r.forEach(this.tab.tabLayers,m.hitch(this,function(e){if("undefined"!==typeof e.empty){var f=new F(e.url);v(f,"load",m.hitch(this,function(){this.tab.tabLayers=[f];this.processIncident(c,b,a)}))}else this.processIncident(c,b,a)}))},processIncident:function(c,b,a){this.container.innerHTML="";k.add(this.container,"loading");var e=[];this.incident=
c;b=y.buffer(c.geometry,b,this.parent.config.distanceSettings[this.parent.config.distanceUnits]);this.graphicsLayer=a;this.graphicsLayer.clear();var f=this.tab.tabLayers;a=[];for(var g=0;g<f.length;g++){var d=f[g],h=new I;h.returnGeometry=!0;h.geometry=b;h.outFields=this._getFields(d);a.push(d.queryFeatures(h))}(new B(a)).then(m.hitch(this,function(b){for(var a=0;a<b.length;a++){var d=b[a][1],g=this._getFields(f[a]),d=d.features;if(0<d.length){for(var h=0;h<d.length;h++){for(var k=d[h],n={DISTANCE:this._getDistance(c.geometry,
k.geometry)},m=0;m<g.length;m++)n[g[m]]=k.attributes[g[m]];k.attributes=n}d.sort(this._compareDistance);e.push(d[0])}}this._processResults(e)}))},_processResults:function(c){this.container.innerHTML="";k.remove(this.container,"loading");0===c.length&&this.buffer?this.container.innerHTML=this.parent.nls.noFeaturesFound:0===c.length&&!this.buffer&&(this.container.innerHTML=this.parent.nls.defaultTabMsg);var b=n.create("div",{id:"SA_tpc",style:"width:"+220*c.length+"px;"},this.container);k.add(b,"SAT_tabPanelContent");
for(var a=this.parent.nls[this.parent.config.distanceUnits],e=0;e<c.length;e++){var f=e+1,g=c[e],d=g.geometry,h=d;"point"!==d.type&&(h=d.getExtent().getCenter());var g=g.attributes,x;"point"===this.incident.geometry.type&&(x=a+": "+Math.round(100*g.DISTANCE)/100);var d="",l=0,t;for(t in g)"DISTANCE"!==t&&3>l&&(d+=D.sanitizeHTML(this._getFieldValue(t,g[t])+"\x3cbr/\x3e"),l+=1);l=n.create("div",{id:"SA_Feature_"+f},b);k.add(l,"SATcolRec");var p=n.create("div",{},l);k.add(p,"SATcolRecBar");var q=n.create("div",
{innerHTML:f},p);k.add(q,"SATcolRecNum");C.set(q,"backgroundColor",this.parent.config.color);v(q,"click",m.hitch(this,this._zoomToLocation,h));x&&(q=n.create("div",{innerHTML:x},p),k.add(q,"SATcolDistance"));this.parent.config.enableRouting&&(p=n.create("div",{title:this.parent.nls.get_directions},p),k.add(p,"SATcolDir"),v(p,"click",m.hitch(this,this._routeToIncident,h)));d=n.create("div",{innerHTML:d},l);k.add(d,"SATcolInfo");d=new s(s.STYLE_SOLID,new u.fromString(this.parent.config.color),1);d=
new z(z.STYLE_CIRCLE,24,d,new u.fromString(this.parent.config.color));l=new G;l.family="Arial";l.size="12px";f=new H(f,l,"#ffffff");f.setOffset(0,-4);null===g.OUTSIDE_POLYGON&&(l=new s(s.STYLE_SOLID,new u([0,0,0,1]),1),p=new E(h.spatialReference),q=this.incident.geometry,"point"!==this.incident.geometry.type&&(q=this.incident.geometry.getExtent().getCenter()),p.addPath([h,q]),this.graphicsLayer.add(new w(p,l,{})));this.graphicsLayer.add(new w(h,d,g));this.graphicsLayer.add(new w(h,f,g))}},_getFields:function(c){var b=
[];if(this.tab.advStat&&this.tab.advStat.stats&&0<this.tab.advStat.stats.outFields.length)r.forEach(this.tab.advStat.stats.outFields,function(a){b.push(a.expression)});else{var a;if(c.infoTemplate)a=c.infoTemplate.info.fieldInfos;else if(0<this.parent.map.itemInfo.itemData.operationalLayers.length){var e=this.parent.map.itemInfo.itemData.operationalLayers;a=null;var f=0;a:for(;f<e.length;f++){var g=e[f];if("ArcGISMapServiceLayer"===g.layerType&&"undefined"!==typeof g.layers)for(var d=0;d<g.layers.length;d++){var h=
g.layers[d];if(h.id===c.layerId&&h.popupInfo){a=h.popupInfo.fieldInfos;break a}}}a||(a=c.fields)}else a=c.fields;if(a)for(e=0;e<a.length;e++)f=a[e],"undefined"!==typeof f.visible?f.visible&&b.push(f.fieldName):b.push(f.name)}var k={};c.fields&&r.forEach(c.fields,m.hitch(this,function(a){if("esriFieldTypeDate"===a.type||a.domain){if("esriFieldTypeDate"===a.type&&c.infoTemplate)for(var b in c.infoTemplate._fieldsMap)"undefined"!==typeof c.infoTemplate._fieldsMap[b].fieldName&&(c.infoTemplate._fieldsMap[b].fieldName===
a.name&&"undefined"!==typeof c.infoTemplate._fieldsMap[b].format.dateFormat)&&(this.dateFields[a.name]=c.infoTemplate._fieldsMap[b].format.dateFormat);k[a.name]=a}}));this.specialFields=k;return b},_getFieldValue:function(c,b){var a=b;if(this.specialFields[c]){var e=this.specialFields[c];"esriFieldTypeDate"===e.type?"undefined"!==this.dateFields[c]?(e=this._getDateFormat(this.dateFields[c]),a=void 0!==typeof e?(new Date(b)).toLocaleDateString(navigator.language,e):(new Date(b)).toLocaleString()):
a=(new Date(b)).toLocaleString():r.some(e.domain.codedValues,function(c){if(c.code===b)return a=c.name,!0})}return a},_getDateFormat:function(c){var b;switch(c){case "shortDate":b={month:"2-digit",day:"2-digit",year:"numeric"};break;case "shortDateLE":b={day:"2-digit",month:"2-digit",year:"numeric"};break;case "longMonthDayYear":b={month:"long",day:"2-digit",year:"numeric"};break;case "dayShortMonthYear":b={day:"2-digit",month:"short",year:"numeric"};break;case "longDate":b={weekday:"long",month:"long",
day:"2-digit",year:"numeric"};break;case "shortDateLongTime":b={month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",second:"2-digit",hour12:!0};break;case "shortDateLELongTime":b={day:"2-digit",month:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",second:"2-digit",hour12:!0};break;case "shortDateShortTime":b={month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!0};break;case "shortDateLEShortTime":b={day:"2-digit",month:"2-digit",year:"numeric",
hour:"numeric",minute:"2-digit",hour12:!0};break;case "shortDateShortTime24":b={month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!1};break;case "shortDateLEShortTime24":b={day:"2-digit",month:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!1};break;case "longMonthYear":b={month:"long",year:"numeric"};break;case "shortMonthYear":b={month:"short",year:"numeric"};break;case "year":b={year:"numeric"}}return b},_getDistance:function(c,b){var a=0,e=this.parent.config.distanceUnits,
a=y.distance(c,b,9001);switch(e){case "miles":a*=6.21371E-4;break;case "kilometers":a*=0.0010;break;case "feet":a*=3.28084;break;case "yards":a*=1.09361;break;case "nauticalMiles":a*=5.39957E-4}return a},_compareDistance:function(c,b){return c.attributes.DISTANCE<b.attributes.DISTANCE?-1:c.attributes.DISTANCE>b.attributes.DISTANCE?1:0},_zoomToLocation:function(c){this.parent.zoomToLocation(c)},_routeToIncident:function(c){this.parent.routeToIncident(c)}})});