// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/RelatedTableCharts/ChartLayout.html":'\x3cdiv\x3e\r\n    \x3cdiv class\x3d"esriCTLayoutContent"\x3e\r\n        \x3cdiv class\x3d"esriCTLabels"\x3e\r\n            \x3cdiv class\x3d"esriCTLayoutHeaderTitle" data-dojo-attach-point\x3d"layoutHeaderTitle"\x3e\r\n            \x3c/div\x3e\r\n        \x3c/div\x3e\r\n        \x3cdiv class\x3d"esriCTChartContainer" data-dojo-attach-point\x3d"chartContainer"\x3e\r\n        \x3c/div\x3e\r\n        \x3cdiv class\x3d"esriCTChartDescription" data-dojo-attach-point\x3d"chartDescription"\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("jimu/BaseWidgetSetting jimu/utils dojo/dom-attr dojo/dom-construct dojo/dom-style dojo/_base/declare dojo/_base/lang dijit/_WidgetsInTemplateMixin dojo/text!./ChartLayout.html dojox/charting/Chart dojox/charting/plot2d/Pie dojox/charting/action2d/Tooltip dojox/charting/action2d/Highlight dojox/charting/action2d/MoveSlice dojox/charting/plot2d/Bars dojox/charting/axis2d/Default".split(" "),function(q,r,l,k,h,s,t,u,v,m,w,n,p,x){return s([q,u],{baseClass:"jimu-widget-RelatedTableCharts-layout",
templateString:v,postCreate:function(){this.inherited(arguments)},startup:function(){this._createChartLayout()},_createChartLayout:function(){this._setNodeValue(this.layoutHeaderTitle,this.config.chartConfig.chartTitle,!0);this._setNodeValue(this.chartDescription,this.config.chartConfig.description,!1);this._initChart()},resize:function(a){this.chart&&setTimeout(t.hitch(this,function(){"PieChart"===this.config.chartConfig.chartType?this._createPieChart():this.chart.resize()}),a)},_setNodeValue:function(a,
d,b){var c=d;this.config.isPreview||(c=this._getFieldValues(d,this.config.selectedFeature.attributes));c?(c=r.sanitizeHTML(c),l.set(a,"innerHTML",c),b&&l.set(a,"title",c)):h.set(a,"display","none")},_initChart:function(){switch(this.config.chartConfig.chartType){case "BarChart":this._createBarChart();break;case "PieChart":this._createPieChart();break;default:l.set(this.chartContainer,"innerHTML",this.nls.errMsgNoFeaturesFound)}},_getBarChartContainerHeight:function(){var a=30;0<this.config.chartData.chartSeries.length&&
(a=30*this.config.chartData.chartSeries.length);150>=a&&(a+=100);return a+"px"},_createBarChart:function(){var a,d={},b={};a=40;var c,g,e={};k.empty(this.chartContainer);a=this._getBarChartContainerHeight();a=new m(k.create("div",{style:"overflow:hidden; width:100%; height:"+a},this.chartContainer));a.addPlot("default",{type:"Bars",gap:4,minBarSize:10,maxBarSize:15});b=h.get(this.chartDescription,"fontFamily");c=h.get(this.chartDescription,"fontSize");g=h.get(this.chartDescription,"color");d={labels:this.config.chartData.chartLabels,
maxLabelCharCount:30,trailingSymbol:"...",natural:!0,majorTickStep:1,minorTicks:!1,fixUpper:!0,includeZero:!1,vertical:!0,titleFontColor:g,titleFont:"normal normal normal "+c+" "+b};b={fixLower:"major",fixUpper:"major",minorTicks:!1,includeZero:!0,titleFontColor:g,titleFont:"normal normal normal "+c+" "+b};this.config.isPreview?(b.titleGap=5,d.majorTick={length:0},b.majorTick={length:0},d.majorLabels=!1,b.majorLabels=!1,d.minorLabels=!1,b.minorLabels=!1,d.title=this.config.chartConfig.labelYAxis,
b.title=this.config.chartConfig.labelXAxis,e.stroke={width:0}):(new n(a,"default"),d.title=this._getFieldValues(this.config.chartConfig.labelYAxis,this.config.selectedFeature.attributes),b.title=this._getFieldValues(this.config.chartConfig.labelXAxis,this.config.selectedFeature.attributes),e.stroke={width:1});b.titleOrientation="away";a.addAxis("y",d);a.addAxis("x",b);this.config.chartData.selectedTheme&&a.setTheme(this.config.chartData.selectedTheme);this.config.chartData.fill&&(e.fill=this.config.chartData.fill);
a.addSeries(this.config.chartConfig.dataSeriesField,this.config.chartData.chartSeries,e,{plot:"default"});new p(a,"default");a.render();this.chart=a;this.onChartCreated()},_createPieChart:function(){var a,d={},b=45;k.empty(this.chartContainer);a=k.create("div",{style:"width:100%; height:100%; overflow:auto"},this.chartContainer);a=new m(a);d={type:w,labels:!0,ticks:!0,fixed:!0,precision:0,radius:b,labelWiring:"#ccc",labelStyle:"columns",htmlLabels:!0,startAngle:-10,maxLabelCharCount:20,trailingSymbol:"..."};
b=(h.get(this.chartContainer,"width")-180)/2;45>b&&(b=45);100<b&&(b=100);d.radius=b;"esriCTEmptyOption"===this.config.chartConfig.labelField&&(d.labels=!1);a.addPlot("default",d);this.config.isPreview||new n(a,"default");this.config.chartData.fill?a.addSeries(this.config.chartConfig.dataSeriesField,this.config.chartData.chartSeries,{fill:this.config.chartData.fill},{plot:"default"}):a.addSeries(this.config.dataSeriesField,this.config.chartData.chartSeries,{plot:"default"});this.config.chartData.selectedTheme&&
a.setTheme(this.config.chartData.selectedTheme);new x(a,"default");new p(a,"default");a.render();this.chart=a;this.onChartCreated()},onChartCreated:function(){},_getFieldValues:function(a,d){var b,c="",g,e,f;a=a.replace(/(\n|\r|\r\n)/g,"\x3cbr\x3e");g=a.split("{");for(e=0;e<g.length;e++)if(0===e)c+=g[e];else if(-1!==g[e].indexOf("}")){b=g[e].split("}");for(f=0;f<b.length;f++)if(0===f){if(d[b[f]]||0===d[b[f]])c+=d[b[f]]}else c=1===f?c+b[f]:c+("}"+b[f])}else c+="{";return c}})});