// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/setting/nls/strings":{queries:"Tareas de consulta",addNew:"Agregar nueva",queryLayer:"Capa de consulta",setSource:"Establecer",setDataSource:"Definir fuente de datos",name:"Nombre",querySource:"Fuente de datos",queryName:"Nombre de tarea",queryDefinition:"Definici\u00f3n de filtro",resultsSetting:"Configuraci\u00f3n de resultados",symbolSetting:"Configuraci\u00f3n de s\u00edmbolo",resultSettingTip:"Define qu\u00e9 se debe mostrar en los resultados de salida y c\u00f3mo mostrarlo.",
resultItemTitle:"T\u00edtulo del elemento de resultado",resultItemContent:"Contenido del elemento de resultado",fieldsSetTip:"Marca los campos que deseas mostrar. Selecciona un campo para actualizar su alias, su orden y su formato.",addField:"Agregar campo",visibility:"Visibilidad",alias:"Alias",specialType:"Tipo especial",actions:"Acciones",none:"Ninguno",link:"V\u00ednculo",image:"Imagen",noField:"Sin campo",operationalLayerTip:"Agregar resultado como capa operativa",setLayerSymbolTip:"Establecer el s\u00edmbolo para los resultados de consulta: ",
setSelectedSymbolTip:"Establece el s\u00edmbolo de la entidad seleccionada.",notUseFilter:"No utilizar filtro",setSourceTip:"Define la fuente de consulta.",setFilterTip:"Define el filtro correctamente.",ok:"Aceptar",cancel:"Cancelar",noFilterTip:"Sin expresi\u00f3n de filtro definida, esta tarea de consulta enumerar\u00e1 todas las entidades de la fuente de datos especificada.",relationships:"Relaciones",addRelationshipLayer:"Agregar nueva relaci\u00f3n",relatedTo:"Relacionado con",selectOption:"Selecciona...",
resultItemSorting:"Ordenaci\u00f3n de los resultados",field:"Campo",sortingOrder:"Orden",configureFieldsTip:"Configura los campos seg\u00fan los cuales se debe ordenar el resultado de la consulta.",setSortingFields:"Configurar campos de ordenaci\u00f3n",ascending:"Ascendente",descending:"Descendente",sortBy:"Ordenar por",thenBy:"A continuaci\u00f3n por",addTask:"Agregar tarea",noTasksTip:'No hay ninguna tarea. Haz clic en "${addTask}" para comenzar.',infoText:"Informaci\u00f3n",filters:"Filtros",
results:"Resultados",optionsText:"Opciones",summaryText:"Resumen",attributeFilter:"Filtro de atributo",attributeFilterTip:"Define las expresiones de atributos que se deben usar en el widget para filtrar la capa de consulta.",noExpressionDefinedTip:"No se ha definido ninguna expresi\u00f3n.",needInputValuesTip:"Se deben introducir valores en tiempo de ejecuci\u00f3n",setExpressions:"Definir expresiones",spatialFilter:"Filtro espacial",spatialFilterTip:"Elige los filtros espaciales utilizados en el widget para limitar los resultados.",
defaultOption:"Predeterminado",useCurrentExtentTip:"Parcial o totalmente dentro de la extensi\u00f3n de mapa actual",useDrawGraphicTip:"Parcial o totalmente dentro de la forma dibujada en el mapa",useFeaturesTip:"En funci\u00f3n de sus ubicaciones con respecto a las entidades de otra capa",noSpatialLimitTip:"No limitar espacialmente los resultados",drawingTools:"Herramientas de dibujo",bufferSettings:"Configuraci\u00f3n de la zona de influencia",defaultDistance:"Distancia predeterminada",bufferDistance:"Distancia de zona de influencia",
defaultUnit:"Unidad predeterminada",miles:"Millas",kilometers:"Kil\u00f3metros",feet:"Pies",meters:"Metros",yards:"Yardas",nauticalMiles:"Millas N\u00e1uticas",availableSpatialRelationships:"Relaciones espaciales disponibles",setSpatialRelationships:"Definir relaciones espaciales",availability:"Disponibilidad",relationship:"Relaci\u00f3n",label:"Etiqueta",intersect:"intersecar",contain:"contienen",areContainedIn:"est\u00e1n contenidas en",cross:"cruz",envelopeIntersect:"intersecci\u00f3n con el contorno",
overlap:"superponer",areOverlapped:"se superponen",touche:"se tocan",within:"dentro de",areWithin:"est\u00e1n dentro de",indexIntersect:"con intersecci\u00f3n de \u00edndice",itemTitle:"T\u00edtulo del elemento",displayFields:"Campos de visualizaci\u00f3n",sortingFields:"Campos de ordenaci\u00f3n",setDisplayFields:"Definir campos de visualizaci\u00f3n",symbol:"S\u00edmbolo",setSymbol:"Definir s\u00edmbolo",serviceSymbolTip:"Usar s\u00edmbolos definidos por la capa",exportTip:"Mostrar bot\u00f3n de exportaci\u00f3n",
keepResultsTip:"Conservar resultados en el mapa despu\u00e9s de cerrar el widget",queryRelatedRecords:"Consultar registros relacionados",createLayerForTaskTip:"Especifica c\u00f3mo crea las capas la tarea",oneLayerForTaskTip:"Crear solo una capa para esta tarea",multipleLayerForTaskTip:"Crear una nueva capa cada vez que se ejecute esta tarea",_localized:{}}});