// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array jimu/LayerInfos/LayerInfos dojo/Deferred dojo/promise/all exports dojo/store/Observable dojo/store/Cache dojo/store/Memory esri/lang ./FeatureLayerQueryStore jimu/utils".split(" "),function(f,k,u,p,m,d,w,x,v,s,y,l){function z(a){var b=[],h=[];k.forEach(a,function(c){var r=b.indexOf(c.name);0>r?b.push(c.name):(h.push(a[r]),h.push(c))});k.forEach(h,function(a){a.name=a.name+"-"+a.id})}function A(a,b){if(!a||!a.length)return b||[];if(!b||!b.length)return a;for(var h=
[],c=0,r=a.length;c<r;c++)for(var g=a[c],e=0,t=b.length;e<t;e++)if(b[e].name===g.name){h.push(g);break}return h}d.readLayerInfosObj=function(a){return u.getInstance(a,a.itemInfo)};d.readLayerInfosFromMap=function(a,b,h){var c=new p;u.getInstance(a,a.itemInfo).then(f.hitch(this,function(a){var g=[];b?a.traversalLayerInfosOfWebmap(function(a){g.push(a)}):a.traversal(function(a){g.push(a)});if(h){var e=[],t=a.getMapNotesLayerInfoArray();k.forEach(t,function(a){e.push(a.id);a.traversal(function(a){e.push(a.id)})});
g=k.filter(g,function(a){return-1===e.indexOf(a.id)})}a=a.getTableInfoArray();g=g.concat(a);c.resolve(g)}),f.hitch(this,function(a){console.error(a);c.reject(a)}));return c.promise};d.generateColumnsFromFields=function(a,b,h,c,r){function g(b){if(a&&s.isDefined(a.fieldInfos))for(var c=0,g=a.fieldInfos.length;c<g;c++){var e=a.fieldInfos[c];if(e.fieldName===b)return e.format}return null}var e={};k.forEach(b,f.hitch(d,function(a,b,q){var n="field"+b,l=!!a.domain,p="esriFieldTypeDate"===a.type,m=h&&a.name===
h;e[n]={label:a.alias||a.name,className:n,hidden:1===q.length?!1:!a.show&&s.isDefined(a.show),unhidable:1===q.length?!1:!a.show&&s.isDefined(a.show)&&a._pk,field:a.name};e[n].sortable=!!r;if("esriFieldTypeString"===q[b].type)e[n].formatter=f.hitch(d,d.urlFormatter);else if("esriFieldTypeDate"===q[b].type)e[n].formatter=f.hitch(d,d.dateFormatter,g(a.name));else if("esriFieldTypeDouble"===q[b].type||"esriFieldTypeSingle"===q[b].type||"esriFieldTypeInteger"===q[b].type||"esriFieldTypeSmallInteger"===
q[b].type)e[n].formatter=f.hitch(d,d.numberFormatter,g(a.name));l?e[n].get=f.hitch(d,function(a,b){return this.getCodeValue(a.domain,b[a.name])},a):m?e[n].get=f.hitch(d,function(a,b,c){return this.getTypeName(c[a.name],b)},a,c):!l&&(!p&&!m)&&(e[n].get=f.hitch(d,function(a,b,c,g){var e=null;b&&c&&0<c.length&&(c=(c=k.filter(c,f.hitch(d,function(a){return a.name===g[b]})))&&c[0]||null)&&(c.domains&&c.domains[a.name]&&c.domains[a.name].codedValues)&&(e=this.getCodeValue(c.domains[a.name],g[a.name]));
return(a=null!==e?e:g[a.name])||isFinite(a)?a:""},a,h,c))}));return e};d.getTypeName=function(a,b){return l.fieldFormatter.getTypeName(a,b)};d.getCodeValue=function(a,b){return l.fieldFormatter.getCodedValue(a,b)};d.urlFormatter=function(a){return l.fieldFormatter.getFormattedUrl(a)};d.dateFormatter=function(a,b){return l.fieldFormatter.getFormattedDate(b,a)};d.numberFormatter=function(a,b){return l.fieldFormatter.getFormattedNumber(b,a)};d.readLayerObjectsFromMap=function(a,b,h){var c=new p,d=[];
this.readLayerInfosFromMap(a,b,h).then(f.hitch(this,function(a){k.forEach(a,f.hitch(this,function(a){d.push(a.getLayerObject())}));m(d).then(f.hitch(this,function(a){c.resolve(a)}),f.hitch(this,function(a){c.reject(a);console.error(a)}))}),f.hitch(this,function(a){c.reject(a)}));return c.promise};d.readSupportTableInfoFromLayerInfos=function(a){var b=new p,h=[];k.forEach(a,f.hitch(this,function(a){h.push(a.getSupportTableInfo())}));m(h).then(f.hitch(this,function(c){c=f.clone(c);k.forEach(c,function(b,
c){b.id=a[c].id});b.resolve(c)}),function(a){b.reject(a)});return b.promise};d.readConfigLayerInfosFromMap=function(a,b,h){var c=new p,d=[];this.readLayerInfosFromMap(a,b,h).then(f.hitch(this,function(a){var b=[];k.forEach(a,function(a){d.push(a.getSupportTableInfo())});m(d).then(f.hitch(this,function(d){k.forEach(d,f.hitch(this,function(c,d){c.isSupportedLayer&&(a[d].name=a[d].title,b.push(a[d]))}));z(b);c.resolve(b)}),f.hitch(this,function(a){c.reject(a)}))}),f.hitch(this,function(a){c.reject(a)}));
return c.promise};d.getConfigInfosFromLayerInfos=function(a){return k.map(a,function(a){return d.getConfigInfoFromLayerInfo(a)})};d.getConfigInfoFromLayerInfo=function(a){var b={};b.name=a.name||a.title;b.id=a.id;b.show=a.isShowInMap();b.layer={url:a.getUrl()};var d=a.getPopupInfo();d&&!d.description&&(b.layer.fields=k.map(d.fieldInfos,function(a){return{name:a.fieldName,alias:a.label,show:a.visible,format:a.format}}),a=f.getObject("layerObject.fields",!1,a),b.layer.fields=A(b.layer.fields,a),k.some(b.layer.fields,
function(a){return a.show})||(b.layer.fields[0].show=!0));return b};d.generateCacheStore=function(a,b,d,c,f){a=new y({layer:a,objectIds:a._objectIds||null,totalCount:b,batchCount:d,where:c||"1\x3d1",spatialFilter:f});b=new v;return new x(a,b,{})};d.generateMemoryStore=function(a,b){return new w(new v({data:a||[],idProperty:b}))};d.merge=function(a,b,d,c){for(var f=k.map(b,function(a){return a[d]}),g=0,e=a.length;g<e;g++){var l=f.indexOf(a[g][d]);-1<l&&c(a[g],b[l])}};d.syncOrderWith=function(a,b,d){function c(a,
b){return k.map(a,function(a){return a[b]})}if(!f.isArray(b)||!d)return a;for(var l=c(a,d),g=[],e=0,p=b.length;e<p;e++){var m=l.indexOf(b[e][d]);-1<m&&(g=g.concat(a.splice(m,1)),l=c(a,d))}return g.concat(a)}});