// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/setting/nls/strings":{queries:"Opera\u0163ii de interogare",addNew:"Ad\u0103ugare nou",queryLayer:"Strat tematic interogare",setSource:"Setare",setDataSource:"Setare surs\u0103 de date",name:"Nume",querySource:"Surs\u0103 date",queryName:"Nume opera\u0163ie",queryDefinition:"Defini\u0163ie filtru",resultsSetting:"Setare rezultate",symbolSetting:"Setare simbol",resultSettingTip:"Defini\u0163i care sunt \u015fi cum s\u0103 fie afi\u015fate rezultatele.",resultItemTitle:"Titlu element rezultat",
resultItemContent:"Con\u0163inut element rezultat",fieldsSetTip:"Bifa\u0163i c\u00e2mpurile care dori\u0163i s\u0103 fie afi\u015fate. Selecta\u0163i un c\u00e2mp pentru a-i actualiza pseudonimul, pentru a-l reordona sau pentru a-l formata.",addField:"Ad\u0103ugare c\u00e2mp",visibility:"Vizibilitate",alias:"Pseudonim",specialType:"Tip special",actions:"Ac\u0163iuni",none:"Niciunul",link:"Link",image:"Imagine",noField:"Niciun c\u00e2mp",operationalLayerTip:"Ad\u0103ugare rezultat drept strat tematic opera\u0163ional",
setLayerSymbolTip:"Seta\u0163i simbolul pentru rezultatele interog\u0103rii: ",setSelectedSymbolTip:"Seta\u0163i simbolul pentru obiectul spa\u0163ial selectat.",notUseFilter:"Nu se utilizeaz\u0103 filtrul",setSourceTip:"Seta\u0163i sursa interog\u0103rii.",setFilterTip:"Seta\u0163i corect filtrul.",ok:"OK",cancel:"Anulare",noFilterTip:"F\u0103r\u0103 a avea expresia de filtrare definit\u0103, aceast\u0103 opera\u0163ie de interogare va lista toate obiectele spa\u0163iale din sursa de date specificat\u0103.",
relationships:"Rela\u0163ii",addRelationshipLayer:"Ad\u0103ugare rela\u0163ie nou\u0103",relatedTo:"Referitor la",selectOption:"Selecta\u0163i...",resultItemSorting:"Sortare elemente rezultate",field:"C\u00e2mp",sortingOrder:"Ordine",configureFieldsTip:"Configura\u0163i c\u00e2mpurile dup\u0103 care vor fi sortate rezultatele interog\u0103rii.",setSortingFields:"Configurarea c\u00e2mpuri sortare",ascending:"Ascendent",descending:"Descendent",sortBy:"Sortare dup\u0103",thenBy:"Apoi dup\u0103",addTask:"Ad\u0103ugare activitate",
noTasksTip:'Nicio activitate, face\u0163i clic pe "${addTask}" pentru a \u00eencepe!',infoText:"Informa\u0163ii",filters:"Filtre",results:"Rezultate",optionsText:"Op\u0163iuni",summaryText:"Rezumat",attributeFilter:"Filtru atribute",attributeFilterTip:"Defini\u0163i expresiile atributelor pentru a fi utilizate \u00een widget cu scopul de a filtra stratul tematic de interog\u0103ri.",noExpressionDefinedTip:"Nu a fost definit\u0103 nicio expresie.",needInputValuesTip:"Trebuie introduse valorile la runtime",
setExpressions:"Setare expresii",spatialFilter:"Filtru spa\u0163ial",spatialFilterTip:"Alege\u0163i filtrele spa\u0163iale utilizate \u00een widget pentru limitarea rezultatelor.",defaultOption:"Implicit",useCurrentExtentTip:"Par\u0163ial sau complet \u00een cadrul extinderii curente de hart\u0103",useDrawGraphicTip:"Par\u0163ial sau complet \u00een cadrul formei trasate pe hart\u0103",useFeaturesTip:"\u00cen baza loca\u0163iilor, \u00een raport cu obiectele spa\u0163iale din alt strat tematic",noSpatialLimitTip:"Nu limita\u0163i spa\u0163ial rezultatele",
drawingTools:"Instrumente de trasare",bufferSettings:"Set\u0103ri buffer",defaultDistance:"Distan\u0163\u0103 implicit\u0103",bufferDistance:"Distan\u0163\u0103 buffer",defaultUnit:"Unitate implicit\u0103",miles:"Mile",kilometers:"Kilometri",feet:"Ft",meters:"Metri",yards:"Iarzi",nauticalMiles:"Mile marine",availableSpatialRelationships:"Rela\u0163ie spa\u0163ial\u0103 disponibil\u0103",setSpatialRelationships:"Setare rela\u0163ie spa\u0163ial\u0103",availability:"Disponibilitate",relationship:"Rela\u0163ie",
label:"Etichet\u0103",intersect:"intersectare",contain:"con\u0163ine",areContainedIn:"sunt con\u0163inute de",cross:"cruce",envelopeIntersect:"intersectare plic",overlap:"suprapunere",areOverlapped:"sunt suprapuse",touche:"atins",within:"\u00een",areWithin:"sunt la",indexIntersect:"intersectare index",itemTitle:"Titlu element",displayFields:"C\u00e2mpuri de afi\u015fare",sortingFields:"C\u00e2mpuri sortare",setDisplayFields:"Setare c\u00e2mpuri de afi\u015fare",symbol:"Simbol",setSymbol:"Setare simbol",
serviceSymbolTip:"Utiliza\u0163i simbolurile definite de stratul tematic",exportTip:"Afi\u015fare buton Export",keepResultsTip:"P\u0103strare rezultate pe hart\u0103 dup\u0103 \u00eenchiderea widgetului",queryRelatedRecords:"\u00cenregistr\u0103ri legate de interog\u0103ri",createLayerForTaskTip:"Specifica\u0163i modul \u00een care activitatea creeaz\u0103 straturi tematice",oneLayerForTaskTip:"Crea\u0163i un singur strat tematic pentru aceast\u0103 activitate",multipleLayerForTaskTip:"Crea\u0163i un strat tematic nou de fiecare dat\u0103 c\u00e2nd este executat\u0103 aceast\u0103 activitate",
_localized:{}}});