// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/nls/strings":{_widgetLabel:"Sp\u00f8rring",executeQueryTip:"Klikk p\u00e5 ett av disse oppgaveelementene for \u00e5 utf\u00f8re sp\u00f8rringen.",invalidConfig:"Ugyldig konfigurasjon. Bruk innstillingssiden for sp\u00f8rringer til \u00e5 hente riktig konfigurasjon.",queryParams:"Alternativer",parameters:"ALTERNATIVER",queries:"SP\u00d8RRINGER",apply:"BRUK",queryResults:"Resultater",clear:"Fjern",noResults:"Fant ingen geoobjekter.",queryError:"Sp\u00f8rringen mislyktes.",numberFound:"Antall geoobjekter som ble funnet:",
mapExtentTip:"Begrens resultatene til det gjeldende kartomr\u00e5det.",noValue:"Ingen verdi",and:"og",stringOperatorIs:"er",stringOperatorIsNot:"er ikke",stringOperatorStartsWith:"begynner p\u00e5",stringOperatorEndsWith:"slutter p\u00e5",stringOperatorContains:"inneholder",stringOperatorDoesNotContain:"inneholder ikke",stringOperatorIsBlank:"er tomt",stringOperatorIsNotBlank:"er ikke tomt",dateOperatorIsOn:"er den",dateOperatorIsNotOn:"er ikke den",dateOperatorIsBefore:"er f\u00f8r",dateOperatorIsAfter:"er etter",
dateOperatorDays:"dagene",dateOperatorWeeks:"ukene",dateOperatorMonths:"m\u00e5nedene",dateOperatorInTheLast:"i de/den siste",dateOperatorNotInTheLast:"ikke i de/den siste",dateOperatorIsBetween:"er mellom",dateOperatorIsNotBetween:"er ikke mellom",dateOperatorIsBlank:"er tomt",dateOperatorIsNotBlank:"er ikke tomt",numberOperatorIs:"er",numberOperatorIsNot:"er ikke",numberOperatorIsAtLeast:"er minst",numberOperatorIsLessThan:"er mindre enn",numberOperatorIsAtMost:"er maksimalt",numberOperatorIsGreaterThan:"er st\u00f8rre enn",
numberOperatorIsBetween:"er mellom",numberOperatorIsNotBetween:"er ikke mellom",numberOperatorIsBlank:"er tomt",numberOperatorIsNotBlank:"er ikke tomt",operationalLayerTip:"Legg til resultat som operativt kartlag",queryResult:"Sp\u00f8rringsresultat",specifyParamsTip:"Angi parametere for denne oppgaven",useSpatialFilter:"Bruk geografisk filter til \u00e5 begrense geoobjekter",useCurrentMapExtent:"Bare geoobjekter som krysser det gjeldende kartomr\u00e5det",drawGraphicOnMap:"Bare geoobjekter som krysser det brukerdefinerte omr\u00e5det",
specifySpatialFilterMsg:"Angi et romlig filter for denne oppgaven.",clearResults:"Fjern resultater",operationalTip:"N\u00e5r dette alternativet er merket av, beholdes resultatene p\u00e5 kartet frem til det klikkes p\u00e5 knappen ${clearResults}.",noneQueryTip:"Ingen sp\u00f8rringsoppgave er konfigurert for denne widgeten.",noPermissionsMsg:"Du har ikke tillatelse til \u00e5 bruke denne tjenesten.",attributesFromRelationship:"Attributter fra relatert tabell",tasks:"Oppgaver",applySpatialFilterToLimitResults:"Bruk et romlig filter til \u00e5 begrense resultatene",
useCurrentExtentTip:"Delvis eller helt innenfor gjeldende kartutstrekning",useDrawGraphicTip:"Delvis eller helt innenfor formen tegnet p\u00e5 kartet",useFeaturesTip:"Basert p\u00e5 deres lokasjoner i forhold til geoobjekter i andre lag",noSpatialLimitTip:"Ikke bruk romlig begrensing p\u00e5 resultater",applySearchDistance:"Bruk en s\u00f8keavstand",spatialRelationship:"Romlig relasjon",relatedLayer:"Relatert lag",bufferDistance:"Bufferavstand",miles:"Miles",kilometers:"kilometer",feet:"fot",meters:"meter",
yards:"Yards",nauticalMiles:"Nautiske mil",back:"Tilbake",execute:"Utf\u00f8r",_localized:{}}});