// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/nls/strings":{_widgetLabel:"Consulta",executeQueryTip:"Haz clic en uno de los siguientes elementos de tarea para ejecutar la consulta.",invalidConfig:"Configuraci\u00f3n no v\u00e1lida. Utiliza la p\u00e1gina de configuraci\u00f3n de consulta para obtener la configuraci\u00f3n correcta.",queryParams:"Opciones",parameters:"OPCIONES",queries:"CONSULTAS",apply:"APLICAR",queryResults:"Resultados",clear:"Borrar",noResults:"Ninguna entidad encontrada.",queryError:"Error en la consulta",
numberFound:"N\u00famero de entidades encontradas",mapExtentTip:"Limita los resultados al \u00e1rea de mapa actual.",noValue:"Sin valor",and:"y",stringOperatorIs:"es",stringOperatorIsNot:"no es",stringOperatorStartsWith:"comienza por",stringOperatorEndsWith:"termina en",stringOperatorContains:"contiene",stringOperatorDoesNotContain:"no contiene",stringOperatorIsBlank:"est\u00e1 vac\u00edo",stringOperatorIsNotBlank:"no est\u00e1 vac\u00edo",dateOperatorIsOn:"es el",dateOperatorIsNotOn:"no es el",dateOperatorIsBefore:"es anterior a",
dateOperatorIsAfter:"es posterior a",dateOperatorDays:"d\u00edas",dateOperatorWeeks:"semanas",dateOperatorMonths:"meses",dateOperatorInTheLast:"es el \u00faltimo",dateOperatorNotInTheLast:"no es el \u00faltimo",dateOperatorIsBetween:"est\u00e1 entre",dateOperatorIsNotBetween:"no est\u00e1 entre",dateOperatorIsBlank:"est\u00e1 vac\u00edo",dateOperatorIsNotBlank:"no est\u00e1 vac\u00edo",numberOperatorIs:"es",numberOperatorIsNot:"no es",numberOperatorIsAtLeast:"es como m\u00ednimo",numberOperatorIsLessThan:"es menos que",
numberOperatorIsAtMost:"es como m\u00e1ximo",numberOperatorIsGreaterThan:"es mayor que",numberOperatorIsBetween:"est\u00e1 entre",numberOperatorIsNotBetween:"no est\u00e1 entre",numberOperatorIsBlank:"est\u00e1 vac\u00edo",numberOperatorIsNotBlank:"no est\u00e1 vac\u00edo",operationalLayerTip:"Agregar resultado como capa operativa",queryResult:"Resultado de consulta",specifyParamsTip:"Especificar par\u00e1metros para esta tarea",useSpatialFilter:"Usar filtro espacial para limitar las entidades",useCurrentMapExtent:"Solo entidades que intersequen el \u00e1rea de mapa actual",
drawGraphicOnMap:"Solo entidades que intersequen el \u00e1rea definida por el usuario",specifySpatialFilterMsg:"Especifica un filtro espacial para esta tarea.",clearResults:"Borrar resultados",operationalTip:'Con esta opci\u00f3n seleccionada, los resultados se conservar\u00e1n en el mapa hasta que se haga clic en el bot\u00f3n "${clearResults}".',noneQueryTip:"No se ha configurado ninguna tarea de consulta para este widget.",noPermissionsMsg:"No tienes permisos para acceder a este servicio.",attributesFromRelationship:"Atributos de la tabla asociada",
tasks:"Tareas",applySpatialFilterToLimitResults:"Aplicar un filtro espacial para limitar los resultados",useCurrentExtentTip:"Parcial o totalmente dentro de la extensi\u00f3n de mapa actual",useDrawGraphicTip:"Parcial o totalmente dentro de la forma dibujada en el mapa",useFeaturesTip:"En funci\u00f3n de sus ubicaciones con respecto a las entidades de otra capa",noSpatialLimitTip:"No limitar espacialmente los resultados",applySearchDistance:"Aplicar una distancia de b\u00fasqueda",spatialRelationship:"Relaci\u00f3n espacial",
relatedLayer:"Capa relacionada",bufferDistance:"Distancia de zona de influencia",miles:"Millas",kilometers:"Kil\u00f3metros",feet:"Pies",meters:"Metros",yards:"Yardas",nauticalMiles:"Millas N\u00e1uticas",back:"Atr\u00e1s",execute:"Ejecutar",_localized:{}}});