// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/nls/strings":{_widgetLabel:"Requ\u00eate",executeQueryTip:"Cliquez sur un des \u00e9l\u00e9ments de t\u00e2ches suivants pour ex\u00e9cuter la requ\u00eate.",invalidConfig:"Configuration non valide. Utilisez la page Param\u00e8tres de la requ\u00eate pour obtenir une configuration appropri\u00e9e.",queryParams:"Options",parameters:"OPTIONS",queries:"REQUETES",apply:"APPLIQUER",queryResults:"R\u00e9sultats",clear:"Effacer",noResults:"Aucune entit\u00e9 trouv\u00e9e.",queryError:"La requ\u00eate a \u00e9chou\u00e9\u00a0!",
numberFound:"Nombre d\u2019entit\u00e9s trouv\u00e9es",mapExtentTip:"Limitez les r\u00e9sultats \u00e0 la zone cartographique actuelle.",noValue:"Aucune valeur",and:"et",stringOperatorIs:"est",stringOperatorIsNot:"n'est pas",stringOperatorStartsWith:"commence par",stringOperatorEndsWith:"se termine par",stringOperatorContains:"contient",stringOperatorDoesNotContain:"ne contient pas",stringOperatorIsBlank:"est vide",stringOperatorIsNotBlank:"n'est pas vide",dateOperatorIsOn:"est le",dateOperatorIsNotOn:"n'est pas le",
dateOperatorIsBefore:"est avant",dateOperatorIsAfter:"est apr\u00e8s",dateOperatorDays:"jours",dateOperatorWeeks:"semaines",dateOperatorMonths:"mois",dateOperatorInTheLast:"au cours des derniers",dateOperatorNotInTheLast:"pas au cours des derniers",dateOperatorIsBetween:"est entre",dateOperatorIsNotBetween:"n'est pas entre",dateOperatorIsBlank:"est vide",dateOperatorIsNotBlank:"n'est pas vide",numberOperatorIs:"est",numberOperatorIsNot:"n'est pas",numberOperatorIsAtLeast:"est au moins",numberOperatorIsLessThan:"est inf\u00e9rieur \u00e0",
numberOperatorIsAtMost:"est au plus",numberOperatorIsGreaterThan:"est sup\u00e9rieur \u00e0",numberOperatorIsBetween:"est entre",numberOperatorIsNotBetween:"n'est pas entre",numberOperatorIsBlank:"est vide",numberOperatorIsNotBlank:"n'est pas vide",operationalLayerTip:"Ajouter le r\u00e9sultat comme couche op\u00e9rationnelle",queryResult:"R\u00e9sultat de la requ\u00eate",specifyParamsTip:"Sp\u00e9cifier les param\u00e8tres de cette t\u00e2che",useSpatialFilter:"Utiliser un filtre spatial pour limiter les entit\u00e9s",
useCurrentMapExtent:"Uniquement les entit\u00e9s qui intersectent la zone cartographique actuelle",drawGraphicOnMap:"Uniquement les entit\u00e9s qui intersectent la zone d\u00e9finie par l'utilisateur",specifySpatialFilterMsg:"Sp\u00e9cifiez un filtre spatial pour cette t\u00e2che.",clearResults:"Effacer les r\u00e9sultats",operationalTip:'Lorsque cette option est s\u00e9lectionn\u00e9e, les r\u00e9sultats sont conserv\u00e9s sur la carte jusqu\u2019\u00e0 l\u2019activation du bouton "${clearResults}".',
noneQueryTip:"Aucune t\u00e2che de requ\u00eate n'a \u00e9t\u00e9 configur\u00e9e pour ce widget.",noPermissionsMsg:"Vous n\u2019\u00eates pas autoris\u00e9 \u00e0 acc\u00e9der \u00e0 ce service.",attributesFromRelationship:"Attributs de la table associ\u00e9e",tasks:"T\u00e2ches",applySpatialFilterToLimitResults:"Appliquer un filtre spatial pour limiter les r\u00e9sultats",useCurrentExtentTip:"Partiellement ou enti\u00e8rement dans l'\u00e9tendue de la carte actuelle",useDrawGraphicTip:"Partiellement ou enti\u00e8rement dans la forme dessin\u00e9e sur la carte",
useFeaturesTip:"En fonction de leurs emplacements par rapport aux entit\u00e9s d'une autre couche",noSpatialLimitTip:"Ne pas limiter spatialement les r\u00e9sultats",applySearchDistance:"Appliquer une distance de recherche",spatialRelationship:"Relation spatiale",relatedLayer:"Couche associ\u00e9e",bufferDistance:"Distance de la zone tampon",miles:"Miles",kilometers:"Kilom\u00e8tres",feet:"Pieds",meters:"M\u00e8tres",yards:"Yards",nauticalMiles:"Milles nautiques",back:"Retour",execute:"Ex\u00e9cuter",
_localized:{}}});