// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Grassetto",copy:"Copia",cut:"Taglia","delete":"Elimina",indent:"Rientro",insertHorizontalRule:"Righello orizzontale",insertOrderedList:"Elenco numerato",insertUnorderedList:"Elenco puntato",italic:"Corsivo",justifyCenter:"Allinea al centro",justifyFull:"Giustifica",justifyLeft:"Allinea a sinistra",justifyRight:"Allinea a destra",outdent:"Annulla rientro",paste:"Incolla",redo:"Ripristina",removeFormat:"Rimuovi formato",selectAll:"Seleziona tutto",strikethrough:"Barrato",
subscript:"Pedice",superscript:"Apice",underline:"Sottolinea",undo:"Annulla",unlink:"Rimuovi collegamento",createLink:"Crea collegamento",toggleDir:"Attiva/Disattiva direzione",insertImage:"Inserisci immagine",insertTable:"Inserisci/Modifica tabella",toggleTableBorder:"Attiva/Disattiva bordo tabella",deleteTable:"Elimina tabella",tableProp:"Propriet\u00e0 tabella",htmlToggle:"Origine HTML",foreColor:"Colore primo piano",hiliteColor:"Colore sfondo",plainFormatBlock:"Stile paragrafo",formatBlock:"Stile paragrafo",
fontSize:"Dimensione carattere",fontName:"Nome carattere",tabIndent:"Rientro tabulazione",fullScreen:"Attiva/Disattiva schermo intero",viewSource:"Visualizza origine HTML",print:"Stampa",newPage:"Nuova pagina",systemShortcut:'La azione "${0}" \u00e8 disponibile solo nel browser tramite un tasto di scelta rapida. Utilizzare ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"dom lun mar mer gio ven sab".split(" "),
"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"ora","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"giorno della settimana","field-wed-relative+0":"questo mercoled\u00ec","field-wed-relative+1":"mercoled\u00ec prossimo","dateFormatItem-GyMMMEd":"E d MMM y G","dateFormatItem-MMMEd":"E d MMM",eraNarrow:["AH"],"field-tue-relative+-1":"marted\u00ec scorso","days-format-short":"dom lun mar mer gio ven sab".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"dd MMMM y G","field-fri-relative+-1":"venerd\u00ec scorso","field-wed-relative+-1":"mercoled\u00ec scorso","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE d MMMM y G","dateFormatItem-yyyyMEd":"E d/M/y GGGGG","field-thu-relative+-1":"gioved\u00ec scorso",
"dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["1\u00ba trimestre","2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],"timeFormat-long":"HH:mm:ss z",
"field-year":"anno","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"ora","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"questo sabato","field-sat-relative+1":"sabato prossimo","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"oggi","field-thu-relative+0":"questo gioved\u00ec","field-day-relative+1":"domani","field-thu-relative+1":"gioved\u00ec prossimo",
"dateFormatItem-GyMMMd":"d MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["T1","T2","T3","T4"],"quarters-standAlone-wide":["Primo trimestre","Secondo trimestre","Terzo trimestre","Quarto trimestre"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E d MMM y G","dateFormatItem-M":"L","days-standAlone-wide":"Domenica Luned\u00ec Marted\u00ec Mercoled\u00ec Gioved\u00ec Venerd\u00ec Sabato".split(" "),
"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"questa domenica","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"domenica prossima","quarters-standAlone-abbr":["T1","T2","T3","T4"],eraAbbr:["AH"],"field-minute":"minuto","field-dayperiod":"periodo del giorno","days-standAlone-abbr":"dom lun mar mer gio ven sab".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1",
"2","3","4"],"field-day-relative+-1":"ieri","dateTimeFormat-long":"{1} 'alle' {0}","dayPeriods-format-narrow-am":"m.","dateFormatItem-h":"hh a","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E d/M","dateTimeFormat-full":"{1} 'alle' {0}","field-fri-relative+0":"questo venerd\u00ec","field-fri-relative+1":"venerd\u00ec prossimo","field-day":"giorno","days-format-wide":"domenica luned\u00ec marted\u00ec mercoled\u00ec gioved\u00ec venerd\u00ec sabato".split(" "),"field-zone":"fuso orario","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),
"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"anno scorso","field-month-relative+-1":"mese scorso","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"hh:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"dom lun mar mer gio ven sab".split(" "),eraNames:["AH"],"days-format-narrow":"DLMMGVS".split(""),"dateFormatItem-yyyyMd":"d/M/y GGGGG","field-month":"mese","days-standAlone-narrow":"DLMMGVS".split(""),
"dateFormatItem-MMM":"LLL","field-tue-relative+0":"questo marted\u00ec","field-tue-relative+1":"marted\u00ec prossimo","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"questo luned\u00ec","field-mon-relative+1":"luned\u00ec prossimo","dateFormat-short":"dd/MM/yy GGGGG","dateFormatItem-EHms":"E HH:mm:ss",
"dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"secondo","field-sat-relative+-1":"sabato scorso","field-sun-relative+-1":"domenica scorsa","field-month-relative+0":"questo mese","field-month-relative+1":"mese prossimo","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E d","field-week":"settimana","dateFormat-medium":"dd/MMM/y G","field-week-relative+-1":"settimana scorsa","field-year-relative+0":"quest'anno","dateFormatItem-yyyyM":"M/y GGGGG",
"field-year-relative+1":"anno prossimo","dayPeriods-format-narrow-pm":"p.","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"hh:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"luned\u00ec scorso","dateFormatItem-yyyy":"y G","field-week-relative+0":"questa settimana","field-week-relative+1":"settimana prossima","field-day-relative+2":"dopodomani","field-day-relative+-2":"l'altro ieri",_localized:{}},"widgets/BatchAttributeEditor/nls/strings":{_widgetLabel:"Editor attributi batch",
widgetIntroSelectByArea:"Utilizzare uno degli strumenti sottostanti per creare un insieme selezionato di feature da aggiornare.  Se la riga \u00e8 \x3cfont class\x3d'maxRecordInIntro'\x3eevidenziata\x3c/font\x3e, \u00e8 stato superato il numero massimo di record.",widgetIntroSelectByFeature:"Utilizzare lo strumento sottostante per selezionare una feature dal layer \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e.  Questa feature verr\u00e0 utilizzata per selezionare e aggiornare tutte le feature che intersecano.  Se la riga \u00e8 \x3cfont class\x3d'maxRecordInIntro'\x3eevidenziata\x3c/font\x3e, \u00e8 stato superato il numero massimo di record.",
widgetIntroSelectByFeatureQuery:"Utilizzare lo strumento sottostante per selezionare una feature da \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e.  Questo attributo \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e della feature verr\u00e0 utilizzato per interrogare i layer sottostanti e aggiornare le feature risultanti.  Se la riga \u00e8 \x3cfont class\x3d'maxRecordInIntro'\x3eevidenziata\x3c/font\x3e, \u00e8 stato superato il numero massimo di record.",widgetIntroSelectByQuery:"Immettere un valore per creare un set di selezione.  Se la riga \u00e8 \x3cfont class\x3d'maxRecordInIntro'\x3eevidenziata\x3c/font\x3e, \u00e8 stato superato il numero massimo di record.",
layerTable:{colLabel:"Nome layer",numSelected:"#",colSyncStatus:""},noConfiguredLayers:"Nessun layer modificabile configurato",editorPopupTitle:"Editor attributi batch",editorPopupSaveBtn:"Salva",editorPopupMultipleValues:"",clear:"Azzera",featuresUpdated:"${0} / ${1} feature aggiornate",featuresSelected:"${0} feature selezionate",featuresSkipped:"Ignorate",search:"Ricerca",queryInput:"Immettere valore per l'interrogazione",noFilterTip:"Se non si definisce l'espressione di filtro, questa attivit\u00e0 di interrogazione restituir\u00e0 tutte le feature presenti nell'origine dati specificata.",
setFilterTip:"Impostare il filtro correttamente.",filterPopup:"Filtra layer",cancel:"Annulla",ok:"OK",drawBox:{point:"Punto",line:"Linea",polyline:"Polilinea",freehandPolyline:"Polilinea a mano libera",extent:"Estensione",polygon:"Poligono",freehandPolygon:"Poligono a mano libera",clear:"Azzera",addPointToolTip:"Fare clic per selezionare quest'area",addShapeToolTip:"Disegnare una forma per selezionare le feature",freehandToolTip:"Premere e tenere premuto per disegnare una forma per selezionare feature.",
startToolTip:"Disegnare una forma per selezionare le feature"},errors:{layerNotFound:"Impossibile trovare il layer ${0} con ID ${1} nella mappa. \u00c8 possibile che la mappa sia stata modificata dalla configurazione dei widget",queryNullID:"La feature di ${0} ha restituito un ID non valido",noSelectedLayers:"Nessun layer selezionato con record da aggiornare",inputValueError:"Valore non valido nel modulo"},_localized:{}}});