// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fed",copy:"Kopi\u00e9r",cut:"Klip","delete":"Slet",indent:"Indrykning",insertHorizontalRule:"Vandret linje",insertOrderedList:"Nummereret liste",insertUnorderedList:"Punktliste",italic:"Kursiv",justifyCenter:"Centreret",justifyFull:"Lige margener",justifyLeft:"Venstrejusteret",justifyRight:"H\u00f8jrejusteret",outdent:"Udrykning",paste:"S\u00e6t ind",redo:"Annull\u00e9r Fortryd",removeFormat:"Fjern format",selectAll:"Mark\u00e9r alle",strikethrough:"Gennemstreget",
subscript:"S\u00e6nket skrift",superscript:"H\u00e6vet skrift",underline:"Understreget",undo:"Fortryd",unlink:"Fjern link",createLink:"Opret link",toggleDir:"Skift retning",insertImage:"Inds\u00e6t billede",insertTable:"Inds\u00e6t/redig\u00e9r tabel",toggleTableBorder:"Skift tabelramme",deleteTable:"Slet tabel",tableProp:"Tabelegenskab",htmlToggle:"HTML-kilde",foreColor:"Forgrundsfarve",hiliteColor:"Baggrundsfarve",plainFormatBlock:"Afsnitstypografi",formatBlock:"Afsnitstypografi",fontSize:"Skriftst\u00f8rrelse",
fontName:"Skriftnavn",tabIndent:"Tabulatorindrykning",fullScreen:"Fuld sk\u00e6rm til/fra",viewSource:"Vis HTML-kilde",print:"Udskriv",newPage:"Ny side",systemShortcut:'Funktionen "${0}" kan kun bruges i din browser med en tastaturgenvej. Brug ${1}.',ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"s\u00f8 ma ti on to fr l\u00f8".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"nu",
"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Ugedag","field-wed-relative+0":"denne onsdag","field-wed-relative+1":"n\u00e6ste onsdag","dateFormatItem-GyMMMEd":"E d. MMM y G","dateFormatItem-MMMEd":"E d. MMM",eraNarrow:["AH"],"field-tue-relative+-1":"sidste tirsdag","days-format-short":"s\u00f8 ma ti on to fr l\u00f8".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d. MMMM y G","field-fri-relative+-1":"sidste fredag","field-wed-relative+-1":"sidste onsdag",
"months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE d. MMMM y G","dateFormatItem-yyyyMEd":"E d/M/y G","field-thu-relative+-1":"sidste torsdag","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"middag",
"field-era":"\u00c6ra","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH.mm","quarters-format-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"timeFormat-long":"HH.mm.ss z","field-year":"\u00c5r","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Time","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),
"field-sat-relative+0":"denne l\u00f8rdag","field-sat-relative+1":"n\u00e6ste l\u00f8rdag","timeFormat-full":"HH.mm.ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"i dag","field-thu-relative+0":"denne torsdag","field-day-relative+1":"i morgen","field-thu-relative+1":"n\u00e6ste torsdag","dateFormatItem-GyMMMd":"d. MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),
"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-standAlone-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E d. MMM y G","dateFormatItem-M":"M","days-standAlone-wide":"s\u00f8ndag mandag tirsdag onsdag torsdag fredag l\u00f8rdag".split(" "),"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d. MMM y G","dayPeriods-format-abbr-noon":"middag","timeFormat-medium":"HH.mm.ss","field-sun-relative+0":"denne s\u00f8ndag",
"dateFormatItem-Hm":"HH.mm","field-sun-relative+1":"n\u00e6ste s\u00f8ndag","quarters-standAlone-abbr":["K1","K2","K3","K4"],eraAbbr:["AH"],"field-minute":"Minut","field-dayperiod":"AM/PM","days-standAlone-abbr":"s\u00f8n man tir ons tor fre l\u00f8r".split(" "),"dateFormatItem-d":"d.","dateFormatItem-ms":"mm.ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"i g\u00e5r","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d. MMM",
"dateFormatItem-MEd":"E d/M","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"denne fredag","field-fri-relative+1":"n\u00e6ste fredag","field-day":"Dag","days-format-wide":"s\u00f8ndag mandag tirsdag onsdag torsdag fredag l\u00f8rdag".split(" "),"field-zone":"Tidszone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"sidste \u00e5r","field-month-relative+-1":"sidste m\u00e5ned",
"dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h.mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"s\u00f8n. man. tir. ons. tor. fre. l\u00f8r.".split(" "),eraNames:["AH"],"days-format-narrow":"SMTOTFL".split(""),"dateFormatItem-yyyyMd":"d/M/y G","field-month":"M\u00e5ned","days-standAlone-narrow":"SMTOTFL".split(""),"dateFormatItem-MMM":"MMM","field-tue-relative+0":"denne tirsdag","field-tue-relative+1":"n\u00e6ste tirsdag",
"dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"denne mandag","field-mon-relative+1":"n\u00e6ste mandag","dateFormat-short":"d/M/y","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"middag","field-second":"Sekund","field-sat-relative+-1":"sidste l\u00f8rdag",
"field-sun-relative+-1":"sidste s\u00f8ndag","field-month-relative+0":"denne m\u00e5ned","field-month-relative+1":"n\u00e6ste m\u00e5ned","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E 'd'. d.","field-week":"Uge","dateFormat-medium":"d. MMM y G","field-week-relative+-1":"sidste uge","field-year-relative+0":"i \u00e5r","dateFormatItem-yyyyM":"M/y G","field-year-relative+1":"n\u00e6ste \u00e5r","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1} {0}",
"dateFormatItem-Hms":"HH.mm.ss","dateFormatItem-hms":"h.mm.ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"sidste mandag","dateFormatItem-yyyy":"y G","field-week-relative+0":"denne uge","field-week-relative+1":"n\u00e6ste uge","field-day-relative+2":"i overmorgen","field-day-relative+-2":"i forg\u00e5rs",_localized:{}},"widgets/BatchAttributeEditor/nls/strings":{_widgetLabel:"Batch-attribut-editor",widgetIntroSelectByArea:"Brug et af v\u00e6rkt\u00f8jerne nedenfor til at oprette et udvalgt s\u00e6t objekter, der skal opdateres. Hvis r\u00e6kken er \x3cfont class\x3d'maxRecordInIntro'\x3efremh\u00e6vet\x3c/font\x3e, er det maksimale antal poster blevet overskredet.",
widgetIntroSelectByFeature:"Brug v\u00e6rkt\u00f8jet nedenfor til at v\u00e6lge et objekt fra \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e laget. Dette objekt vil blive brugt til at v\u00e6lge og opdatere alle objekter, der gennemsk\u00e6res. Hvis r\u00e6kken er \x3cfont class\x3d'maxRecordInIntro'\x3efremh\u00e6vet\x3c/font\x3e, er det maksimale antal poster blevet overskredet.",widgetIntroSelectByFeatureQuery:"Brug v\u00e6rkt\u00f8jet nedenfor til at v\u00e6lge et objekt fra \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Dette objekts \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e-attribut vil blive brugt til at foresp\u00f8rge p\u00e5 lagene nedenfor og opdatere de resulterende objekter. Hvis r\u00e6kken er \x3cfont class\x3d'maxRecordInIntro'\x3efremh\u00e6vet\x3c/font\x3e, er det maksimale antal poster blevet overskredet.",
widgetIntroSelectByQuery:"Angiv en v\u00e6rdi for at oprette et markeringss\u00e6t. Hvis r\u00e6kken er \x3cfont class\x3d'maxRecordInIntro'\x3efremh\u00e6vet\x3c/font\x3e, er det maksimale antal poster blevet overskredet.",layerTable:{colLabel:"Navn p\u00e5 lag",numSelected:"#",colSyncStatus:""},noConfiguredLayers:"Ingen redig\u00e9rbare lag er konfigureret",editorPopupTitle:"Batch-attribut-editor",editorPopupSaveBtn:"Gem",editorPopupMultipleValues:"",clear:"Ryd",featuresUpdated:"${0} / ${1} objekt(er) opdateret",
featuresSelected:"${0} objekt(er) valgt",featuresSkipped:"Tilsidesat",search:"Search",queryInput:"Angiv en v\u00e6rdi, der skal foresp\u00f8rges om",noFilterTip:"Defineres der ikke et filterudtryk, viser denne foresp\u00f8rgsel alle objekter i den angivne datakilde.",setFilterTip:"Angiv filteret korrekt.",filterPopup:"Filtr\u00e9r lag",cancel:"Annull\u00e9r",ok:"OK",drawBox:{point:"Punkt",line:"Linje",polyline:"Polylinje",freehandPolyline:"Frih\u00e5ndspolylinje",extent:"Udstr\u00e6kning",polygon:"Polygon",
freehandPolygon:"Frih\u00e5ndspolygon",clear:"Ryd",addPointToolTip:"Klik for at v\u00e6lge i dette omr\u00e5de",addShapeToolTip:"Tegn en form for at v\u00e6lge objekter",freehandToolTip:"Tryk og hold nede for at tegne en form for at v\u00e6lge objekter",startToolTip:"Tegn en form for at v\u00e6lge objekter"},errors:{layerNotFound:"Laget ${0} med id'et ${1} blev ikke fundet p\u00e5 kortet, kortlaget kan v\u00e6re \u00e6ndret siden widget-konfigurationen",queryNullID:"Objektet fra ${0} returnerede et ugyldigt id",
noSelectedLayers:"Ingen valgte lag med poster, der skal opdateres",inputValueError:"Ugyldig v\u00e6rdi i formularen"},_localized:{}}});