// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Milhas",acronym:"mi"},kilometers:{displayText:"Quil\u00f4metros",acronym:"km"},feet:{displayText:"P\u00e9s",acronym:"p\u00e9s"},meters:{displayText:"Metros",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Configura\u00e7\u00f5es da Pesquisa",defaultBufferDistanceLabel:"Configurar valor de dist\u00e2ncia do buffer padr\u00e3o",maxBufferDistanceLabel:"Configurar valor de dist\u00e2ncia do buffer m\u00e1ximo para localizar fei\u00e7\u00f5es",
bufferDistanceUnitLabel:"Unidades de dist\u00e2ncia do buffer",defaultBufferHintLabel:"Sugest\u00e3o: Utilize para configurar o valor padr\u00e3o de um buffer",maxBufferHintLabel:"Sugest\u00e3o: Utilize para configurar o valor m\u00e1ximo de um buffer",bufferUnitLabel:"Sugest\u00e3o: Defina a unidade para criar buffer",selectGraphicLocationSymbol:"S\u00edmbolo de local ou endere\u00e7o",graphicLocationSymbolHintText:"Sugest\u00e3o: S\u00edmbolo para endere\u00e7o pesquisado ou local clicado",fontColorLabel:"Selecionar cor da fonte para resultados da pesquisa",
fontColorHintText:"Sugest\u00e3o: Cor da fonte de resultados da pesquisa"},layerSelector:{selectLayerLabel:"Selecionar camadas de pesquisa",layerSelectionHint:"Sugest\u00e3o: Utilize o bot\u00e3o configurar para selecionar camadas",addLayerButton:"Configurar",okButton:"Ok",cancelButton:"Cancelar"},routeSetting:{routeSettingTabTitle:"Configura\u00e7\u00f5es de Dire\u00e7\u00e3o",routeServiceUrl:"Servi\u00e7o de Rota",travelModeServiceUrl:"Servi\u00e7o do Modo de Viagem",buttonSet:"Configurar",routeServiceUrlHintText:"Sugest\u00e3o: Clique em \u2018Configurar\u2019 para procurar e selecionar um servi\u00e7o de rota",
directionLengthUnit:"Unidades do comprimento de dire\u00e7\u00e3o",unitsForRouteHintText:"Sugest\u00e3o: Utilizado para exibir unidades para rota",selectRouteSymbol:"Selecionar s\u00edmbolo para exibir rota",routeSymbolHintText:"Sugest\u00e3o: Utilizado para exibir s\u00edmbolo de linha da rota",travelModeServiceUrlHintText:"Sugest\u00e3o: Clique em \u2018Configurar\u2019 para procurar e selecionar um Servi\u00e7o do Modo de Viagem",invalidTravelmodeServiceUrl:"Especifique um servi\u00e7o do Modo de Viagem v\u00e1lido ",
routingDisabledMsg:"Para habilitar dire\u00e7\u00f5es, garanta que a rota esteja habilitada no item do ArcGIS Online."},networkServiceChooser:{arcgislabel:"Adicionar do ArcGIS Online",serviceURLabel:"Adicionar URL de Servi\u00e7o",routeURL:"URL da Rota",validateRouteURL:"Validar",exampleText:"Exemplo",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",okButton:"Ok",cancelButton:"Cancelar",
nextButton:"Avan\u00e7ar",backButton:"Voltar",invalidRouteServiceURL:"Especifique um servi\u00e7o de Rota v\u00e1lido."},errorStrings:{bufferErrorString:"Inisra um valor num\u00e9rico v\u00e1lido.",selectLayerErrorString:"Selecione as camadas para pesquisar.",invalidDefaultValue:"A dist\u00e2ncia de buffer padr\u00e3o n\u00e3o pode estar em branco. Especifique a dist\u00e2ncia de buffer",invalidMaximumValue:"A dist\u00e2ncia de buffer m\u00e1xima n\u00e3o pode estar em branco. Especifique a dist\u00e2ncia de buffer",
defaultValueLessThanMax:"Especifique a dist\u00e2ncia de buffer padr\u00e3o dentro do limite m\u00e1ximo",defaultBufferValueGreaterThanZero:"Especifique a dist\u00e2ncia de buffer padr\u00e3o maior que 0",maximumBufferValueGreaterThanZero:"Especifique a dist\u00e2ncia de buffer m\u00e1xima maior que 0"},symbolPickerPreviewText:"Visualizar:",_localized:{}}});