// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negrito",copy:"Copiar",cut:"Cortar","delete":"Eliminar",indent:"Indentar",insertHorizontalRule:"R\u00e9gua horizontal",insertOrderedList:"Lista numerada",insertUnorderedList:"Lista marcada",italic:"It\u00e1lico",justifyCenter:"Alinhar ao centro",justifyFull:"Justificar",justifyLeft:"Alinhar \u00e0 esquerda",justifyRight:"Alinhar \u00e0 direita",outdent:"Recuar",paste:"Colar",redo:"Repetir",removeFormat:"Remover formato",selectAll:"Seleccionar tudo",strikethrough:"Rasurado",
subscript:"Inferior \u00e0 linha",superscript:"Superior \u00e0 linha",underline:"Sublinhado",undo:"Anular",unlink:"Remover liga\u00e7\u00e3o",createLink:"Criar liga\u00e7\u00e3o",toggleDir:"Alternar direc\u00e7\u00e3o",insertImage:"Inserir imagem",insertTable:"Inserir/Editar tabela",toggleTableBorder:"Alternar contorno da tabela",deleteTable:"Eliminar tabela",tableProp:"Propriedades da tabela",htmlToggle:"Origem HTML",foreColor:"Cor de primeiro plano",hiliteColor:"Cor de segundo plano",plainFormatBlock:"Estilo de par\u00e1grafo",
formatBlock:"Estilo de par\u00e1grafo",fontSize:"Tamanho do tipo de letra",fontName:"Nome do tipo de letra",tabIndent:"Indentar com a tecla Tab",fullScreen:"Alternar ecr\u00e3 completo",viewSource:"Ver origem HTML",print:"Imprimir",newPage:"Nova p\u00e1gina",systemShortcut:'A ac\u00e7\u00e3o "${0}" apenas est\u00e1 dispon\u00edvel no navegador utilizando um atalho de teclado. Utilize ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a",
"days-standAlone-short":"do sg te qu qi sx sb".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"agora","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Dia da semana","field-wed-relative+0":"esta quarta-feira","field-wed-relative+1":"pr\u00f3xima quarta-feira","dateFormatItem-GyMMMEd":"E, d 'de' MMM 'de' y G","dateFormatItem-MMMEd":"E, d 'de' MMM",eraNarrow:["AH"],"field-tue-relative+-1":"ter\u00e7a-feira passada","days-format-short":"do sg te qu qi sx sb".split(" "),
"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d 'de' MMMM 'de' y G","field-fri-relative+-1":"sexta-feira passada","field-wed-relative+-1":"quarta-feira passada","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"QQQQ 'de' y G","dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"da tarde","dateFormat-full":"EEEE, d 'de' MMMM 'de' y G",
"dateFormatItem-yyyyMEd":"E, dd/MM/y GGGGG","field-thu-relative+-1":"quinta-feira passada","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"a.m.","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"meio-dia","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["1.\u00ba trimestre",
"2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"timeFormat-long":"HH:mm:ss z","field-year":"Ano","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hora","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"este s\u00e1bado","field-sat-relative+1":"pr\u00f3ximo s\u00e1bado","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"hoje",
"field-thu-relative+0":"esta quinta-feira","field-day-relative+1":"amanh\u00e3","field-thu-relative+1":"pr\u00f3xima quinta-feira","dateFormatItem-GyMMMd":"d 'de' MMM 'de' y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["T1","T2","T3","T4"],"quarters-standAlone-wide":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"dateFormatItem-Gy":"y G",
"dateFormatItem-yyyyMMMEd":"E, d/MM/y G","dateFormatItem-M":"L","days-standAlone-wide":"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),"dateFormatItem-yyyyMMM":"MM/y G","dateFormatItem-yyyyMMMd":"d/MM/y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"este domingo","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"pr\u00f3ximo domingo","quarters-standAlone-abbr":["T1","T2","T3","T4"],eraAbbr:["AH"],
"field-minute":"Minuto","field-dayperiod":"Da manh\u00e3/da tarde","days-standAlone-abbr":"dom seg ter qua qui sex s\u00e1b".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"ontem","dateTimeFormat-long":"{1} '\u00e0s' {0}","dayPeriods-format-narrow-am":"a.m.","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d 'de' MMM","dateFormatItem-MEd":"E, dd/MM","dateTimeFormat-full":"{1} '\u00e0s' {0}","field-fri-relative+0":"esta sexta-feira",
"field-fri-relative+1":"pr\u00f3xima sexta-feira","field-day":"Dia","days-format-wide":"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),"field-zone":"Fuso hor\u00e1rio","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"ano passado","field-month-relative+-1":"m\u00eas passado","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a",
"dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"p.m.","days-format-abbr":"dom seg ter qua qui sex s\u00e1b".split(" "),eraNames:["AH"],"days-format-narrow":"DSTQQSS".split(""),"dateFormatItem-yyyyMd":"dd/MM/y GGGGG","field-month":"M\u00eas","days-standAlone-narrow":"DSTQQSS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"esta ter\u00e7a-feira","field-tue-relative+1":"pr\u00f3xima ter\u00e7a-feira","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})",
"dayPeriods-format-wide-am":"da manh\u00e3","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"esta segunda-feira","field-mon-relative+1":"pr\u00f3xima segunda-feira","dateFormat-short":"d/M/y G","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Segundo","field-sat-relative+-1":"s\u00e1bado passado","field-sun-relative+-1":"domingo passado",
"field-month-relative+0":"este m\u00eas","field-month-relative+1":"pr\u00f3ximo m\u00eas","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E, d","field-week":"Semana","dateFormat-medium":"d 'de' MMM, y G","field-week-relative+-1":"semana passada","field-year-relative+0":"este ano","dateFormatItem-yyyyM":"MM/y GGGGG","field-year-relative+1":"pr\u00f3ximo ano","dayPeriods-format-narrow-pm":"p.m.","dateFormatItem-yyyyQQQQ":"QQQQ 'de' y G","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss",
"dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM 'de' y G","field-mon-relative+-1":"segunda-feira passada","dateFormatItem-yyyy":"y G","field-week-relative+0":"esta semana","field-week-relative+1":"pr\u00f3xima semana","field-day-relative+2":"depois de amanh\u00e3","field-day-relative+-2":"anteontem",_localized:{}},"widgets/BatchAttributeEditor/nls/strings":{_widgetLabel:"Editor de Atributos em Batch",widgetIntroSelectByArea:"Utilize uma das ferramentas abaixo para criar o conjunto selecionado de elementos a atualizar.  Se a linha estiver \x3cfont class\x3d'maxRecordInIntro'\x3edestacada\x3c/font\x3e, o n\u00famero m\u00e1ximo de registos foi excedido.",
widgetIntroSelectByFeature:"Utilize a ferramenta abaixo para selecionar um elemento da camada \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e .  Este elemento ser\u00e1 utilizado selecionar e atualizar todos os elementos em interse\u00e7\u00e3o.  Se a linha estiver \x3cfont class\x3d'maxRecordInIntro'\x3edestacada\x3c/font\x3e, o n\u00famero m\u00e1ximo de registos foi excedido.",widgetIntroSelectByFeatureQuery:"Utilize a ferramenta abaixo para selecionar um elemento de \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e .  O atributo \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e desta camada ser\u00e1 utilizado para consultar as camadas abaixo e atualizar os elementos resultantes.  Se a linha estiver \x3cfont class\x3d'maxRecordInIntro'\x3edestacada\x3c/font\x3e, o n\u00famero m\u00e1ximo de registos foi excedido.",
widgetIntroSelectByQuery:"Introduza um valor para criar um conjunto de sele\u00e7\u00e3o.  Se a linha estiver \x3cfont class\x3d'maxRecordInIntro'\x3edestacada\x3c/font\x3e, o n\u00famero m\u00e1ximo de registos foi excedido.",layerTable:{colLabel:"Nome da Camada",numSelected:"#",colSyncStatus:""},noConfiguredLayers:"N\u00e3o foram configuradas quaisquer camadas edit\u00e1veis",editorPopupTitle:"Editor de Atributos em Batch",editorPopupSaveBtn:"Guardar",editorPopupMultipleValues:"",clear:"Limpar",
featuresUpdated:"${0} / ${1} elemento(s) atualizado(s)",featuresSelected:"${0} elemento(s) selecionado(s)",featuresSkipped:"Ignorados",search:"Pesquisar",queryInput:"Introduza um valor para consulta",noFilterTip:"Sem uma express\u00e3o de filtro definida, esta tarefa de consulta ir\u00e1 listar todos os elementos na fonte de dados especificada.",setFilterTip:"Por favor, defina o filtro corretamente.",filterPopup:"Filtrar Camada",cancel:"Cancelar",ok:"OK",drawBox:{point:"Ponto",line:"Linha",polyline:"Polilinha",
freehandPolyline:"Polilinha \u00c0 M\u00e3o Livre",extent:"Estender",polygon:"Pol\u00edgono",freehandPolygon:"Pol\u00edgono \u00c0 M\u00e3o Livre",clear:"Limpar",addPointToolTip:"Clique para selecionar nesta \u00e1rea",addShapeToolTip:"Desenhe uma forma para selecionar elementos",freehandToolTip:"Mantenha pessionado para desenhar uma forma para selecionar elementos",startToolTip:"Desenhe uma forma para selecionar elementos"},errors:{layerNotFound:"A camada ${0} com a ID ${1} n\u00e3o foi encontrada no mapa, o mapa pode ter sido alterado desde a configura\u00e7\u00e3o dos widgets",
queryNullID:"O elemento de ${0} foi devolvido com uma ID inv\u00e1lida",noSelectedLayers:"N\u00e3o existem camadas selecionadas com registos para atualizar",inputValueError:"Valor inv\u00e1lido no formul\u00e1rio"},_localized:{}}});