// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Chart/setting/nls/strings":{chartTasks:"T\u00e2ches du diagramme",addNew:"Ajouter une t\u00e2che",addNewTip:"Ajouter une t\u00e2che au diagramme",name:"Nom",set:"D\u00e9finir",setDataSource:"D\u00e9finir la source de donn\u00e9es",generalSettingsTip:"D\u00e9finissez la source de donn\u00e9es, le titre et la description des diagrammes.",chartModeSettingTip:"S\u00e9lectionnez un mode d\u2019analyse et d\u2019affichage des donn\u00e9es sous forme de diagrammes.",detailsSettingTip:"D\u00e9finissez l\u2019apparence du diagramme en sp\u00e9cifiant son type et sa couleur, ainsi que les valeurs \u00e0 repr\u00e9senter\u00a0:",
symbolSettingTip:"D\u00e9finissez l\u2019affichage cartographique des donn\u00e9es repr\u00e9sent\u00e9es.",addFilterTip:"Appliquer un filtre \u00e0 ces donn\u00e9es",dataSource:"Source de donn\u00e9es",noResults:"Aucune entit\u00e9 trouv\u00e9e.",chartTitle:"Titre du diagramme",description:"Description",chartingMode:"Affichage du diagramme",featureOption:"Afficher les valeurs entit\u00e9 par entit\u00e9",categoryOption:"Afficher les valeurs par cat\u00e9gorie",countOption:"Afficher le nombre d\u2019entit\u00e9s par cat\u00e9gorie",
fieldOption:"Afficher les valeurs attributaires sous forme de diagrammes",category:"Cat\u00e9gorie",axisLabel:"Etiquette de cat\u00e9gorie",categoryField:"Champ de cat\u00e9gorie",operation:"Op\u00e9ration",originalOption:"Utiliser les valeurs d\u2019origine",sumOption:"Somme",averageOption:"Moyenne",minOption:"Minimum",maxOption:"Maximum",valueFields:"Champs de valeur",moveUp:"Monter",moveDown:"Descendre",sortOrder:"Trier les diagrammes via les \u00e9tiquettes de cat\u00e9gorie",ascending:"Croissant",
descending:"D\u00e9croissant",chartType:"Type de diagramme",column:"Histogramme",bar:"Barres",line:"Courbes",pie:"Secteurs",chartColor:"Couleur du diagramme",showDataLabels:"Afficher les \u00e9tiquettes de donn\u00e9es",setSymbol:"Symbole de la s\u00e9lection",setHighLightColor:"Couleur de mise en surbrillance",settings:"Param\u00e8tres",mapInterationOptions:"Options d\u2019interaction cartographique",preview:"Aper\u00e7u",ok:"OK",cancel:"Annuler",close:"Fermer",setFilterTip:"D\u00e9finissez le filtre correctement ",
setChartTitleTip:"D\u00e9finissez le titre du diagramme.",setChartTypeTip:"S\u00e9lectionnez au moins un type de diagramme.",setDataFieldTip:"S\u00e9lectionnez au moins un champ de valeur.",setOutputFieldTip:"D\u00e9finissez les champs en sortie.",count:"Total",label:"Etiquette",horizontalAxis:"Axe horizontal",verticalAxis:"Axe vertical",dataLabels:"Etiquettes de donn\u00e9es",color:"Couleur",colorful:"Color\u00e9",monochromatic:"Monochromatique",noTaskTip:"Cliquez sur Nouveau pour ajouter une t\u00e2che de diagramme",
info:"Infos",charts:"Diagrammes",options:"Options",taskName:"Nom de la t\u00e2che",summary:"R\u00e9sum\u00e9",resultDescription:"Description du r\u00e9sultat",spatialFilterTip:"Choisissez le ou les filtres spatiaux utilis\u00e9s dans le widget pour limiter les r\u00e9sultats.",defaultOption:"Param\u00e8tre par d\u00e9faut",useCurrentExtentTip:"Partiellement ou enti\u00e8rement dans l'\u00e9tendue de la carte actuelle",useDrawGraphicTip:"Partiellement ou enti\u00e8rement dans la forme dessin\u00e9e sur la carte",
useFeaturesTip:"En fonction de leurs emplacements par rapport aux entit\u00e9s d'une autre couche",noSpatialLimitTip:"Ne pas limiter spatialement les r\u00e9sultats",drawingTools:"Outils de dessin",bufferSettings:"Param\u00e8tres de la zone tampon",defaultDistance:"Distance par d\u00e9faut",bufferDistance:"Distance de la zone tampon",defaultUnit:"Unit\u00e9 par d\u00e9faut",miles:"Miles",kilometers:"Kilom\u00e8tres",feet:"Pieds",meters:"M\u00e8tres",yards:"Yards",nauticalMiles:"Milles nautiques",
availableSpatialRelationships:"Relations spatiales disponibles",setSpatialRelationships:"D\u00e9finir les relations spatiales",availability:"Disponibilit\u00e9",relationship:"Relation",actions:"Actions",intersect:"intersectent",contain:"contiennent",areContainedIn:"sont contenus dans",cross:"croiser",envelopeIntersect:"intersection de l'enveloppe",overlap:"superposition",areOverlapped:"sont superpos\u00e9s",touche:"touchent",within:"dans",areWithin:"sont dans",indexIntersect:"intersection de l'index",
_localized:{}}});