// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Chart/setting/nls/strings":{chartTasks:"Diagramoppgaver",addNew:"Legg til ny",addNewTip:"Legg til en ny diagramoppgave",name:"Navn",set:"Angi",setDataSource:"Angi datakilde",generalSettingsTip:"Angi datakilde, tittel og beskrivelse for diagrammer.",chartModeSettingTip:"Velg hvordan data skal analyseres og vises som diagrammer.",detailsSettingTip:"Angi diagramutformingen ved \u00e5 velge type og farge og hvilke verdier som skal vises i diagrammet:",symbolSettingTip:"Angi kartvisning for diagramdata.",
addFilterTip:"Legg til filter for disse dataene",dataSource:"Datakilde",noResults:"Fant ingen geoobjekter.",chartTitle:"Diagramtittel",description:"Beskrivelse",chartingMode:"Diagramvisning",featureOption:"Vis verdier geoobjekt for geoobjekt",categoryOption:"Vis verdier etter kategori",countOption:"Vis antall geoobjekter etter kategori",fieldOption:"Vis attributtverdier som diagrammer",category:"Kategori",axisLabel:"Kategorietikett",categoryField:"Kategorifelt",operation:"Oppgave",originalOption:"Bruk opprinnelige verdier",
sumOption:"Sum",averageOption:"Gjennomsnittlig",minOption:"Minimum",maxOption:"Maksimum",valueFields:"Verdifelter",moveUp:"Flytt opp",moveDown:"Flytt ned",sortOrder:"Sorter diagramrekkef\u00f8lgen via kategorietiketter",ascending:"Stigende",descending:"Synkende",chartType:"Diagramtype",column:"Kolonnediagram",bar:"Stolpediagram",line:"Linjediagram",pie:"Sektordiagram",chartColor:"Diagramfarge",showDataLabels:"Vis dataetiketter",setSymbol:"Utvalgsymbol",setHighLightColor:"Uthevingsfarge",settings:"Innstillinger",
mapInterationOptions:"Alternativer for kartinteraksjon",preview:"Forh\u00e5ndsvisning",ok:"OK",cancel:"Avbryt",close:"Lukk",setFilterTip:"Angi filteret p\u00e5 riktig m\u00e5te. ",setChartTitleTip:"Du m\u00e5 angi en diagramtittel.",setChartTypeTip:"Du m\u00e5 velge minst \u00e9n diagramtype.",setDataFieldTip:"Du m\u00e5 velge minst ett verdifelt.",setOutputFieldTip:"Du m\u00e5 angi resultatfelter.",count:"Antall",label:"Etikett",horizontalAxis:"Horisontal akse",verticalAxis:"Vertikal akse",dataLabels:"Datap\u00e5skrifter",
color:"Farge",colorful:"Med flere farger",monochromatic:"Med bare \u00e9n farge",noTaskTip:"Klikk p\u00e5 Legg til ny for \u00e5 legge til en diagramoppgave",info:"Info",charts:"Diagrammer",options:"Alternativer",taskName:"Navn p\u00e5 oppgave",summary:"Sammendrag",resultDescription:"Resultatbeskrivelse",spatialFilterTip:"Velg et eller flere romlige filtre som er brukt til \u00e5 begrense resultatene i widgeten.",defaultOption:"Standard",useCurrentExtentTip:"Delvis eller helt innenfor gjeldende kartutstrekning",
useDrawGraphicTip:"Delvis eller helt innenfor formen tegnet p\u00e5 kartet",useFeaturesTip:"Basert p\u00e5 deres lokasjoner i forhold til geoobjekter i andre lag",noSpatialLimitTip:"Ikke bruk romlig begrensing p\u00e5 resultater",drawingTools:"Tegneverkt\u00f8y",bufferSettings:"Bufferinnstillinger",defaultDistance:"Standardavstand",bufferDistance:"Bufferavstand",defaultUnit:"Standardenhet",miles:"Miles",kilometers:"kilometer",feet:"fot",meters:"meter",yards:"Yards",nauticalMiles:"Nautiske mil",availableSpatialRelationships:"Tilgjengelige romlige relasjoner",
setSpatialRelationships:"Angi romlige relasjoner",availability:"Tilgjengelighet",relationship:"Relasjon",actions:"Handlinger",intersect:"skj\u00e6ringspunkt",contain:"inneholder",areContainedIn:"forekommer i",cross:"krysse",envelopeIntersect:"skj\u00e6ringspunkt for innhyllingskurve",overlap:"overlapping",areOverlapped:"er overlappet",touche:"tanger",within:"innenfor",areWithin:"er innenfor",indexIntersect:"skj\u00e6ringspunkt for indeks",_localized:{}}});