// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/DistrictLookup/setting/nls/strings":{units:{miles:"Miles",kilometers:"Kilom\u00e8tres",feet:"Pieds",meters:"M\u00e8tres"},layerSetting:{layerSettingTabTitle:"Param\u00e8tres de recherche",buttonSet:"D\u00e9finir",selectLayersLabel:"S\u00e9lectionner une couche",selectLayersHintText:"Astuce\u00a0: utilis\u00e9 pour s\u00e9lectionner la couche de polygones et la couche de points associ\u00e9e.",selectPrecinctSymbolLabel:"S\u00e9lectionner le symbole pour mettre le polygone en surbrillance",
selectGraphicLocationSymbol:"Symbole d\u2019adresse ou d\u2019emplacement",graphicLocationSymbolHintText:"Astuce\u00a0: symbole d\u2019une adresse recherch\u00e9e ou d\u2019un emplacement s\u00e9lectionn\u00e9",precinctSymbolHintText:"Astuce\u00a0: utilis\u00e9 pour afficher le symbole du polygone s\u00e9lectionn\u00e9"},layerSelector:{okButton:"OK",cancelButton:"Annuler",selectPolygonLayerLabel:"S\u00e9lectionner la couche de polygones",selectPolygonLayerHintText:"Astuce\u00a0: utilis\u00e9 pour s\u00e9lectionner la couche de polygones.",
selectRelatedPointLayerLabel:"S\u00e9lectionner la couche de points associ\u00e9e \u00e0 la couche de polygones",selectRelatedPointLayerHintText:"Astuce\u00a0: utilis\u00e9 pour s\u00e9lectionner la couche de points associ\u00e9e \u00e0 la couche de polygones",polygonLayerNotHavingRelatedLayer:"S\u00e9lectionnez une couche de polygones poss\u00e9dant une couche de points associ\u00e9e.",errorInSelectingPolygonLayer:"S\u00e9lectionnez une couche de polygones poss\u00e9dant une couche de points associ\u00e9e.",
errorInSelectingRelatedLayer:"S\u00e9lectionnez la couche de points associ\u00e9e \u00e0 la couche de polygones."},routeSetting:{routeSettingTabTitle:"Param\u00e8tres de direction",routeServiceUrl:"Service de calcul d'itin\u00e9raire",travelModeServiceUrl:"Service de mode de d\u00e9placement",buttonSet:"D\u00e9finir",routeServiceUrlHintText:"Astuce\u00a0: cliquez sur \u2018D\u00e9finir\u2019 pour rechercher et s\u00e9lectionner un service de calcul d\u2019itin\u00e9raire d\u2019analyse du r\u00e9seau",
directionLengthUnit:"Unit\u00e9s de longueur de la direction",unitsForRouteHintText:"Astuce\u00a0: utilis\u00e9 pour afficher les unit\u00e9s signal\u00e9es pour l\u2019itin\u00e9raire",selectRouteSymbol:"S\u00e9lectionner le symbole pour afficher l\u2019itin\u00e9raire",routeSymbolHintText:"Astuce\u00a0: utilis\u00e9 pour afficher le symbole lin\u00e9aire de l\u2019itin\u00e9raire",travelModeServiceUrlHintText:"Astuce\u00a0: cliquez sur \u2018D\u00e9finir\u2019 pour rechercher et s\u00e9lectionner un service de mode de d\u00e9placement",
invalidTravelmodeServiceUrl:"Sp\u00e9cifiez un service de mode de d\u00e9placement valide",routingDisabledMsg:"Pour activer les directions, assurez-vous que le calcul d\u2019itin\u00e9raire est activ\u00e9 dans l\u2019\u00e9l\u00e9ment ArcGIS\u00a0Online."},networkServiceChooser:{arcgislabel:"Ajouter depuis ArcGIS Online",serviceURLabel:"Ajouter une URL de service",routeURL:"URL de l\u2019itin\u00e9raire",validateRouteURL:"Valider",exampleText:"Exemple",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",
hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",okButton:"OK",cancelButton:"Annuler",nextButton:"Suivant",backButton:"Pr\u00e9c\u00e9dent",invalidRouteServiceURL:"Sp\u00e9cifiez un service d\u2019itin\u00e9raire valide."},symbolPickerPreviewText:"Aper\u00e7u :",_localized:{}}});