// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Query/setting/SortFields.html":'\x3cdiv\x3e\r\n\t\x3cdiv\x3e${nls.configureFieldsTip}\x3c/div\x3e\r\n\t\x3cdiv class\x3d"add-with-icon" data-dojo-attach-event\x3d"onclick:_onAddNewClicked"\x3e\r\n\t\t\x3cspan class\x3d"jimu-icon jimu-icon-add"\x3e\x3c/span\x3e\r\n\t\t\x3cspan class\x3d"add-label"\x3e${nls.addNew}\x3c/span\x3e\r\n\t\x3c/div\x3e\r\n\t\x3cdiv data-dojo-attach-point\x3d"tableDiv"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/registry dijit/form/Select dojo/text!./SortFields.html dojo/on dojo/query dojo/_base/lang dojo/_base/array dojo/_base/html jimu/dijit/SimpleTable".split(" "),function(n,p,q,r,l,m,s,g,h,d,e,k,t){return n([p,q,r],{baseClass:"jimu-query-setting-sort-fields",templateString:s,_allFieldNames:null,_sortTipClassName:"sort-tip",_fieldNameSelectClassName:"field-name-select",_sortTypeSelectClassName:"sort-type-select",
nls:null,layerDefinition:null,orderByFields:null,validSortFieldTypes:[],postCreate:function(){this.inherited(arguments);var a=e.filter(this.layerDefinition.fields,d.hitch(this,function(b){return 0<=this.validSortFieldTypes.indexOf(b.type)}));this._allFieldNames=e.map(a,function(b){return b.name});this._initTable();this.orderByFields?this._setOrderByFields(this.orderByFields):this.orderByFields=[]},_initTable:function(){var a={autoHeight:!1,style:"height:187px",fields:[{name:"sortTip",title:this.nls.field,
type:"text",width:"100px"},{name:"fieldName",title:"",type:"extension",create:d.hitch(this,this._create4FieldName),setValue:d.hitch(this,this._setValue4FieldName),getValue:d.hitch(this,this._getValue4FieldName)},{name:"sortType",title:this.nls.sortingOrder,type:"extension",create:d.hitch(this,this._create4SortType),setValue:d.hitch(this,this._setValue4SortType),getValue:d.hitch(this,this._getValue4SortType)},{name:"actions",title:this.nls.actions,type:"actions",actions:["up","down","delete"],width:"120px"}]};
this.table=new t(a);this.own(g(this.table,"row-up",d.hitch(this,this._onTableRowUp)));this.own(g(this.table,"row-down",d.hitch(this,this._onTableRowDown)));this.table.placeAt(this.tableDiv);this.table.startup()},getOrderByFields:function(){var a=this.table.getData();return e.map(a,d.hitch(this,function(b){return b.fieldName+" "+b.sortType}))},_getFieldAlias:function(a){for(var b=a,f=this.layerDefinition.fields,c=0;c<f.length;c++)if(f[c].name===a){b=f[c].alias||a;break}return b},_getRestFields:function(){var a=
this._getAllFieldSelects(),b=e.map(a,d.hitch(this,function(b){return b.get("value")}));return e.filter(this._allFieldNames,d.hitch(this,function(a){return 0>b.indexOf(a)}))},_onAddNewClicked:function(){var a=this._getRestFields();if(0!==a.length){var b="",b=0===this.table.getRows().length?this.nls.sortBy:this.nls.thenBy;this.table.addRow({sortTip:b,fieldName:a[0],sortType:"ASC"})}},_setOrderByFields:function(a){this.table.clear();a=a||[];e.forEach(a,d.hitch(this,function(b,a){var c=b.split(" "),d=
c[0],e="ASC";c[1]&&"string"===typeof c[1]&&(c[1]=c[1].toUpperCase(),"DESC"===c[1]&&(e="DESC"));c="";c=0===a?this.nls.sortBy:this.nls.thenBy;this.table.addRow({sortTip:c,fieldName:d,sortType:e})}))},_getAllFieldSelects:function(){var a=h("."+this._fieldNameSelectClassName,this.table.tbody);return e.map(a,d.hitch(this,function(b){return l.byNode(b)}))},_getSelectFromTd:function(a,b){var d=h("."+b,a)[0];return l.byNode(d)},_onTableRowUp:function(){this._resetSortTips()},_onTableRowDown:function(){this._resetSortTips()},
_getAllSortTipDivs:function(){return h(".sortTip .normal-text-div",this.table.tbody)},_resetSortTips:function(){var a=this.table.getRows();e.forEach(a,d.hitch(this,function(b,a){var c="",c=0===a?this.nls.sortBy:this.nls.thenBy;this.table.editRow(b,{sortTip:c})}));a=this._getAllSortTipDivs();e.forEach(a,d.hitch(this,function(b,a){b.innerHTML=0===a?this.nls.sortBy:this.nls.thenBy}))},_create4FieldName:function(a){var b=this._getRestFields(),f=new m({style:"width:120px;height:20px;"});k.addClass(f.domNode,
this._fieldNameSelectClassName);k.addClass(f.domNode,"restrict-select-width");f.placeAt(a);e.forEach(b,d.hitch(this,function(a){var b=this._getFieldAlias(a);f.addOption({value:a,label:b})}));this.own(g(f,"change",d.hitch(this,this._onFieldNameSelectChanged)))},_setValue4FieldName:function(a,b){this._getSelectFromTd(a,this._fieldNameSelectClassName).set("value",b)},_getValue4FieldName:function(a){return this._getSelectFromTd(a,this._fieldNameSelectClassName).get("value")},_onFieldNameSelectChanged:function(){var a=
this._getAllFieldSelects();e.forEach(a,d.hitch(this,function(a){var f=a.get("value");a.domNode.title="";var c=a.getOptions(f);c&&c.label&&(a.domNode.title=c.label);c=a.getOptions();c=e.filter(c,d.hitch(this,function(a){return a.value!==f}));a.removeOption(c);c=this._getRestFields();e.forEach(c,d.hitch(this,function(c){if(c!==f){var d=this._getFieldAlias(c);a.addOption({value:c,label:d})}}))}))},_create4SortType:function(a){var b=new m({style:"width:120px;height:20px;"});k.addClass(b.domNode,this._sortTypeSelectClassName);
b.placeAt(a);b.addOption({value:"ASC",label:this.nls.ascending,selected:!0});b.addOption({value:"DESC",label:this.nls.descending})},_setValue4SortType:function(a,b){var d=this._getSelectFromTd(a,this._sortTypeSelectClassName);("ASC"===b||"DESC"===b)&&d.set("value",b)},_getValue4SortType:function(a){return this._getSelectFromTd(a,this._sortTypeSelectClassName).get("value")}})});