// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/setting/nls/strings":{queries:"Sp\u00f8rringsoppgaver",addNew:"Legg til ny",queryLayer:"Kj\u00f8r sp\u00f8rring for lag",setSource:"Angi",setDataSource:"Angi datakilde",name:"Navn",querySource:"Datakilde",queryName:"Navn p\u00e5 oppgave",queryDefinition:"Filterdefinisjon",resultsSetting:"Resultatinnstilling",symbolSetting:"Symbolinnstilling",resultSettingTip:"Definer hva som skal vises i resultatene og hvordan de skal vises.",resultItemTitle:"Tittelelement for resultat",resultItemContent:"Innhold i resultatelement",
fieldsSetTip:"Merk av for feltene du vil vise. Velg et felt for \u00e5 oppdatere aliaset, rekkef\u00f8lgen eller formatet.",addField:"Legg til felt",visibility:"Synlighet",alias:"Alias",specialType:"Spesiell type",actions:"Handlinger",none:"Ingen",link:"Kobling",image:"Bilde",noField:"Ingen felt",operationalLayerTip:"Legg til resultat som operativt kartlag",setLayerSymbolTip:"Angi symbol for sp\u00f8rringsresultater: ",setSelectedSymbolTip:"Angi symbolet for det valgte geoobjektet.",notUseFilter:"Ikke bruk filter",
setSourceTip:"Angi kilde for sp\u00f8rring.",setFilterTip:"Angi filteret p\u00e5 riktig m\u00e5te.",ok:"OK",cancel:"Avbryt",noFilterTip:"Uten definert filteruttrykk viser denne sp\u00f8rringoppgaven alle geoobjekter i den angitte datakilden.",relationships:"Relasjoner",addRelationshipLayer:"Legg til ny relasjon",relatedTo:"Gjelder",selectOption:"Du m\u00e5 velge...",resultItemSorting:"Sortering av resultatelementer",field:"Felt",sortingOrder:"Rekkef\u00f8lge",configureFieldsTip:"Konfigurer feltene som sp\u00f8rringsresultatene skal sorteres etter.",
setSortingFields:"Angi sorteringsfelter",ascending:"Stigende",descending:"Synkende",sortBy:"Sorter etter",thenBy:"Deretter etter",addTask:"Legg til oppgave",noTasksTip:'Ingen oppgaver. Klikk p\u00e5 "${addTask}" for \u00e5 begynne.',infoText:"Info",filters:"Filtre",results:"Resultater",optionsText:"Alternativer",summaryText:"Sammendrag",attributeFilter:"Attributtfilter",attributeFilterTip:"Definer attributtuttrykk som skal brukes i widgeten til \u00e5 filtrere sp\u00f8rringslaget.",noExpressionDefinedTip:"Det er ingen definerte uttrykk.",
needInputValuesTip:"Verdier m\u00e5 angis ved kj\u00f8retid",setExpressions:"Angi uttrykk",spatialFilter:"Geografisk filter",spatialFilterTip:"Velg et eller flere romlige filtre som er brukt til \u00e5 begrense resultatene i widgeten.",defaultOption:"Standard",useCurrentExtentTip:"Delvis eller helt innenfor gjeldende kartutstrekning",useDrawGraphicTip:"Delvis eller helt innenfor formen som er tegnet p\u00e5 kartet",useFeaturesTip:"Basert p\u00e5 deres lokasjoner i forhold til geoobjekter i andre lag",
noSpatialLimitTip:"Ikke bruk romlig begrensing p\u00e5 resultater",drawingTools:"Tegneverkt\u00f8y",bufferSettings:"Bufferinnstillinger",defaultDistance:"Standardavstand",bufferDistance:"Bufferavstand",defaultUnit:"Standardenhet",miles:"Miles",kilometers:"kilometer",feet:"fot",meters:"meter",yards:"Yards",nauticalMiles:"Nautiske mil",availableSpatialRelationships:"Tilgjengelige romlige relasjoner",setSpatialRelationships:"Angi romlige relasjoner",availability:"Tilgjengelighet",relationship:"Relasjon",
label:"Etikett",intersect:"skj\u00e6ringspunkt",contain:"inneholder",areContainedIn:"forekommer i",cross:"krysse",envelopeIntersect:"skj\u00e6ringspunkt for innhyllingskurve",overlap:"overlapping",areOverlapped:"er overlappet",touche:"tanger",within:"innenfor",areWithin:"er innenfor",indexIntersect:"skj\u00e6ringspunkt for indeks",itemTitle:"Elementtittel",displayFields:"Vis felter",sortingFields:"Sorteringsfelter",setDisplayFields:"Angi vsiningsfelter",symbol:"Symbol",setSymbol:"Angi symbol",serviceSymbolTip:"Bruk symboler definert av laget",
exportTip:"Vis Eksporter-knappen",keepResultsTip:"Behold resultatene p\u00e5 kartet etter at widgeten er lukket",queryRelatedRecords:"Foreta sp\u00f8rring i relaterte poster",createLayerForTaskTip:"Angi hvordan oppgaven oppretter lag",oneLayerForTaskTip:"Opprett bare ett lag for denne oppgaven",multipleLayerForTaskTip:"Opprett et nytt lag hver gang oppgaven utf\u00f8res",_localized:{}}});